prefix-dev/pixi

src/project.rs

Warns in the error for missing dependencies

Improve Error: Add check if dependencies are present

---

src/progress.rs

Had issues with it as the default size was to big for the default size of a linux terminal

Improve looks: auto scale download bar

---

.github/workflows/rust.yml
Cargo.toml

This disables LTO for non-release-releases :)

Conditional LTO

---

scripts/install.sh

I managed to include a small typo that checks the wrong file 😬 
thanks @jonashaag!

fix: typo in config.fish name

---

src/environment.rs
src/virtual_packages.rs

The virtual packages were not considered when checking if a lock file is up to date. This caused any package that depended on a virtual package to always be out of date.
Fix #103

fix: issue #103

---

src/project/mod.rs

Improves the error message for parsing the `pixi.toml` file.
```
error: failed to parse pixi.toml from E:\Developer\prefix\pixi\myproject
Caused by:
TOML parse error at line 2, column 8
|
2 | name = 3
|        ^
invalid type: integer `3`, expected a string
```

feat: improved toml error messages

---

Cargo.lock
Cargo.toml
src/cli/run.rs

Bump rattler to get better shell detection from https://github.com/mamba-org/rattler/pull/219.
@ruben-arts @wolfv @tdejager can you check if running commands and stuff still work correctly for you?

bump: rattler

---

examples/cpp-sdl/.gitignore
examples/cpp-sdl/CMakeLists.txt
examples/cpp-sdl/README.md
examples/cpp-sdl/pixi.lock
examples/cpp-sdl/pixi.toml
examples/cpp-sdl/src/main.cc

Adds an example on how to use pixi with C++.

example: shows how to use c++ and sdl

---

docs/README.md
src/cli/global/install.rs
src/cli/global/mod.rs

rename global add to global install

---

src/project/mod.rs

`add` command was broken, this should fix it.

fix: fix add command

---

src/cli/init.rs

Remove use of current_dir so the function becomes more testable.

feat: remove use of env_current_dir

---

src/cli/install.rs
src/cli/run.rs
src/cli/shell.rs
src/project/mod.rs

refactor: made a method for project discovery or loading

---

Cargo.lock
src/cli/global/install.rs
src/cli/run.rs
src/cli/shell.rs

Related: https://github.com/mamba-org/rattler/pull/232

fix: specify the path modification for shell activation

---

docs/Community.md
docs/README.md

Added a built using pixi section. We could make an issue for people to add to this :)

doc: built using pixi

---

examples/README.md

Added other repostitories to the README as an example.

doc: added other repository examples to the readme

---

docs/README.md

Since `pixi global` appears to be just like `condax`.

Mention condax in README

---

Cargo.lock

Bump rattler to fix #210 via https://github.com/mamba-org/rattler/pull/262

add newlines to the end of `pixi install` scripts

---

Cargo.lock
Cargo.toml
src/cli/mod.rs
src/cli/upload.rs

feat: add `pixi upload` command to upload packages to prefix.dev

---

src/cli/task.rs
src/project/mod.rs

feat: list tasks

---

.github/workflows/rust.yml

I would like to have an aarch64 release for pixi :)

Also build for aarch64

---

src/cli/global/install.rs

Dont use a shebang on windows!

fix: dont use a shebang on windows

---

README.md

Updates the banner with Paxton!
I included both a webp file (87kb) and a png (192kb) if webp is not supported by the browser.

feat: updated banner

---

src/cli/init.rs
src/cli/run.rs
src/repodata.rs
src/task/mod.rs
tests/common/builders.rs
tests/common/mod.rs
tests/task_tests.rs

With recently introduced changes strictly aliased tasks were not working properly. This PR fixes the issue and adds a test so it never breaks again!

fix: alias was broken

---

.gitignore

fix: ignore ds-store

---

docs/Community.md

As requested in https://github.com/prefix-dev/pixi/discussions/300#discussioncomment-6813742

Add VegaFusion to Community.md

---

src/project/mod.rs
src/virtual_packages.rs

Filter `system-requirements` that are not meant for the current OS

---

Cargo.lock
Cargo.toml
src/cli/auth.rs
src/cli/info.rs
src/project/snapshots/pixi__project__manifest__test__invalid_target_specific.snap
src/virtual_packages.rs
tests/common/package_database.rs

Fix required changes to align with latest version of rattler.

Align with latest rattler version `0.9.0`

---

src/prompt.rs

Previously the prompt wouldn't update if you changed dir. 
This now reruns the prompt every time it prints
Closes #384

fix pwsh prompt

---

Cargo.lock
Cargo.toml
src/environment.rs
tests/common/mod.rs

Bumps rattler to the latest version.

bump: ratter 0.11.0

---

Cargo.lock

bump rattler and tracing

---

src/cli/task.rs

fix: sort task list

---

src/cli/completion.rs
src/cli/snapshots/pixi__cli__completion__tests__zsh_completion.snap

Closes #423 
It feels like this should be easier but it will not accept an empty value.

fix: no error when completing nothing

---

Cargo.lock
Cargo.toml
src/environment.rs
src/project/snapshots/pixi__project__manifest__test__mapped_dependencies.snap

Update to the latest rattler, to prepare for release

bump: up rattler to v0.12.0 and update code to use new channel feature.

---

Cargo.lock
examples/pypi/pixi.lock
src/environment.rs
src/progress.rs

This fixes a few crashes I had with the progress bars.

fix: progress issues

---

src/cli/init.rs

fix: actually add the template and give better errors

---

Cargo.lock
src/environment.rs

Small API change, should not change anything!

feat: update rip with small api change

---

.github/workflows/release.yml

:man_facepalming: missed that this was a placeholder

Fix: `winget-releaser` gets correct identifier

---

examples/pypi/pixi.lock
examples/pypi/pixi.toml

add jupyter extra to black to test extras

---

src/project/manifest/environment.rs
src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/snapshots/pixi__project__manifest__test__invalid_key.snap

Adds the ability to define a feature or environments in the pixi.toml
> [!WARNING]
> Does not implement using these environments! Just the de-serialization.

De-serialization of `features` and `environments`

---

Cargo.lock
Cargo.toml

Should fix https://github.com/prefix-dev/pixi/issues/631

Bump rattler

---

src/cli/shell_hook.rs

feat: add default environment to the shell-hook script

---

src/cli/mod.rs
src/cli/shell_hook.rs

@ruben-arts / @orhun check it out :)

fix: `shell-hook`:use the correct prefix and make sure it is up to date

---

src/cli/list.rs

feat: list specific environment

---

README.md

fix: make svg a gif

---

install/install.sh

fix: logic PIXI_NO_PATH_UPDATE variable

---

docs/environment.md

https://github.com/prefix-dev/pixi/discussions/397#discussioncomment-8572062
I haven't tested this on windows

docs: Add direnv usage

---

Cargo.lock
Cargo.toml

Fixes https://github.com/prefix-dev/pixi/issues/799

fix: Update rattler to v0.19.0.

---

.github/workflows/docs.yml

This should update the install scripts on every push to main

docs: update install scripts in action

---

src/install_pypi.rs

Made the code a bit more clear, when a re-install happens for a pypi package.

fix: made the uv re-install logic a bit more clear

---

src/cli/list.rs

closes https://github.com/prefix-dev/pixi/issues/904

fix: highlight pypi deps in pixi list

---

src/task/task_environment.rs
src/task/task_graph.rs

fix: default to the default environment if possible

---

Cargo.lock
Cargo.toml
src/install_pypi.rs
src/lock_file/resolve.rs
tests/install_tests.rs

feat: upgrade to uv 0.1.16, updated for changes in the API

---

src/project/manifest/mod.rs
src/project/manifest/snapshots/pixi__project__manifest__tests__add_channels.snap

fix: use correct name of the channel on adding

---

mkdocs.yml
pixi.lock
pixi.toml

See https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661 and https://github.com/Python-Markdown/markdown/issues/3
Before:
After:

docs: Fix list indentation

---

docs/stylesheets/extra.css

docs: improve light mode

---

src/cli/list.rs

Show more pypi info in the `pixi list` command. This was annoying me for a while:
For this toml:
```toml
[project]
name = "bla"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim de Jager <tim@prefix.dev>"]
platforms = ["osx-arm64"]
[dependencies]
python = ">=3.12.2,<3.13"
flask = "*"
```
Before:
```bash
Package          Version   Build               Size       Kind   Source
blinker          1.7.0                                    pypi
bzip2            1.0.8     h93a5062_5          119.5 KiB  conda  bzip2-1.0.8-h93a5062_5.conda
ca-certificates  2024.2.2  hf0a4a13_0          152.1 KiB  conda  ca-certificates-2024.2.2-hf0a4a13_0.conda
click            8.1.7                                    pypi
flask …
```

feat: show more pypi metadata in list

---

docs/cli.md

Reflect #723 #854 #948 #962 changes

chore(docs): update global cli documentation

---

src/project/manifest/mod.rs
src/project/manifest/snapshots/pixi__project__manifest__tests__invalid_key.snap

chore: allow "tool" table in the pixi toml

---

docs/ide_integration/pycharm.md
mkdocs.yml

Closes #189 
https://github.com/pavelzw/pixi-pycharm

docs: Add PyCharm documentation

---

src/prompt.rs

fix: correct fish prompt

---

docs/cli.md
src/cli/search.rs

feat: improve `pixi search` with platform selection and making limit optional

---

src/environment.rs
tests/install_tests.rs

fix: Create conda-meta/history file

---

docs/design_proposals/multi_environment_proposal.md
pixi.lock
pixi.toml

I tried to make a minimal example but I'm having a hard time reproducing the issue so going to remove the linenums for now as they aren't that important. 
Fixes #1001

fix: removed linenums to avoid buggy visualization

---

.github/workflows/schema.yml
.pre-commit-config.yaml
pixi.lock
pixi.toml
schema/model.py
schema/schema.json
schema/test_manifest.py

Modifies the schema to:
- Turns platform strings into literals. 
- Move schema tasks to seperate environment.

feat: platform literals

---

examples/cpp-sdl/pixi.toml

This does some minor cleanup to the CMake cpp-sdl example.

chore: minor cleanup

---

docs/cli.md

Request for the addtion coming from: https://github.com/prefix-dev/pixi/discussions/1070

docs: add lockfile update description in preparation for pixi update

---

docs/index.md

Improve the documentation on the installation script. Idea for improving sparked by @pavelzw in https://github.com/prefix-dev/pixi/pull/1129#issuecomment-2041184670

docs: improve install script docs

---

.github/workflows/rust.yml

Hopefully this helps with the flacky tests. It's not a fix its just a mitigation to get working tests again. Don't judge :man_shrugging:

ci: add retries to nextest

---

src/cli/list.rs
src/cli/tree.rs

fix: add env name if not default to tree and list command

---

src/lock_file/mod.rs

Extending this error:
```
× environment default and platform linux-64 refers to a package that does not exist: https://conda.anaconda.org/conda-forge/linux-64/bladiebla.tar.bz2
```
with:
```
× Failed to load lock file from `/home/rarts/development/pixi/pixi.lock`
╰─▶ environment default and platform linux-64 refers to a package that does not exist: https://conda.anaconda.org/conda-forge/linux-64/bladiebla.tar.bz2
```

fix: improve error on parsing lockfile

---

docs/ide_integration/pycharm.md

depends on https://github.com/pavelzw/pixi-pycharm/pull/13

docs: Add Windows support for PyCharm integration

---

README.md
docs/advanced/github_actions.md

Depends on https://github.com/prefix-dev/setup-pixi/pull/87

docs: update action documentation

---

docs/features/environment.md

Hey @pavelzw I recently made sure that `direnv` is available for all conda-forge platforms :) Maybe you have additional thoughts on the commands to run for installation?

docs: add note about installing direnv with pixi

---

src/lock_file/records_by_name.rs
src/lock_file/satisfiability.rs
tests/satisfiability/pypi-extras/has-extras/pyproject.toml
tests/satisfiability/pypi-extras/pixi.lock
tests/satisfiability/pypi-extras/pixi.toml
tests/satisfiability/pypi-extras/use-with-extras/pyproject.toml

This PR fixes a bug where if extras where involved in a certain way the satisfiability would always fail. This PR fixes this behavior and includes a test that shows that a project with recursive extra usage remains satisfiable.

fix: satisfiability with pypi extras

---

src/lock_file/resolve.rs

The fix that was made in #1186 was only applied to Source Distributions. This was incorrect, refactored into seperate method and used for both built and source dists.
Still not really sure how to add a good test in CI, we could use hatches dynamic metadata to generate a pyproject.toml but still seems more trouble than its worth to me :)

fix: uses the special-case uv path handling for both built and source

---

Cargo.lock
Cargo.toml

Bump rattler to the latest release including:
- https://github.com/mamba-org/rattler/pull/618
- https://github.com/mamba-org/rattler/pull/616

chore: bump rattler

---

Cargo.lock
Cargo.toml
src/install_pypi.rs
src/lock_file/satisfiability.rs

feat: update to uv 0.1.38

---

src/project/manifest/mod.rs

fix: add error if channel or platform doesn't exist on remove

---

examples/pypi/pixi.lock
examples/pypi/pixi.toml
src/lock_file/resolve.rs
src/lock_file/update.rs
tests/add_tests.rs
tests/common/mod.rs
tests/install_tests.rs

feat: use locked_pypi_packages as preferences in the pypi solve

---

src/cli/completion.rs
src/cli/global/mod.rs
src/cli/install.rs
src/cli/list.rs
src/cli/mod.rs
src/cli/run.rs
src/cli/search.rs
src/cli/self_update.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/cli/task.rs
src/cli/upload.rs
tbump.toml

Found a really good read here: https://clig.dev/#help
I did a cleanup based on what I've read there. It's just an increment but would love to take more from it.

chore: cleanup and improve cli

---

Cargo.lock
Cargo.toml

Bump back the rattler versions, so that we are dependent on rattler releases again.

chore: bump back rattler versions

---

src/cli/global/list.rs

feat: Sort packages in `list_global_packages`

---

src/install_pypi.rs

I added a test for this issue: https://github.com/prefix-dev/pixi/issues/1418. That I think the recent uv upgrade has fixed, as that code has changed. I'll ask in the thread for a verification. Anyways, I think it would be good to merge this as a regression test.

feat: added test for special chars wheel filename

---

src/cli/mod.rs

fix: render help for `--frozen`

---

Cargo.lock
Cargo.toml
src/project/mod.rs

fix: creation of parent dir of symlink 

---

src/cli/info.rs
src/cli/self_update.rs
src/consts.rs
src/environment.rs
src/lock_file/update.rs
tests/install_tests.rs

This helps other tools find information about the environment

feat: add environment file to environment dir

---

Cargo.lock
Cargo.toml
src/install_pypi.rs

fix: replace http code %2b with +

---

CHANGELOG.md
CITATION.cff
Cargo.lock
Cargo.toml
docs/advanced/github_actions.md
install/install.ps1
install/install.sh
schema/schema.json
src/cli/mod.rs
tbump.toml

chore: bump to 0.24.1

---

docs/Community.md

~for glum and metalearners, the PR is still open. let's wait for them with merging~

docs: Add some other quantco repos

---

src/cli/exec.rs

When the exec was missing a command an error occured. This gives a better error message.

feat: better error when exec is missing a cmd

---

src/cli/exec.rs

Let's exec make use of the authenticated client as well.
@pavelzw  could you give this a go?

feat: make exec use authenticated client

---

docs/ide_integration/pycharm.md

xref https://github.com/pavelzw/pixi-pycharm/pull/28

docs: Add note to mark directory as excluded in pixi-pycharm

---

pixi.toml

fix: pre-commit install pixi task

---

src/cli/completion.rs
src/cli/snapshots/pixi__cli__completion__tests__nushell_completion.snap

feat: Add nushell completions for `pixi run`

---

CHANGELOG.md
CITATION.cff
Cargo.lock
Cargo.toml
docs/advanced/github_actions.md
install/install.ps1
install/install.sh
schema/schema.json
src/cli/mod.rs
tbump.toml

chore: bump version to 0.26.0

---

examples/flask-hello-world-pyproject/pixi.lock
pixi.toml
tests/run_all_examples.py

Added a script for testing all examples using a development version or release version of pixi.
@ruben-arts do we need some documentation for this somewhere or?

feat: added script and tasks for testing

---

src/cli/init.rs

As discussed in https://github.com/prefix-dev/pixi/pull/1673#issuecomment-2252472007

chore: sort `pixi init` output

---

src/cli/global/install.rs

I tried to fix #1685 but that was already fixed by someone else. Then I found my global install was not working because of this issue: 
The fix is using the `config.default_channels()` vs the `config.default_channels`...
The rest of this PR is cleanup

chore: fix global install 

---

src/cli/mod.rs
src/cli/search.rs
src/lib.rs
src/utils/defaults.rs
src/utils/indicatif.rs
src/utils/mod.rs

Merges utils file and module together.

refactor: merge utils

---

src/cli/exec.rs

Fixes https://github.com/prefix-dev/pixi/issues/1748

fix: Authenticate exec package download

---

src/cli/init.rs
tests/common/builders.rs
tests/common/mod.rs
tests/init_tests.rs
tests/pixi_tomls/pyproject_no_pixi.toml

fix: dont accidentally wipe pyproject.toml on `init`

---

.github/workflows/rust.yml
.pre-commit-config.yaml
crates/pixi_manifest/src/target.rs
crates/pixi_spec/src/serde.rs

- add `--workspace` flag
- fix existing warnings

ci: run `clippy` on all workspaces

---

docs/design_proposals/pixi_global_manifest.md

Ask for community feedback in the design proposal

docs: community feedback `pixi global`

---

src/lock_file/package_identifier.rs
src/lock_file/records_by_name.rs

I had some compiler warnings in pixi. Dunno why CI didnt find these?? I fixed them.

fix: trait impl override

---

src/cli/init.rs
src/cli/install.rs
src/cli/list.rs
src/cli/project/channel/add.rs
src/cli/project/channel/remove.rs
src/cli/project/platform/add.rs
src/cli/project/platform/remove.rs
src/cli/remove.rs
src/cli/run.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/cli/tree.rs
src/environment.rs
src/lock_file/update.rs
tests/common/mod.rs
tests/install_tests.rs
tests/solve_group_tests.rs

The return parameter was never used

refactor: Rename `get_up_to_date_prefix` to `update_prefix`

---

src/cli/has_specs.rs

Make `specs` and `pypi_deps` more functional

refactor: Make `HasSpecs` implementation more functional

---

docs/design_proposals/pixi_global_manifest.md

docs: make `channels` required in `pixi global` manifest

---

src/lock_file/resolve/pypi.rs
src/lock_file/resolve/resolver_provider.rs

To ease with debugging, add some statistics when conda packages that are PyPI imposter packages, are actually hit by a request during a uv resolve.

feat: add some logging for when packages are actually overriden by conda

---

src/lock_file/resolve/pypi.rs
src/lock_file/resolve/resolver_provider.rs

Somehow this change was not included in the previous PR. Included this again here.

fix: move to logging to seperate function and change to debug logging

---

crates/pixi_manifest/src/target.rs
tests/add_tests.rs

Fixes #1850
Reallows for:
```
pixi add black --pypi
pixi add black[cli] --pypi
```

fix: add package when extra is added

---

crates/pixi_default_versions/src/lib.rs
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-64.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-aarch64.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-ppc64le.snap

fix: downgrade __linux default to 4.18

---

pixi.lock
pixi.toml
scripts/activate_linux.sh

~~Doesn't work yet since the linker is overwritten [here](https://github.com/conda-forge/rust-feedstock/blob/3bddfa0e0ab5811ee904f20a08b7f31f824264dc/recipe/install-rust.sh#L32)~~
I now use an activation script to override that.

feat: use mold on linux

---

crates/pixi_manifest/src/manifest.rs

Improves the error message for when the target is missing.

feat: better error for when the target or platform are missing

---

scripts/release.py

It should fetch from upstream remote

fix: release script

---

src/lock_file/satisfiability.rs

Fixes: https://github.com/prefix-dev/pixi/issues/2036

fix: lock file is always outdated 

---

crates/pypi_modifiers/src/pypi_tags.rs

Split tag creation functions. So that it is a bit more readable.

fix: split tag creation functions

---

examples/cpp-sdl/src/main.cc

This ensures that mouse is working and shows how to use it.

feat: move the rectangle using a mouse in SDL

---

docs/features/system_requirements.md
docs/reference/project_configuration.md
mkdocs.yml

Add more documentation on system-requirements and include the `CONDA_OVERRIDE_*` functionality

docs: update system requirements information

---

pixi.toml

refactor: remove psutils

---

crates/pixi_build_types/src/procedures/conda_build.rs
src/build/mod.rs

Adds glob input files. To be used in source verification.

feat: glob input files

---

src/cli/global/sync.rs
src/global/install.rs

It now informs you if `pixi global sync` did nothing

feat: Give better info message for `pixi global sync`

---

src/cli/init.rs

fix: add newline to .gitignore

---

Cargo.lock
Cargo.toml
crates/pixi_record/src/source_record.rs
src/build/mod.rs
src/environment.rs

Gives back the globs and sha hash after a build.

feat: give back globs and build hash

---

docs/Community.md

docs: community: add array-api-extra

---

Cargo.lock
crates/pixi_glob/Cargo.toml
crates/pixi_glob/src/glob_hash.rs
crates/pixi_glob/src/glob_hash_cache.rs
crates/pixi_glob/src/glob_mtime.rs
crates/pixi_glob/src/glob_set.rs
crates/pixi_glob/src/lib.rs

This PR adds a struct that helps with the computation of the newest modification time for a file. This PR
also cleans some of the used functions and adds documentation for everything

feat: add mtime glob struct

---

src/cli/update.rs

Something to say for the `--help` info

docs: Add description for `pixi update --json`

---

src/global/project/mod.rs

Should resolve the issue described in https://github.com/prefix-dev/pixi/issues/342#issuecomment-2385120308

fix: global ensure manifest dir exists

---

crates/pixi_manifest/src/manifests/mod.rs
crates/pixi_manifest/src/manifests/project.rs
crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__project__tests__get_or_insert_toml_table.snap

Before it couldn't deal with inline tables.

fix: `get_or_insert_nested_table`

---

src/cli/run.rs

Simplified version of https://github.com/prefix-dev/pixi/pull/1649
Just to get a version in before we have a good design

fix: output task on pixi run without input

---

Cargo.lock
Cargo.toml

chore: update rattler crates

---

src/cli/run.rs

Fixes: #2197 
New result:
```
❯ pixi run -e env-that-does-not-exist
× unknown environment 'env-that-does-not-exist'
❯ pixi run -e lint
Available tasks:
lint
pre-commit-install
pre-commit-install-minimal
pre-commit-run
toml-format
toml-lint
❯ pixi run 
Available tasks:
build
build-docs
bump
bump-changelog
deploy-dev
deploy-latest
docs
generate-schema
install
....

fix: check environment name before returning not found print

---

src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/global/project/manifest.rs
tests/integration/test_global.py

It used to accept not giving any positional parameters

fix: update expose cli

---

pixi.lock

There was a bug in the version of taplo used on windows.

fix: taplo on windows

---

crates/pixi_spec/src/path.rs

Adds a useful method to resolve the path of a source spec.

chore: add resolve_path method

---

src/cli/clean.rs

Fixes #2237 
Not sure why this wasn't a compiler error....

fix: clean cache alias

---

docs/design_proposals/pixi_global_manifest.md
src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/cli/global/list.rs
src/cli/global/sync.rs
src/cli/global/uninstall.rs
src/cli/global/update.rs
src/global/project/manifest.rs
src/global/project/mod.rs
tests/integration/test_global.py

Don't ask whether to migrate, just migrate the manifest

fix: improve global migration

---

crates/pixi_build_frontend/src/build_frontend.rs
crates/pixi_build_frontend/src/lib.rs
crates/pixi_build_frontend/src/protocol_builder.rs
crates/pixi_build_frontend/src/protocols/conda_build/mod.rs
crates/pixi_build_frontend/src/protocols/pixi/mod.rs
crates/pixi_build_frontend/src/protocols/pixi/protocol.rs
crates/pixi_build_types/src/lib.rs
crates/pixi_build_types/src/procedures/conda_build.rs
crates/pixi_build_types/src/procedures/conda_metadata.rs
crates/pixi_build_types/src/procedures/initialize.rs
examples/cpp-sdl/pixi.lock
examples/cpp-sdl/pixi.toml
src/build/cache/build_cache.rs
src/build/cache/source_metadata_cache.rs
src/build/mod.rs
src/cli/build.rs
src/environment.rs
src/lock_file/update.rs

Adds virtual packages for the build and host platforms to ensure that the correct information is loaded that is also used at build and runtime.

feat: add virtual package to backend

---

src/cli/global/expose.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/uninstall.rs

Extend them and make them more consistent

docs: update `pixi global` docs

---

Cargo.lock
crates/pixi_build_frontend/src/lib.rs
crates/pixi_build_frontend/src/protocol.rs
crates/pixi_build_frontend/src/protocols/pixi/mod.rs
crates/pixi_build_frontend/src/protocols/pixi/protocol.rs
crates/pixi_build_frontend/src/reporters.rs
crates/pixi_build_types/src/procedures/conda_build.rs
src/build/mod.rs
src/cli/build.rs
src/environment.rs
src/lock_file/update.rs

This PR adds the first step of adding progress reporting for the pixi build progress. This creates some reporter traits
that can be used to report progress, but only implements noop reporters. Will implement actuall reporting of progress in subsequent PR.

feat: add progress reporter for build

---

src/cli/global/update.rs

Doesn't change reporting, but the code is now a bit more logical

fix: slightly improve global update

---

docs/advanced/updates_github_actions.md

Bump this action to the latest version

docs: bump peter-evans/create-pull-request action to v7

---

src/cli/build.rs

Add virtual package to the build process. 
This allows me to build the ros_workspace.

fix: add vpkgs to the build config

---

CITATION.cff

I've added Nichita and me to CITATION.cff

docs: add nichita and julian to CITATION.cff

---

src/cli/global/install.rs
src/cli/global/update.rs
src/global/common.rs
src/global/project/mod.rs

- Remove extra space at beginning of message
- Change variable names

fix: global update reporting

---

.pre-commit-config.yaml
mypy.ini
pixi.toml
scripts/release.py

- Strong typing in release.py
- Typecheck Python scripts

chore: improve Python scripts

---

src/cli/update.rs

I found the naming and docs a bit confusing and tried to improve that a bit

fix: `update` helper function

---

crates/pixi_manifest/src/manifests/manifest.rs

- more consistent with other methods
- also fits the doc comment

fix: `feature_mut` docs

---

.github/workflows/trampoline.yaml
src/global/trampoline.rs

Required as we build for it on conda-forge.

fix: add powerpc64le target to trampoline

---

docs/reference/cli.md

docs: fix upgrade --feature doc

---

docs/ide_integration/pycharm.md

This fixes https://github.com/prefix-dev/pixi/issues/2484

docs: Update pycharm.md to show optional installation

---

docs/tutorials/python.md

Follow up on https://github.com/prefix-dev/pixi/pull/2452
I'd missed that the structure was referenced later here

docs: update project structure in Python tutorial

---

.github/workflows/trampoline.yaml
src/global/trampoline.rs

@ruben-arts this is the more correct architecture for PPC64LE.

fix: correct ppc64le arch

---

crates/pixi_manifest/src/task.rs

```toml
[tasks]
hi = "echo hi"
hello = "echo hello"
welcome = { depends-on = ["hi", "hello"], description = "hi and hello" }
```
```
pixi task --manifest-path test_project/pixi.toml ls                      
Tasks that can run on this machine:
-----------------------------------
hello, hi, welcome
```
```
./target/pixi/release/pixi task --manifest-path test_project/pixi.toml ls
Tasks that can run on this machine:
-----------------------------------
hello, hi, welcome
- welcome         hi and hello
```

fix: update Task::Alias to return command description

---

src/install_pypi/plan/test/harness.rs
src/install_pypi/plan/test/mod.rs

Final attempt to fix the flaky CI (as I got it failing on OSX again), otherwise disable on linux.
* Splits up the test case
* Extra sanity check

fix: attempt to fix flaky pypi CI for linux

---

docs/reference/cli.md

Add options not listed on reference page

docs: update clean cache CLI doc

---

examples/rich_example/pixi.lock
src/lock_file/satisfiability.rs

Fix the example, and add a test to make sure it doesn't get pushed in a broken state.

fix: the satifiability of the rich example and test it

---

src/cli/global/sync.rs
tests/integration_python/pixi_global/test_global.py

fix: `pixi global sync` reports after each handled environment

---

docs/build/getting_started.md

Fix one typo and rearrange a bit

docs: pixi build follow up

---

Cargo.lock
Cargo.toml

This makes PrefixRecord loading run in parallel inside rattler.

feat: enable rayon when reading `PrefixRecord`'s

---

docs/Community.md

docs: add `marray` to community

---

src/main.rs

This results in exactly the same behaviour

refactor: simplify main a bit

---

Cargo.lock
Cargo.toml
crates/pixi_consts/Cargo.toml
crates/pixi_consts/src/consts.rs
crates/pixi_utils/Cargo.toml
crates/pixi_utils/src/executable_utils.rs
src/global/trampoline.rs

- move from lazy_static to once cell in the stdlib
- move away from oncecell crate where possible
- add comment to consts

fix: move away from lazy_static

---

src/cli/self_update.rs

`self-update` didnt work for arm64.

chore: self update for win arm64

---

pixi.toml
scripts/activate.bat
scripts/activate.sh

This PR simplifies some of the activiation we do for Rust and make it work for win-arm64 as well. I also added some comments to explain some of the environment variables set in the activation script.

chore: simplify rust activation

---

Cargo.lock
crates/pixi_glob/src/glob_mtime.rs
crates/pixi_progress/Cargo.toml
crates/pixi_progress/src/lib.rs
crates/pixi_pty/src/unix/pty_process.rs
crates/pixi_record/src/lib.rs
crates/pixi_uv_conversions/src/types.rs
src/project/mod.rs

Supersedes https://github.com/prefix-dev/pixi/pull/2778

fix: remove unused function and crates

---

crates/pixi_build_types/src/project_model.rs

This makes it a bit easier to access the inner build type :)

feat: expose build type v1 function

---

.github/workflows/ci.yml
docs/features/environment.md
docs/source_files/pixi_tomls/activation.toml

Fixes the CI and tests in CI if the source files in the documentation are changed

fix: documentation tests

---

crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_cpp.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_python.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_workspace.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@boltons.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@cpp-sdl.snap
crates/pixi_build_types/src/project_model.rs

Not all types in the pixi build protocol used camelCase. This PR fixes that.

fix: camelCase project protocol types

---

docs/reference/pixi_configuration.md
docs/switching_from/conda.md

docs: fix broken links to anchors

---

crates/pixi_build_type_conversions/src/project_model.rs
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_cpp.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_python.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_workspace.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_workspace_variants.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@boltons.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@cpp-sdl.snap
crates/pixi_build_types/src/project_model.rs

These will really be the last changes to the project model. (Famous last words).

fix: more build protocol fixes

---

docs/Community.md

docs: add `quantity-array` to community

---

docs/source_files/pixi_tomls/multi-environment-py-envs.toml
docs/source_files/pixi_tomls/multi-environment-simple.toml
docs/tutorials/multi_environment.md
mkdocs.yml

After @Hofer-Julian's remark I felt inspired to add this tutorial.

docs: add multi env tutorial

---

docs/source_files/pixi_projects/pixi_build_cpp/pixi.lock
docs/source_files/pixi_projects/pixi_build_workspace/pixi.lock

This should fix the CI failure on main

fix: update lock file on doc examples

---

docs/source_files/pixi_projects/pixi_build_cpp/pixi.lock
docs/source_files/pixi_projects/pixi_build_python/pixi.lock
docs/source_files/pixi_projects/pixi_build_workspace/pixi.lock
docs/source_files/pixi_projects/pixi_build_workspace_variants/pixi.lock

followup for this: https://github.com/prefix-dev/pixi/pull/2963

fix: update pixi lock files

---

src/cli/update.rs
src/cli/upgrade.rs
src/diff.rs
src/lib.rs

To revive #2340 in a separate tool, I need some functions public in diff.rs.
Needed for https://github.com/pavelzw/pixi-diff/pull/3

feat: Make diff module public

---

crates/pixi_manifest/src/manifests/manifest.rs
src/cli/project/platform/remove.rs
tests/integration_python/test_main_cli.py

It used to remove every platform

fix: `project platform remove`

---

docs/advanced/lockfile_diffs.md
mkdocs.yml

xref #2340, https://github.com/pavelzw/pixi-diff

docs: Add pixi-diff documentation

---

docs/tutorials/python.md

docs: fix python tutorial

---

src/cli/lock.rs
src/cli/mod.rs
tests/integration_python/test_main_cli.py

We already talked about this for a long time...

feat: add `pixi lock`

---

scripts/activate.sh
src/shell_snippets/pixi-bash.sh
src/shell_snippets/pixi-zsh.sh

fixes #3042
This shell rehashing is really hard to test. @wolfv if you have any better ideas to do this please don't hesitate to share them ;)

fix: don't change the ps1 on a rehash in a pixi shell

---

Cargo.lock
Cargo.toml
crates/pixi_utils/src/reqwest.rs
src/cli/mod.rs
src/cli/project/export/conda_environment.rs
tests/integration_python/test_main_cli.py

Related PR: https://github.com/conda/rattler/pull/1045
Draft until we switched to rattler release

fix: pixi authentication 

---

src/build/mod.rs

Fixes #2818
Still have to figure out if the change to `conda_get_metadata` makes sense

fix: changing cmake doesn't trigger rebuild

---

.github/workflows/ci.yml

This wastes useless dollars :)

ci: only build win-arm64 on main [skip ci]

---

crates/pixi_build_types/src/channel_configuration.rs
crates/pixi_build_types/src/procedures/conda_build.rs
crates/pixi_build_types/src/procedures/conda_metadata.rs

Needed for https://github.com/prefix-dev/pixi-build-backends/pull/78

refactor: add clone to params

---

docs/advanced/s3.md

https://github.com/prefix-dev/rattler-build/pull/1299 is now done

docs: Add s3 upload section

---

docs/source_files/pixi_projects/pixi_build_cpp/pixi.lock

chore: fix lockfile in docs

---

docs/advanced/production_deployment.md

https://github.com/Quantco/pixi-pack/pull/103

docs: Mention add_pip_as_python_dependency in compatibility mode for pixi-pack

---

docs/advanced/github_actions.md

xref https://github.com/prefix-dev/setup-pixi/pull/179

docs: mention run-install in setup-pixi documentation

---

.github/workflows/ci.yml

See also https://github.com/bnjbvr/cargo-machete/issues/158

ci: remove cargo-machete for now

---

docs/build/python.md

Kind of a nitpick; understand if you want to reject this

docs: update python.md

---

docs/stylesheets/extra.css

closes #3200 
copies the looks from `rattler-build`

docs: improve looks of a link

---

pixi.lock
pixi.toml
tests/integration_python/common.py
tests/scripts/run-all-examples.py
tests/wheel_tests/generate_summaries.py

Otherwise my IDE fights with our pre-commit setup (ruff version mismatch)

chore: upgrade lint dependencies

---

tests/integration_python/pixi_global/test_global.py

Let's move from `numpy` to `narwhals` and give the test a better name

test: attempt to fix flaky global test

---

tests/integration_python/__snapshots__/test_docs_examples.ambr

I missed that in https://github.com/prefix-dev/pixi/pull/3265

test: fix "extra-slow" snapshot

---

mkdocs.yml

GitHub suggestion went wrong here

docs: fix chapter name

---

CONTRIBUTING.md
README.md

follow-up to gh-3302 @Hofer-Julian

docs: more Pixi capitalistation

---

Cargo.lock
Cargo.toml
pixi_docs/Cargo.lock

chore: update rattler

---

Cargo.lock
Cargo.toml
crates/pixi_config/src/lib.rs
crates/pixi_consts/src/consts.rs
docs/reference/cli/pixi.md
docs/reference/cli/pixi/add.md
docs/reference/cli/pixi/remove.md
pixi_docs/Cargo.lock
src/cli/cli_config.rs
src/cli/config.rs
src/cli/mod.rs

feat: improve cli help headers and styling

---

docs/reference/cli/pixi/add.md
docs/reference/cli/pixi/exec.md
docs/reference/cli/pixi/global/add.md
docs/reference/cli/pixi/global/expose/add.md
docs/reference/cli/pixi/global/expose/remove.md
docs/reference/cli/pixi/global/install.md
docs/reference/cli/pixi/global/remove.md
docs/reference/cli/pixi/init.md
docs/reference/cli/pixi/remove.md
docs/reference/cli/pixi/task/add.md
docs/reference/cli/pixi/task/remove.md
docs/reference/cli/pixi/workspace/platform/remove.md
src/cli/cli_config.rs
src/cli/exec.rs
src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/upgrade.rs
src/cli/init.rs
src/cli/task.rs
src/cli/workspace/platform/remove.rs

- Singular everywhere
- Explain that they can be specified multiple times

docs: fix docs for CLI arguments that can be specified multiple times

---

docs/advanced/channel_logic.md
docs/advanced/explain_info_command.md
docs/advanced/shebang.md
docs/build/backends.md
docs/build/cpp.md
docs/build/dependency_types.md
docs/build/python.md
docs/build/variants.md
docs/build/workspace.md
docs/deployment/authentication.md
docs/deployment/container.md
docs/deployment/pixi_pack.md
docs/deployment/s3.md
docs/switching_from/conda.md
docs/tutorials/multi_environment.md
docs/tutorials/ros2.md

- Move more headings to title case
- Add newlines

docs: fix heading style

---

.github/workflows/ci.yml

See https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised

ci: use step-security `changed-files`

---

CHANGELOG.md

I adapted this link by accident

docs: fix broken link in changelog

---

docs/integration/editor/jupyterlab.md

docs: remove reference to archived mybinder.org example

---

src/lock_file/update.rs

Fixes #3159 
`main`:
```
Error:   × failed to solve the conda requirements of 'default' 'win-64'
╰─▶ Cannot solve the request because of: No candidates were found for talker2 *.
```
This PR:
```
Error:   x the package 'talker2' is not provided by the project located at 'talker2'
help: The build backend does provide other packages, did you mean 'talker'?
```

fix: error on package not provided by build backend

---

.pre-commit-config.yaml
install/install.sh
pixi.lock
pixi.toml
src/shell_snippets/pixi-bash.sh
src/shell_snippets/pixi-zsh.sh
tests/data/channels/recipes/post_link_script_package/post-link.sh
tests/scripts/test-export.sh

Use `shfmt` to format bash/posix shell scripts.
rule: `shfmt -w -i=4 -s -bn`

feat: format shell script with shfmt

---

renovate.json

Updating here will probably do more harm than good

ci: let renovate ignore paths we don't care to update

---

.github/workflows/ci.yml
.github/workflows/trampoline.yaml

Renovate is unhappy with `setup-alpine`.
Let's see if that helps.

ci: update github actions hash

---

cliff.toml
pixi.toml
tbump.toml

- update `git-cliff`
- fix deprecation warning
- fix broken formatting in release notes
- fix doc page reference

fix: update `git-cliff`

---

Cargo.toml

Shown here that it fixes the issues we had: https://github.com/prefix-dev/pixi/actions/runs/14594103556

fix: release build with custom runners

---

docs/global_tools/introduction.md

Otherwise i get
```
error: Unable to read input file: Is a directory
source: Error while reading file '/Users/pavel/.pixi/completions/fish'
```

docs: Fix fish completion command

---

docs/deployment/pixi_pack.md

https://github.com/Quantco/pixi-pack/pull/136

docs: Add s3 middleware and mirror middleware to pixi-pack

---

schema/model.py
schema/schema.json

We actually allow empty strings
See also https://discord.com/channels/1082332781146800168/1082338253925003385/1366760818930352248

fix: task arg schema

---

crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__invalid_task_list.snap
crates/pixi_manifest/src/manifests/workspace.rs
crates/pixi_manifest/src/toml/task.rs

fix: task arg parsing panic

---

docs/integration/editor/jetbrains.md

xref https://github.com/pavelzw/pixi-pycharm/pull/67

docs: Mention YouTrack tracking issues for pixi

---

docs/deployment/pixi_pack.md

Update pixi-pack docs to reflect PR at https://github.com/Quantco/pixi-pack/pull/156

docs: Support local pixi-pack executables for self-extracting

---

docs/integration/third_party/pixi_install_to_prefix.md
mkdocs.yml

docs: Mention pixi-install-to-prefix

---

crates/pixi_manifest/src/discovery.rs
crates/pixi_manifest/src/manifests/workspace.rs
crates/pixi_manifest/src/snapshots/pixi_manifest__discovery__test__explicit_workspace_discoverer@split_package_bad_package.snap
crates/pixi_manifest/src/snapshots/pixi_manifest__discovery__test__explicit_workspace_discoverer@split_package_good_package.snap
crates/pixi_manifest/src/toml/manifest.rs
tests/data/workspace-discovery/split_package/bad/package/pixi.toml
tests/data/workspace-discovery/split_package/bad/pixi.toml
tests/data/workspace-discovery/split_package/good/package/pixi.toml
tests/data/workspace-discovery/split_package/good/pixi.toml

Fixes #3766 
Also added test cases that verify this behavior.

fix: workspace version and name inheritance

---

docs/source_files/pixi_workspaces/pixi_build/workspace/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/workspace_variants/pixi.lock

If this PR is green, CI on main should be green as well after merging

fix: update lock files

---

docs/source_files/pixi_workspaces/pixi_build/getting_started/pixi.lock

This should make CI on main green again

ci: update doc example lock files

---

docs/deployment/pixi_pack.md

https://github.com/Quantco/pixi-pack/pull/169

docs: Update pixi-pack docs for allow `--inject`ing wheels

---

src/lock_file/resolve/pypi.rs
src/lock_file/update.rs

closes https://github.com/prefix-dev/pixi/issues/3854
thanks @ruben-arts for helpful directions on the issue! i still need to work more on the pixi codebase

fix: update help message for unsupported PyPI platform error to include adding Python dependency

---

docs/index.md
docs/javascripts/extra.js
docs/stylesheets/extra.css
mkdocs.yml

- Improved @matthewfeickert 's quote
- Made the quotes scrollable by grabbing them. (fun to see how we can add some more js to the documentation.)

docs: improve quotes

---

pixi.toml

With this command, all tests are run in one go.
@zelosleone

test: add `test-all-extra-slow`

---

.github/workflows/ci.yml
pixi.toml

Retrying makes sense on CI, but not so much when developing locally. There retrying is pretty annoying

ci: only retry on CI

---

docs/build/advanced_cpp.md
docs/build/cpp.md
docs/build/python.md

This should make the docs easier to find

docs: add links to backend docs

---

docs/deployment/pixi_pack.md

xref: https://github.com/Quantco/pixi-pack/pull/181

docs: Update pixi-pack documentation for parallel downloads

---

mkdocs.yml

It's already in deployment.
Let's also add it to extensions

docs: add pixi pack to our extensions

---

docs/index.md

While my initial change worked locally it doesn't on pixi.sh because of the different paths styles.

docs: fix links

---

pixi.lock
pixi.toml

my favourite library was added by accident

fix: remove boltons

---

docs/workspace/system_requirements.md

fixes: #3918 
I still find this hard to explain, but this is my best attempt.

docs: improve the `system-requirements` documentation

---

mkdocs.yml

docs: enable `content.code.select`

---

docs/source_files/pixi_workspaces/pixi_build/advanced_cpp/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/cpp/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/getting_started/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/python/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/workspace/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/workspace_variants/pixi.lock

test: update lockfile

---

examples/pixi-build/array-api-extra/pixi.lock
examples/pixi-build/array-api-extra/pixi.toml
examples/pixi-build/cpp-sdl/pixi.lock
examples/pixi-build/cpp-sdl/pixi.toml
examples/pixi-build/cpp-sdl/src/main.cc
examples/pixi-build/recursive-run-dependencies/pixi.lock
examples/pixi-build/recursive-run-dependencies/pixi.toml
src/lock_file/satisfiability/mod.rs
tests/scripts/run-all-examples.py

The lockfiles need to be updated as the hash function changed

fix: update locks of build lockfiles

---

tests/integration_python/pixi_global/test_shortcuts.py
tests/integration_python/test_edge_cases.py
tests/integration_python/test_main_cli.py
tests/integration_python/test_pypi_options.py
tests/integration_python/test_run_cli.py
tests/integration_python/test_shell.py
tests/integration_python/test_uv_sources.py

Hope to eliminate flacky test by using cache while installing numpy. 
And did some cleanup.

chore: remove tmp cache dir from test

---

crates/pixi_manifest/src/target.rs
examples/jupyterlab/LorenzDifferentialEquations.ipynb
typos.toml

In my opinion this trace added no value unless truly debugging the parsing code. But since it has been refactored this makes little sense.

chore: remove confusing info trace

---

.github/workflows/setup-dev-drive.ps1

rattler-build isn't happy with mixed path separators

fix: dev drive script

---

.github/workflows/ci.yml

fix: cargo-machete action 0.9.1

---

crates/pixi_core/src/lock_file/update.rs

Easy PR. Refactors the skip method, I felt it could be simplified a bit :)

feat: refactor skip method

---

crates/pixi_reporters/src/download_verify_reporter.rs
crates/pixi_reporters/src/sync_reporter.rs

- **add more debug to panic of validation state in downloading**
- **add full entry to panic**

fix: split progress bar ids

---

docs/global_tools/introduction.md

We didn't document this awesome new feature before

docs: extend global tutorial with source deps

---

crates/pixi_core/src/lock_file/update.rs
crates/pixi_core/src/workspace/grouped_environment.rs

Fixes https://github.com/prefix-dev/pixi-build-backends/issues/315

fix: diagnostic source of solve error was not propagated

---

Cargo.lock
Cargo.toml

This updates to the latest rattler version :)

feat: update to latest rattler

---

docs/build/getting_started.md

Not sure if this actually works, best guess ;)

docs: Fix build getting started doc

---

tests/integration_python/test_main_cli.py

https://github.com/prefix-dev/pixi/actions/runs/17260170689/job/48980191313

chore: try fixing extra-slow tests

---

Cargo.lock
Cargo.toml
crates/pixi_build_types/Cargo.toml
crates/pixi_build_types/src/lib.rs
crates/pixi_build_types/src/project_model.rs
crates/pixi_stable_hash/Cargo.toml
crates/pixi_stable_hash/src/lib.rs

Moves the stable hash implementation into its own crate.

refactor: extract stable hash

---

crates/pixi_cli/src/self_update.rs

Show current and target versions when passing `--dry-run` to `self-update`.
Closes #4512

feat(self-update): include version information in `self-update --dry-run`

---

README.md

https://github.com/scipy/scipy/issues/21489#issuecomment-3279545579

docs(README): add hyperlinks for `cargo` and `npm`

---

crates/pixi/tests/integration_rust/add_tests.rs
crates/pixi/tests/integration_rust/common/mod.rs

fix: `add_tests::add_with_channel`

---

docs/integration/ci/github_actions.md

https://github.com/prefix-dev/setup-pixi/pull/221 by @olivier-lacroix

docs: Add global environments in setup-pixi

---

crates/pixi_utils/src/conda_environment_file.rs
crates/pixi_utils/src/snapshots/pixi_utils__conda_environment_file__tests__test_import_from_env_yaml.cockpit.yml.snap
tests/integration_python/test_import.py

fix(import): handle `url::pkg` dependencies from conda env file

---

docs/reference/pixi_manifest.md

@andyfaff please could you review :) ?

docs(manifest): more simple introduction to manifest reference
