prefix-dev/pixi

.github/workflows/rust.yml
docs/README.md
scripts/install.ps1
scripts/install.sh

add binary install commandos

---

src/project.rs

Currently returning just a `&str`. We could decide to return a parsed version instead.

Name & Version accessors

---

src/cli/mod.rs

Detect the current shell from the environment if not specified on the command line.
Fix #90

fix: detect shell for autocompletion

---

scripts/install.sh

Hi!
currently, the `install.sh` script only modifies the `.bash_profile`. Since `zsh` is the default shell on macOS and many use `fish`, I've also added these two conditionally to the installation script.
Note that for `fish` it would also be viable to just run `fish_add_path ${INSTALL_DIR}` once instead of having it added to the config. However, I think that makes things more complicated and the fish docs suggest that adding this line to the config is not wrong.

add: modify fish and zsh configuration as well

---

Cargo.toml
docs/README.md
src/cli/mod.rs

Adds `--version`, usage, about, and stuff to `Cargo.toml`.
```
A package management and workflow tool
Usage: pixi.exe [COMMAND]
Commands:
completion  Generates a completion script for a shell
init        Creates a new project
add         Adds a dependency to the project
run         Runs command in project
install     Installs the defined package in a global accessible location
help        Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
Fixes #92

feat: add version and color

---

docs/README.md

We installing using `cargo install` it is important to use the lock file from the repository. By default, this is not the case but by adding `--locked` it is. 
Fix #96

fix: add --locked to install instructions

---

Cargo.lock
Cargo.toml
src/cli/auth.rs
src/cli/mod.rs

So far this is just a simple subcommand to store login information

add authentication subcommand

---

docs/README.md
src/cli/add.rs
src/cli/install.rs
src/cli/mod.rs
src/cli/run.rs

This PR does two things
- Refactors `pixi` to give the help command and `pixi install` will prepare the environment + lockfile
- Adds the `--manifest-path` option to `run`, `add` and `install`.

refactor to install command and add manifest path

---

src/cli/shell.rs

Add the `--manifest-path` option to the shell command

feat: add manifest-path to shell command

---

.github/workflows/rust.yml
Cargo.toml

The Wix installer requires that the binary is placed in the `release` folder but when running in release its placed in the `release-lto` folder. This is because for releases we use a different profile. I changed the code around so that instead of using another profile the flags for `lto` and `strip` are injected with environment variables.

fix: lto with flags

---

CHANGELOG.md
Cargo.lock
Cargo.toml
pixi.toml

Because there was an issue with the windows installer build we quickly release a bugfix

prepare v0.0.5

---

src/cli/init.rs

fix: canonicalize path before parsing it as path.

---

Cargo.toml
src/cli/run.rs
tests/common/mod.rs
tests/install_tests.rs

Can now run commands sequentially, currently run activation scripts for each command which will be fixed at a later point. Will work on adding a command line interface for command management in a different PR. This will make it easier to add tests which I will also do there :)
The SDL2 example should work now 👍

feat: now runs commands sequentially

---

src/cli/run.rs
src/cli/shell.rs

Don't manually prepend the path anymore

fix: path behavior for run

---

docs/README.md

- Run init steps separately (`&&` doesn't work for every shell)
- Show how to exit the pixi shell again

Extend readme

---

Cargo.lock
Cargo.toml
examples/cpp-sdl/pixi.toml
src/cli/run.rs
tests/common/mod.rs
tests/install_tests.rs

This is the initial work to use the deno task shell in our code instead of our own concoction. 
Im running into an issue though where Im unable to capture the output from deno tasks. I [opened an issue on the `deno_task_shell` crate](https://github.com/denoland/deno_task_shell/issues/86) to that end.
Fix #162
Fix #165

feat: use deno task shell to execute commands

---

Cargo.lock
Cargo.toml
src/cli/add.rs
src/cli/global/install.rs
src/environment.rs
src/repodata.rs

Bumps rattler to [0.6.0](https://github.com/mamba-org/rattler/releases/tag/v0.6.0)

bump: rattler 0.6.0

---

docs/cli.md
docs/getting_started.md

Update `[commands]` references in documentation to `[tasks]`

docs: change commands to tasks

---

src/cli/init.rs

Closes #214 
https://docs.rs/minijinja/latest/minijinja/syntax/index.html#trailing-newlines
> MiniJinja, like Jinja2, will remove one trailing newline from the end of the file automatically on parsing. This lets templates produce a consistent output no matter if the editor adds a trailing newline or not. If one wants a trailing newline an extra newline can be added or the code rendering it adds it manually.

Add trailing newline to pixi.toml and .gitignore

---

.gitignore
Cargo.lock
Cargo.toml
src/cli/auth.rs
src/cli/info.rs
src/project/mod.rs

Add additonal information in info command
global: 
- cache dir size
- auth store location 
project: 
- dependency count
- cache size 
- lock file last updated
- target platforms
also reformats the output of tasks and adds help string in info command

Add additional information in info, closes #193 

---

.github/workflows/rust.yml

Aligns the CI with the latest in rattler. See https://github.com/mamba-org/rattler/pull/274
#233 disabled the cache because of a build issue with aarch64. This PR reenables that again.

fix: align CI with rattler

---

Cargo.lock
Cargo.toml
src/cli/mod.rs

Allow control over whether colors are used in the output.
`--color auto`: default behavior. Will use colors if on a terminal and the env variable `NO_COLOR` is not set.
`--color never`: never use colors.
`--color always`: force using colors regardless of the environment.

feat: allow forcing or disabling colors

---

Cargo.lock
Cargo.toml
src/cli/mod.rs
src/cli/search.rs

Add `search` subcommand 
```
➜ pixi search python -c bioconda -c conda-forge
Package                                  Version             Channel            
python                                   3.11.4              conda-forge        
ipython                                  8.14.0              conda-forge        
spython                                  0.3.0               conda-forge        
bpython                                  0.24                conda-forge        
qpython                                  2.0.0               conda-forge        
vpython                                  7.6.4               conda-forge        
lpython                                  0.19.0              conda-forge        
pythonpy                                 0.4.11              bioconda …
```

feat/add search command (fix #230)

---

.github/workflows/rust.yml

An attempt to reduce the binary size as well as adding a gnu build.

reduce binary size

---

docs/getting_started.mdx

The word `run` was missing in the task section

Missing word in getting_started.mdx

---

.gitattributes
src/cli/init.rs

Just stumbled on this project and figured I'd add this small nice-to-have.
This applies syntax highlighting in the GitHub web interface, and treats it as a generated file.
In the future, you might want to contribute to [github-linguist](https://github.com/github-linguist/linguist) so that GitHub has proper support for this filename, but, for now, a [quick search](https://github.com/search?q=path%3Apixi.lock&type=code) shows that this file probably won't meet the popularity requirement.

Set linguist attributes for `pixi.lock`

---

Cargo.lock
Cargo.toml

This PR enables the use of the OS certificate store which should make it possible to use pixi behind a corporate firewall.
This might also be a solution for https://github.com/prefix-dev/pixi/issues/291 , if the used certificate is stored in the OS certificate store.
@pavelzw I know you ran into this at some point, would you be able to test this?

feat: enable use of os certificate store

---

src/cli/global/install.rs
src/cli/global/list.rs
src/cli/global/mod.rs
src/cli/global/remove.rs

This fixes #314 and #50 by adding two new global commands `global list` and `global remove` for inspecting and removing the globally installed packages.
In order to avoid having to try to map back the installed binaries to their source packages via parsing the shell scripts or something, the general approach I took here was to add a dry run option to the function that generates the binary scripts, such that we can re-run the script generation on list or remove to see what files would be generated for a given package and thus belong to that package. (This strategy has at least two small flaws: it's not very backwards compatible if pixi decides to change the names of the generated files at some point, and it's not robust to two different packages installing a binary with the same name. The …

Add `pixi global list` and `pixi global remove` commands

---

Cargo.lock
Cargo.toml
src/cli/run.rs
src/cli/task.rs
src/task/mod.rs
tests/task_tests.rs

An attempt to at least improve the situation in https://github.com/prefix-dev/pixi/issues/311 . This PR simplifies the quoting we use when creating and executing tasks to only really quote arguments that contain white spaces.

fix: simplify quoting logic

---

src/repodata.rs

Only noarch should be required, the other subdirs might be missing.

fix: noarch is the only channel that must exist

---

src/virtual_packages.rs

Add tip to the error of a to low local system requirement.
closes #346

misc: add tip to resolve virtual package issue

---

docs/cli.mdx
src/cli/mod.rs
src/cli/project/channel/add.rs
src/cli/project/channel/mod.rs
src/cli/project/mod.rs
tests/common/builders.rs
tests/common/mod.rs
tests/project_tests.rs

Added the #254 but with the `project` prefix. So the main cli entry point stays as clean as possible. This is beneficial for future expansion.

feat: add channel add feature on project subcommand.

---

docs/basic_usage.mdx
docs/cli.mdx
docs/configuration.mdx
docs/examples/cpp-sdl.mdx
docs/overview.mdx
docs/vision.mdx

depends on https://github.com/prefix-dev/cms/pull/10

docs: copy from cms

---

Cargo.lock
Cargo.toml
src/cli/add.rs
src/cli/global/install.rs
src/environment.rs
src/repodata.rs

Bumps rattler to use the latest `main` branch and bumps pixi to `0.5.0-dev` to indicate that the latest version is a not the latest released one.

bump: 0.5.0-dev and rattler

---

docs/cli.mdx
src/cli/add.rs
src/cli/install.rs
src/cli/run.rs
src/cli/shell.rs
src/environment.rs
tests/common/builders.rs
tests/common/mod.rs
tests/install_tests.rs
tests/task_tests.rs

Closes #349 
Add the `--frozen` and `--locked` like how cargo does it. 
Allow users to force CI to not touch the lock file.

feat: add --locked and --frozen to getting an up-to-date prefix

---

docs/cli.mdx

Otherwise this would get piped into a file called `=1.8` 😅

docs: use quotes in cli

---

docs/cli.mdx
src/environment.rs

closes #371 
Error when there is no lockfile and the `--frozen` option is used.

fix: update the --frozen logic to error when there is no lockfile

---

docs/cli.mdx
src/cli/run.rs
src/cli/task.rs
src/project/mod.rs
src/task/mod.rs
tests/common/builders.rs
tests/common/mod.rs
tests/task_tests.rs

This feature also fixes the fact that `pixi run` always runs in the root of the project.
Now only the pixi tasks are run in the root of the project (unless specified differently), while the `pixi run` will run in the `env::current_dir()` .
closes #376

feat: Add the current working directory in tasks

---

docs/configuration.mdx
src/project/environment.rs
src/project/manifest.rs
src/project/mod.rs
src/project/snapshots/pixi__project__manifest__test__activation_scripts.snap
src/project/snapshots/pixi__project__manifest__test__dependency_types.snap
src/project/snapshots/pixi__project__manifest__test__target_specific.snap
src/project/snapshots/pixi__project__manifest__test__target_specific_tasks.snap
tests/init_tests.rs

closes #399 
Version is only needed when building so making it an optional. Keeping it in the templates as of right now.

misc: make version an optional field in the config.

---

install/install.sh

Fixes #403
This updates `install.sh` to create the required dot file instead of silently skipping the addition of `PATH`.

Fix install.sh to create dot file if not present

---

Cargo.lock
src/cli/add.rs
src/cli/global/install.rs
src/environment.rs

This does break modern installations of pixi projects that include both conda-forge and the pytorch channel. 
I think we should make this configurable to avoid not having to option to solve already working environments.

misc: set strict_channel_priority to true

---

.github/workflows/rust.yml

Fixes #413.
The `Check for release` step was run after it was used to determine whether or not to strip. Now stripping is just always enabled, just like `lto`.

Fix linux binaries are not stripped

---

README.md

This pull request aims to enhance the README.md file by making it more organized, reader-friendly, and grammatically correct. The improvements include the addition of a table of contents for easier navigation and various changes to refine the content.
Here's a summary of the changes made:
- Added a table of contents to provide easy access to different sections.
- Improved grammar and language for better clarity and readability.
These changes should contribute to a more informative and polished README, improving the overall user experience for visitors to the repository. Your feedback and suggestions are highly appreciated.

Enhance README.md: Added Table of Contents, Grammar Improvements

---

install/windows/main.wxs

I've had problems related to his path entry.
Changing it to backslashes resolved them.
I am not 100% sure that the forward slashes were the reason.
However,  using backslashes on Windows is probably a good idea in general.

Let `PIXI_BIN_PATH` use backslashes

---

.gitignore
docs/Community.md
docs/FAQ.md
docs/advanced/authentication.md
docs/assets/logo_light_no_text.svg
docs/configuration.md
mkdocs.yml
pixi.lock
pixi.toml

Add social cards like this. We need to pay to be able to customize these cards.

docs: Add social cards to the pages

---

install/install.sh

Mitigation for https://github.com/prefix-dev/pixi/issues/446

install.sh: Print more informative error if created file is empty

---

install/install.ps1

Smaller solution than #448 
Decided to keep it simple to also make the documentation simpler. Now it is just the home folder for everything.

fix: Use home dir on windows

---

examples/ctypes-factorial/.gitignore
examples/ctypes-factorial/README.md
examples/ctypes-factorial/pixi.lock
examples/ctypes-factorial/pixi.toml
examples/ctypes-factorial/src/factorial.c
examples/ctypes-factorial/src/factorial.h
examples/ctypes-factorial/src/factorial.py

https://github.com/prefix-dev/pixi/discussions/436

new example: ctypes

---

README.md

docs: mention the AUR package

---

pixi.lock
src/install.rs
src/progress.rs

Add nice progress messages to the conda installation phase as well.

feat: add progress info to conda install

---

Cargo.lock
src/lock_file/python.rs

Bump RIP to fix the sdist issues we had. Only wheels are allowed for pixi atm.

bump: rip to fix sdist issues

---

Cargo.lock
Cargo.toml
tests/install_tests.rs

This ensures that tests that install things are run in serial. Hopefully that fixes the flaky CI. In the future we should properly fix this though...

test: run serially

---

src/lock_file/mod.rs
src/lock_file/python.rs
src/project/manifest.rs
src/project/mod.rs
src/project/python.rs
src/project/snapshots/pixi__project__manifest__test__activation_scripts.snap
src/project/snapshots/pixi__project__manifest__test__dependency_types.snap
src/project/snapshots/pixi__project__manifest__test__mapped_dependencies.snap
src/project/snapshots/pixi__project__manifest__test__python_dependencies.snap
src/project/snapshots/pixi__project__manifest__test__target_specific.snap
src/project/snapshots/pixi__project__manifest__test__target_specific_tasks.snap

Going from:
```
× failed to parse pixi.toml from /home/rarts/development/pixi/examples/pypi
╰─▶ failed to parse project manifest
╭─[pixi.toml:14:1]
14 │     
15 │ ╭─▶ [pypi-dependencies]
16 │ │   pyboy = "==1.6.6"
17 │ │   tensorflow = "==2.14.0"
18 │ │   flask = ""
19 │ ├─▶ black = "~=23.10"
· ╰──── invalid PEP440
╰────
```
To:
```
× failed to parse pixi.toml from /home/rarts/development/pixi/examples/pypi
╰─▶ failed to parse project manifest
╭─[pixi.toml:17:1]
17 │ tensorflow = "==2.14.0"
18 │ flask = ""
·         ─┬
·          ╰── invalid PEP440: https://peps.python.org/pep-0440/
19 │ black = "~=23.10"
╰────
```

Fix pypi dependencies parsing errors

---

docs/configuration.md

docs: add pypi-dependencies to the configuration docs

---

src/cli/run.rs
tests/common/mod.rs

I think this is enough info, can be less can be more, what do you think?

ux: show which command is run to the user

---

Cargo.lock
Cargo.toml
examples/flask-hello-world/pixi.lock
examples/pypi/pixi.lock
examples/pypi/pixi.toml
src/cli/run.rs
src/environment.rs
src/lock_file/mod.rs
src/lock_file/package_identifier.rs
src/lock_file/python.rs
src/lock_file/python_name_mapping.rs
src/lock_file/satisfiability.rs
tests/common/package_database.rs

This PR adds support for checking the satisfiability of the lock-file which includes pypi-dependencies.
Purls have been added to the lock-file (https://github.com/mamba-org/rattler/pull/414) (See also: https://github.com/conda-incubator/ceps/pull/63). This enables checking which conda packages will install which pypi packages without needing to check the internet. This ensures we can still check if a lock-file is up to date quickly.
I did not profile this code but I think there are a lot of places we can improve the performance. Thats for a later PR.
I also didn't add tests. I think we should but we can also do that in another PR.
Closes #467

feat: implement lock-file satisfiability with pypi dependencies

---

src/environment.rs

Fix #507 
Pixi simply removed all redundant python packages. Only packages without an INSTALLER where left alone. I changed this behavior to only remove python packages installed by pixi itself.

fix: issue 507

---

Cargo.lock
src/environment.rs

Remove empty folders when uninstalling a pypi dependency.

feat: remove empty folders on python uninstall

---

docs/index.md
install/install.ps1

Tested on both windows and linux

docs: add update manual

---

src/lock_file/python.rs
src/project/manifest.rs

fix: issue 529

---

.github/workflows/release.yml
README.md
docs/index.md

This should start automatically making prs on the winget-pkg repo when we make a new release. 
Added the WINGET_TOKEN to pixi using the `public-repo` access from my personal account:
Closes #323 as we then have automated the release.

feat: add winget releaser

---

docs/cli.md
docs/configuration.md

docs: update pypi part

---

Cargo.lock
Cargo.toml
src/cli/run.rs
src/cli/task.rs
src/project/mod.rs
src/task/executable_task.rs
src/task/mod.rs
src/task/traverse.rs
tests/common/mod.rs

Refactor run code a bit. Includes changes of #550.
I also refactored the traversal code to use a single `traverse` method that is reused all over the place. This includes a `should_visit` function that we can later use to skip executing certain tasks if certain conditions hold.

refactor: task run code

---

src/cli/add.rs

`pixi add --pypi bla`  would save `bla = "*"` to file but we obviously don't want to add failing dependencies.

fix: save file after lockfile is correctly updated

---

src/lock_file/mod.rs
src/project/mod.rs

This PR works around the file locking deadlock issue that we encountered by limiting the number of concurrent solves when also solving pypi dependencies.

fix: limit the number of concurrent solves

---

docs/configuration.md

No you can search for cuda in our documentation and his will be the first hit. 
Closes #590

Document adding CUDA to `system-requirements`

---

Cargo.toml
src/cli/search.rs

Improve search with more info about specific package and possibility to add a wildcard in the search
https://github.com/prefix-dev/pixi/issues/378
Rattler:
https://github.com/mamba-org/rattler/pull/446
Specific package
Using wildcard

Improve search

---

src/cli/add.rs

Previously, the `add` command was using the default set of virtual packages from [get_minimal_virtual_packages](https://github.com/prefix-dev/pixi/blob/5a16570ae4af85b4de5b5fb858050e4c1e59b132/src/virtual_packages.rs#L28C8-L28C36) for solving, rather than using the actual virtual packages for the current project; see #607 for more detail.
(Hopefully this will resolve the `__cuda` issue in #607, though I haven't yet tested that on my target machine.)

fix: use project virtual packages in add command

---

.github/dependabot.yml

https://github.com/prefix-dev/pixi/pull/611#issuecomment-1875564017
dependabot should automatically add its own labels anyway, see https://github.com/prefix-dev/setup-pixi/pull/62 and https://github.com/prefix-dev/setup-pixi/pull/30

Remove custom dependabot labels

---

docs/design_proposals/multi_environment_proposal.md

There was still a "real world" example missing from the multiple machine use case.
Also, wouldn't this use case make the [target table](http://pixi.sh/configuration/#the-target-table) irrelevant?
The 
```toml
[dependencies]
cmake = "3.26.4"
python = "3.10"
[target.osx-64.dependencies]
python = "3.11"
```
example also kind of goes against the philosophy of _adding_ additional requirements to the requirements set (and not replacing them).
IMO the example above should be not solvable since `python=3.10, python=3.11` together produce invalid requirements.

Add multiple machines from one project example

---

src/cli/remove.rs
src/consts.rs
src/project/manifest.rs
src/project/mod.rs
src/project/python.rs
src/project/snapshots/pixi__project__manifest__test__remove_target_pypi_dependency.snap

Remove dependencies on pypi-dependencies section in pixi.toml
It fixes #591

Add `--pypi` option to `pixi remove`

---

docs/advanced/channel_priority.md
mkdocs.yml

We got a lot of questions about the channel logic including the priority and channel specific logic. This document tries to explain this better.

Document the channel logic

---

src/cli/add.rs
src/cli/global/install.rs
src/cli/info.rs
src/cli/project/channel/list.rs
src/cli/search.rs
src/cli/task.rs
src/consts.rs
src/lock_file/mod.rs
src/lock_file/satisfiability.rs
src/project/environment.rs
src/project/errors.rs
src/project/manifest/environment.rs
src/project/manifest/mod.rs
src/project/manifest/target.rs
src/project/manifest/validation.rs
src/project/mod.rs
src/repodata.rs
src/task/executable_task.rs
tests/init_tests.rs

This PR refactors the code to extract project information from `Environment`s instead of directly from the project. 
This initial PR tries to retain the same surface level API as before where the accessors on the `Project` struct remains intact. 
A next PR will remove this functions and force users to go through `Environment`s instead of `Project`.
This PR currently refactos the `platforms`, `channels` and `tasks` functions. I will create a follow-up PRs to also refactor the `system-requirements`, `activation` and `dependency` functions.

refactor: move code from `Project` to `Environment`

---

docs/cli.md
src/cli/global/install.rs
src/cli/global/list.rs
src/cli/global/mod.rs
src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs

Fixes: #613 
Introduce a new 'upgrade' and `upgrade-all` subcommand to 'pixi'.
Users can specify the target package with the 'package' option and choose upgrade channels using the 'channel' option.
```sh
pixi global upgrade <package> --channel <channel>
```
```sh
pixi global upgrade-all  --channel <channel>
```

feat: add upgrade command to pixi

---

docs/configuration.md

Removes the mention of the `unix` and `windows` system requirements as they were removed in #632

docs: remove windows and unix system requirements

---

src/cli/add.rs
src/cli/info.rs
src/lock_file/mod.rs
src/lock_file/satisfiability.rs
src/project/dependencies.rs
src/project/environment.rs
src/project/manifest/environment.rs
src/project/manifest/mod.rs
src/project/manifest/snapshots/pixi__project__manifest__target__tests__targets.snap
src/project/manifest/target.rs
src/project/mod.rs
src/project/snapshots/pixi__project__environment__test__dependencies.snap
src/project/snapshots/pixi__project__tests__dependency_target_sets.snap
tests/add_tests.rs

This PR extracts the dependencies code to `Environment`. This is a little bit more involved than previous PRs because there can be multiple features that define requirements on the same package. Instead of overwriting each other we take into account all requirements of the different features.

refactor: extract dependencies to `Environment`

---

README.md

`pixi` can be installed with `pacman` now!

docs: update the instructions for installing on Arch Linux

---

Cargo.lock
Cargo.toml
src/lock_file/pypi.rs
src/lock_file/satisfiability.rs
src/project/environment.rs
src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/target.rs
src/project/mod.rs

Refactors the code to get the `pypi-dependencies` from `Environment` instead of directly from the manifest.

refactor: extract pypi-dependencies from environment

---

src/install.rs

If you are using `pixi` `v0.11.1` you got a feature activated called `reflinking`. This however doesn't work correctly yet.
The issue you might get is:
```
Permission denied (os error 13)
```
This (as far as we know) only happens on `btrfs`  filesystems, like my Fedora setup. 
You can check if your on `btrfs` using the following command:
```
> lsblk -f
...
nvme0n1                                                                                            
├─nvme0n1p1 vfat   FAT32                       4C  581,4M     3% /boot/efi
├─nvme0n1p2 ext4   1.0                         3a  611,7M    30% /boot
└─nvme0n1p3 btrfs        fedora_localhost-live 87   69,6G    91% /home
```

fix: Don't allow the use of reflinks

---

src/environment.rs

fixes #650
reproducible case (on Linux):
```yaml
platforms = [
"osx-arm64",
]
name = "bug"
[dependencies]
python = "=3.11.*"
```
Run:
```
$ pixi add --no-install ruff
WARN pixi::environment: Adding dependency for unsupported platform (linux-64).
✔ Added ruff
```
`ruff = ">=0.1.13,<0.2"` added to `pixi.toml` 🎉

fix: support adding dependencies for project's unsupported platforms

---

src/cli/mod.rs
src/cli/shell_hook.rs

closes #410
This is a hidden command - let me know where should we document this!

feat: add shell-hook command

---

Cargo.lock
Cargo.toml
src/project/manifest/environment.rs

Added the `from_str` in preperation for the CLI and now it is really strict with some good error msgs.

feat: make environment name parsing strict

---

src/task/mod.rs

Running a task that have [ or ] as part of command gives an error about `glob: no matches found '....'` 
To reproduce run `pixi run python test.py arg=[12,12]` which gives `glob: no matches found '/home/juruc/workspaces/pixi_ws/pixi/arg=[12,12]'`
This PR quote the part of the command that have [ or ]

Fix running a deno task: Quote part of the command that have brackets [ or ]

---

src/cli/add.rs
src/consts.rs
src/environment.rs
src/project/environment.rs
src/project/mod.rs

Now the environments would be put in:
```
pixi/.pixi
└── envs
└── default
├── bin
├── ...
└── prefix  <--- prefix file
```

feat: use named environments (only "default" for now)

---

src/cli/global/install.rs
src/cli/info.rs
src/config.rs
src/environment.rs
src/project/mod.rs
src/repodata.rs

Closes #681 
This adds the ability to set the cache dir using an environment variable:
```
export PIXI_CACHE_DIR=/path/to/cache
export RATTLER_CACHE_DIR=/path/to/cache
```
I added the `RATTLER_CACHE_DIR` so that we could use that in all our libraries so that it gets shared (like it does before this change)
I added the `PIXI_CACHE_DIR` to not confuse users that don't have any knowledge that rattler is our backend.

feat: Allow user to set the cache directory

---

install/install.ps1
install/install.sh

Close #686 
The PR mainly adds the option of using a `PIXI_NO_PATH_UPDATE` environment variable to suppress PATH update, when installing pixi from install script.
Besides the option added, since the PR is about environment variable, the way of updating PATH in the PowerShell install script has also been modified from using `[Environment]::SetEnvironmentVariable` to set environment variable to get and update environment variable from Windows registry.
This change doesn't affect pixi installation directly and is primarily to address a potential issue that `SetEnvironmentVariable` expands all environment variables and this behavior may not be welcomed in some cases.
```pwsh
$Env:PATH
#> %USERPROFILE%\bin;
#> C:\Users\userA\bin;C:\pixi\bin
#> %USERPROFILE%\bin;C:\pixi\bin
```
Related code are …

feat(install): Add `PIXI_NO_PATH_UPDATE` for PATH update suppression

---

src/cli/global/install.rs
src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs
src/cli/search.rs
src/cli/upload.rs
src/environment.rs
src/lib.rs
src/project/manifest/mod.rs
src/project/mod.rs
src/repodata.rs
tests/install_tests.rs

Because `Client` and `AuthenticatedClient` were re-used in the binary, when using a different runtime these were also shared. Because multiple tests have different runtimes, we ran into this issue:
https://users.rust-lang.org/t/runtime-dropped-the-dispatch-task/91915
This should hopefully fix this.

Feat: non-global reqwest client

---

Cargo.lock
Cargo.toml
src/cli/list.rs
src/cli/mod.rs
src/environment.rs
src/install_pypi.rs
src/lock_file/mod.rs
src/lock_file/package_identifier.rs
src/lock_file/pypi.rs
src/lock_file/satisfiability.rs
src/project/dependencies.rs
src/project/environment.rs
src/project/manifest/feature.rs
src/pypi_tags.rs
src/repodata.rs
tests/add_tests.rs
tests/common/mod.rs
tests/install_tests.rs

Refactors pixi to make use of the changes made in https://github.com/mamba-org/rattler/pull/484 .
This completely refactors how lock-files are checked and how they are rebuilt. 
@ruben-arts Please carefully test that lock-files are still properly verified and updated.
Note that this does **not** add multi-env support yet. This work is just done to integrate with multi-env capable lock-files.

refactor: update to rattler lock v4

---

src/cli/project/channel/add.rs
src/project/manifest/mod.rs
src/project/manifest/snapshots/pixi__project__manifest__tests__add_channels.snap
tests/common/mod.rs

Adds more testing as well as this cli command:
```
pixi project add -f/--feature cuda nvidia
```

feat: add features to channel add command

---

Cargo.lock
src/cli/add.rs
src/cli/global/install.rs
src/cli/run.rs
src/cli/search.rs
src/cli/shell.rs
src/environment.rs
src/lock_file/mod.rs
src/lock_file/satisfiability.rs
src/project/environment.rs
src/repodata.rs

This is the first implementation of multi-env which will update the lock-file for all environments.
There are some notable improvements that can be made in terms of usability from code. I will do that in another PR this PR should initially be enough to start testing multi-env!
closes https://github.com/prefix-dev/pixi/issues/585

feat: update all environments in the lock-file when requesting an environment

---

src/cli/search.rs

Close #712 
*before*
```
❯ pixi search jupyterlab
jupyterlab py37_0
-----------------
Name                jupyterlab
Version             1.0.10
Build               py37_0
Size                13936631
License             BSD-3-Clause
Subdir              win-64
File Name           jupyterlab-1.0.10-py37_0.tar.bz2
URL                 https://conda.anaconda.org/conda-forge/win-64/jupyterlab-1.0.10-py37_0.tar.bz2
MD5                 bd9a55e6d10092c8230fdcc00efdaceb
SHA256              f674dd303a889e7adeabdb609bde2801f8078020513438c585a941f7a7efe75f
Dependencies:
- jinja2 >=2.10
- jupyterlab_server >=1.0.0,<2.0.0
- notebook >=4.3.1
- python >=3.7,<3.8.0a0
- tornado !=6.0.0,!=6.0.1,!=6.0.2
❯ pixi search jupyterlab*
Package                                  Version             Channel
jupyterlab …
```

fix(cli): make `pixi search` result correct

---

docs/cli.md
src/cli/mod.rs
src/cli/shell.rs
src/cli/shell_hook.rs

Now you can do:
```
pixi shell-hook -e prod
pixi shell-hook --manifest-path ~/project/pixi.toml
pixi shell-hook --locked
pixi shell-hook --frozen
```
closes #719

feature: allow specifying the environment in shell-hook

---

src/cli/info.rs

Previously `pixi info` would only show the tasks for one platform, but I don't think that is the most helpful. So now it shows all the tasks. Also if they are not supported.

fix: Allow the tasks for all platforms to be shown in info

---

tests/add_tests.rs

Fix an issue with flaky pypi tests in CI.

fix: flaky tests while installing pypi dependencies

---

examples/cpp-sdl/pixi.lock
examples/cpp-sdl/pixi.toml
src/activation.rs
src/cli/info.rs
src/cli/run.rs
src/cli/task.rs
src/environment.rs
src/lib.rs
src/project/environment.rs
src/project/manifest/feature.rs
src/project/mod.rs
src/task/error.rs
src/task/executable_task.rs
src/task/task_graph.rs
tests/common/mod.rs
tests/task_tests.rs

This adds the ability to run tasks in different environments and modifies the `run` cli command to only check the lock-file once.

feat: run tasks in the env they are defined

---

examples/polarify/.gitattributes
examples/polarify/.gitignore
examples/polarify/pixi.lock
examples/polarify/pixi.toml
examples/polarify/tests/test_versions.py

Add the polarify example from the design document to the examples.
Tested on:

misc: add polarify usecase as an example

---

install/install.sh

The linux installer was broken by #692 and fails currently with 
```
bash: line 83: PIXI_NO_PATH_UPDATE: unbound variable
```
This changes this to use a default value and checks if the string is empty instead

Fix linux installer

---

examples/docker-build/Dockerfile

This helps testing as we can easily spawn a docker image that has pixi installed using `pixi run start` in that example now.

misc: install pixi and add to the path in docker example

---

src/project/manifest/python.rs

refactor: simplify the deserializer of `PyPiRequirement`

---

Cargo.lock
Cargo.toml
src/cli/list.rs

Fix #741 
Replaces `comfy_table` with the much simpler `tabwriter`. This allows us to simply use `console` for all styling which should then follow the rules around `--color`.

refactor: use tabwriter instead of comfy_table

---

src/install_pypi.rs

This is a temp fix for the pypi wheel building deadlock that occurred. Solving that is ongoing but this is a workaround for now.

fix: avoid pypi deadlock

---

src/task/task_graph.rs

Not broken but still a good thing to test

test: running cuda env and using those tasks.

---

pixi.toml
src/project/manifest/mod.rs

This allows the user to call `pixi rm MatPlotLib` if they have that in the pixi.toml. 
closes #761

fix: remove using source name

---

examples/polarify/pixi.lock
examples/polarify/pixi.toml

Once #767 is fixed, `pixi run test` will also work

Add test to default env in polarify example

---

CONTRIBUTING.md
src/cli/info.rs
src/cli/project/channel/list.rs
src/cli/run.rs
src/cli/task.rs
src/consts.rs
src/environment.rs
src/lib.rs
src/project/environment.rs
src/project/errors.rs
src/project/manifest/environment.rs
src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/target.rs
src/project/manifest/validation.rs
src/project/mod.rs
src/project/snapshots/pixi__project__tests__target_specific_tasks-2.snap
src/project/snapshots/pixi__project__tests__target_specific_tasks-3.snap
src/project/snapshots/pixi__project__tests__target_specific_tasks.snap
src/task/error.rs
src/task/executable_task.rs
src/task/mod.rs
src/task/task_environment.rs
src/task/task_graph.rs
tests/common/builders.rs
tests/common/mod.rs
tests/task_tests.rs

Putting in a first pass on generalizing the colors used in the terminal.

misc: set color scheme

---

docs/cli.md
src/cli/list.rs

This avoid list output which is not uptodate with the pixi.toml
closes #774

feat: update lock on `pixi list`

---

src/project/manifest/environment.rs
src/task/mod.rs
src/task/task_environment.rs

This addresses @pavelzw issue in #767 
Which means that if a task is in the default environment we always automatically run it from that environment.

misc: use default env if task available in it.

---

docs/cli.md
src/cli/add.rs
src/cli/project/platform/add.rs
src/cli/project/platform/list.rs
src/cli/project/platform/remove.rs
src/project/manifest/mod.rs
src/utils/spanned.rs

Adds:
```shell
> pixi project platform remove -f/--feature test win-64
> pixi project platform add -f/--feature test win-64
> pixi project platform list
Environment: default
- win-64
- osx-arm64
- linux-64
- osx-64
Environment: test
- linux-64
```

feat: add `-f`/`--feature` to the `pixi project platform` command

---

docs/cli.md
docs/configuration.md
docs/environment.md

Fixup missing CLI options and did a pass on explaining a pixi environment and how to use it.

docs: Add more documentation on `environments`

---

src/environment.rs

misc: color environment name in install step

---

docs/advanced/authentication.md

https://github.com/mamba-org/rattler/blob/main/crates/rattler_networking/src/authentication_storage/backends/file.rs?rgh-link-date=2024-02-09T12%3A34%3A06Z#L119

docs: Fix authentication path

---

Cargo.lock
Cargo.toml

Removes the git references and instead directly targets the latest release. No code changes required. :)

bump: rattler 0.18.0

---

docs/cli.md
src/cli/shell_hook.rs

fixes #810 
This also fixes it for all the other shells as this only worked for `bash` and `cmd`.

fix: use autoguessing of the shell in the shell hook

---

.github/workflows/lint-pr.yml

Since we follow conventional commits specification, it would be nice to have this.

feat(ci): check conventional PR title

---

README.md

I created the Alpine package for `pixi`: <https://pkgs.alpinelinux.org/packages?name=pixi>
This PR aims to add the instructions for installing `pixi` on Alpine.
Also, I made some formatting changes and added repology badge.

docs: add instructions for installing on Alpine Linux

---

src/cli/init.rs
src/utils/conda_environment_file.rs

When importing an environment.yml file we skip the micromamba selector lines. They are very seldomly used and so this is not going to affect many users. 
We are still importing everything that is trivial to import.

feat: skip micromamba style selector lines and warn about them

---

src/cli/add.rs
src/project/manifest/mod.rs

fix: check duplicates while adding dependencies

---

Cargo.lock
Cargo.toml
src/lock_file/pypi_name_mapping.rs

Cache and retry the download of the pypi name mapping.

fix: cache and retyr pypi name mapping

---

docs/configuration.md
src/project/manifest/target.rs
src/project/manifest/validation.rs
tests/pixi_tomls/many_targets.toml
tests/project_tests.rs
tests/snapshots/project_tests__parse_project-2.snap
tests/snapshots/project_tests__parse_project-3.snap
tests/snapshots/project_tests__parse_project.snap

I added a few more targets that should make it easier to select packages for some sets of platforms.
You can now do:
```toml
[target.unix.dependencies]
special-unix-pkg = "*"
[target.windows.dependencies]
pywin32 = "3.12"
```
We could consider to overload `osx`, too. The correct name for osx is macOS though, since a while. Unfortunately that is not reflected in the "subdir" name.

feat: add windows, macos, linux and unix to targets

---

src/cli/info.rs

Adds the prefix folder to the output of `pixi info --json`.

feat: add prefix to project info json output

---

src/project/manifest/environment.rs
src/project/manifest/feature.rs

Changes the output of `project info --json` to output proper environment names:
before: 
```json
{
"name": {
"Named": "pl017"
},
"features": [
{
"Named": "pl017"
},
{
"Named": "py310"
},
{
"Named": "test"
},
"Default"
],
```
after:
```json
{
"name": "pl017",
"features": [
"pl017",
"py310",
"test",
"default"
],
```
Im also wondering if the `"default"` feature should be include in the above list ..

fix: environment and feature names in pixi info --json

---

src/cli/global/list.rs

Before
After
I have handled the read_dir as catch all under assumption that most error would be related to dirs doesn't exist

fix: Improve global list UX when there is no global env dir created

---

cliff.toml

Now `git-cliff` will skip it in the changelog if we add `skip-release-notes` label to a PR.

chore: skip changelog entries by PR label

---

src/cli/global/list.rs
src/cli/init.rs
src/cli/snapshots/pixi__cli__init__tests__test_import_from_env_yaml.cockpit.yml.snap
src/cli/snapshots/pixi__cli__init__tests__test_import_from_env_yaml.crnnft.yml.snap
src/cli/snapshots/pixi__cli__init__tests__test_import_from_env_yaml.let-plot.yml.snap

closes https://github.com/prefix-dev/pixi/issues/877
Please let me know if I can make this more idiomatic.

fix: Avoid duplicate pip dependency while importing environment.yaml

---

src/cli/init.rs

fixes https://github.com/prefix-dev/pixi/issues/868
Since `source` attribute wasn't present on the `Channel` type, I went ahead with this approach

fix: Handle custom channels when importing from env yaml

---

src/install_pypi.rs

I was testing the Prefix main branch with the `uv` integration and noticed it was removing editable installs when it shouldn't, similarly to https://github.com/prefix-dev/pixi/issues/507 which was fixed by in https://github.com/prefix-dev/pixi/pull/509.

fix: pip editable installs getting uninstalled

---

install/install.sh

This addresses https://github.com/prefix-dev/pixi/issues/897
```
$ echo $SHELL
/bin/bash
$ bash ./install/install.sh
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-aarch64-apple-darwin.tar.gz
The binary will be installed into '/Users/romain/.pixi/bin'
######################################################################## 100.0%
Updating '/Users/romain/.bash_profile'
Please restart or source your shell.
```
```
$ echo $SHELL
/bin/tcsh
$ bash ./install/install.sh
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-aarch64-apple-darwin.tar.gz
The binary will be …
```

feat: add tcsh install support

---

src/cli/shell.rs
src/project/mod.rs

This PR adds a user agent to the http Client. Apparently this is needed for some mirrors. 
Fixes #753

fix: add user agent to pixi http client

---

src/environment.rs
src/install_pypi.rs
src/lock_file/update.rs
tests/common/mod.rs
tests/install_tests.rs

Remove distribution from site-packages dir when interpreter changes.

feat: remove dists site-packages's when python interpreter changes

---

src/install_pypi.rs
src/lock_file/resolve.rs

Move the uv no-binary and no-build options into the shared context. So that they are the same across resolve and install.

feat: move uv options into context

---

docs/configuration.md

Updated the PyPI dependencies section.

docs: updated the pypi dependencies section, to use with the uv release

---

src/lock_file/outdated.rs
src/lock_file/update.rs
src/project/grouped_environment.rs
tests/common/mod.rs
tests/common/package_database.rs
tests/install_tests.rs

When switching channels we should disregard all locked conda packages.
Fixes #922

fix: switching channels

---

.github/workflows/schema.yml
.pre-commit-config.yaml
.ruff.toml
docs/configuration.md
examples/ctypes-factorial/src/factorial.py
examples/lightgbm/main.py
examples/opencv/calibrate.py
examples/opencv/webcam_capture.py
examples/polarify/tests/test_versions.py
examples/pypi/pycosat_example.py
examples/qgis/get_data.py
examples/rerun_example/dna_example.py
examples/rerun_example/force_driven_lockfile_graph.py
examples/solve-groups/test_imports.py
pixi.lock
pixi.toml
schema/examples/invalid/no_channel.toml
schema/examples/valid/full.toml
schema/examples/valid/minimal.toml
schema/model.py
schema/schema.json
schema/test_manifest.py
src/install_pypi.rs

Adding a pydantic schema for the `pixi.toml` for future integration into lsp and schema checkers.

feat: add a schema for the pixi.toml

---

src/repodata.rs

Decided to turn back on jlap to improve speed of updating cache for slow internet situations. There are plans to improve the Jlap implementation overall soon.

fix: turn back on jlap for faster repodata fetching

---

src/lock_file/satisfiability.rs

Fixes the issue of `lock-file not up-to-date with the project` when a lockfile contains dependencies that contain matchspecs that can't be parsed using the strict version parsing.  (e.g. `!=1.2.*`, `>=1.2.*`)

fix: parse lockfile matchspecs lenient

---

README.md

This is the default now and doesn't need to be specified

docs: Remove cache: true from setup-pixi

---

README.md
docs/advanced/github_actions.md
docs/basic_usage.md
mkdocs.yml

as discussed in https://github.com/prefix-dev/pixi/pull/950#issuecomment-1988005399
I copied everything from the setup-pixi readme and removed the [Local development](https://github.com/prefix-dev/setup-pixi#local-development) part and made it compatible with mkdocs.
We should make sure that every change to the documentation here will also be changed in the setup-pixi readme. xref https://github.com/prefix-dev/setup-pixi/pull/84

docs: Add GitHub Actions documentation

---

src/install_pypi.rs
src/lock_file/update.rs
tests/common/builders.rs
tests/common/mod.rs
tests/install_tests.rs

This fixes the situation where pypi dependencies were not removed from the prefix, while they were removed in the toml. 
The problem was that if you have a single pypi dependency and removed this, the project would say it does not have pypi dependencies and the updating of the pypi prefix was never done. 
This bug was introduced by me in #863, I think it would be nice to skip this code in the right situation, but seeing as this is a pretty big bug. I think its prudent to use this PR for now.
But hey 🤷‍♂️ , at least we have an add/remove tested now, and the test cli has expanded a bit.
@ruben-arts I've noticed there is also not a test for the conda situation here, maybe we should add it as well.

fix: pypi dependencies not being removed

---

README.md
assets/badge/v0.json
docs/Community.md

chore: add a badge

---

src/cli/global/upgrade.rs

A small logic tweak making `global upgrade <package>` support matchspec input.
before:
```
$ pixi g upgrade python==3.10
× Package is not globally installed
```
after:
```
$ .\target\release\pixi.exe g upgrade python==3.11
Updated python v3.10.0 -> v3.11.0
```
This is useful when they don't want to upgrade a package to the latest version but a slightly newer one.

feat(cli): global upgrade supports matchspec

---

install/install.sh

Closes #965 
This PR downloads and installs `pixi` in a Git Bash shell on Windows. I've updated `install.sh` to properly download the ~~Linux~~ Windows executable. ~~However, the command `chmod +x "$BIN_DIR/pixi"` doesn't work on Windows, so I can't run `pixi` after downloading it. Any ideas?~~

fix: install Windows executable when executing `install.sh` in Git Bash

---

schema/examples/valid/full.toml
schema/model.py
schema/schema.json

Add `tool` to the schema so it will be accepted by the parser.
(Thanks for the ping @pavelzw)

fix: add `tool` to strict json schema

---

src/prefix.rs

The `path::ends_with` function only compares full segments. We need to compare the extension if we want to filter only `JSON` files. 
The condition was anyways wrong (we would have skipped over files that end with json but those are the ones we are interested in).
cc @ruben-arts I believe this would fix the issue with putting the `prefix` file into the `conda-meta` folder.
cc @baszalmstra

fix: more proper scanning of the conda-meta folder for `json` entries

---

docs/environment.md

https://github.com/prefix-dev/pixi/pull/982#issuecomment-1997257818

docs: Mention watch_file in direnv usage

---

docs/index.md

fixes: #917 
There isn't a lot we can do to keep this script a readable one liner so I added a tip so the users will be helped if they have an error.

docs: add tip to help users when no PROFILE file exists

---

docs/advanced/authentication.md
docs/advanced/global_configuration.md
src/cli/global/common.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs
src/cli/info.rs
src/cli/install.rs
src/cli/remove.rs
src/cli/run.rs
src/cli/search.rs
src/cli/shell.rs
src/config.rs
src/snapshots/pixi__config__tests__config_merge.snap
src/utils/reqwest.rs

@pavelzw do you think you could try this branch?
I tested a bit and I could not see what would go wrong with your config file though.

feat: use `RATTLER_AUTH_FILE` and use proper reqwest clients in search

---

.github/workflows/docs.yml

Stop running the docs releases on our forks.

chore: don't run docs releases on forks

---

src/task/task_environment.rs
src/task/task_graph.rs

Those tests' results are affected by unsupported platform error. Adding riscv64 to platforms fixes the issue on it.
Error log:
```
failures:
---- task::task_graph::test::test_multi_env_defaults_ambigu stdout ----
note: test did not panic as expected
---- task::task_environment::tests::test_find_task_explicit_defined stdout ----
thread 'task::task_environment::tests::test_find_task_explicit_defined' panicked at src/task/task_environment.rs:272:9:
assertion failed: matches!(result, Err(FindTaskError::AmbiguousTask(_)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- task::task_environment::tests::test_find_task_dual_defined stdout ----
thread 'task::task_environment::tests::test_find_task_dual_defined' panicked at src/task/task_environment.rs:246:9: …
```

fix: test failure on riscv64

---

docs/advanced/explain_info_command.md
docs/advanced/global_configuration.md
docs/cli.md
src/config.rs

feat(config): `XDG_CONFIG_HOME` and `XDG_CACHE_HOME` compliance

---

.github/workflows/rust.yml

Fixes https://github.com/prefix-dev/pixi/issues/1008
Adds a windows arm build to CI . This PR does not test the generated binary.

feat: build pixi for windows arm

---

src/lock_file/outdated.rs
src/lock_file/update.rs

Fixes #1036
With the following pixi toml:
```toml
[project]
name = "project"
platforms = ["linux-64", "osx-arm64"]
[dependencies]
python = "3.11.8"
timeago = "==1.0.16"
[feature.test]
platforms = ["linux-64"]
[environments]
test = ["test"]
```
The environment `test` is only solvable for `linux-64`. However, when trying to solve this lock-file on another platform no python interpreter can be installed for the environment because the environment does not support it.
This PR shows a problem that we should fix, see #1051 for that tracking issue.

feat: add error for unsupported pypi dependencies

---

src/activation.rs
src/cli/init.rs
src/project/environment.rs
src/project/manifest/document.rs
src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/pyproject.rs
src/project/manifest/target.rs
src/project/mod.rs
src/project/solve_group.rs
src/task/task_environment.rs
src/task/task_graph.rs
tests/project_tests.rs

Some small minor code changes to the pyproject implementation:
* Move some setters to the `ManifestSource` enum.
* `Manifest::from_str` determine the type of manifest from the path argument instead of taking an additional argument.
* Move detection of valid pyproject file in project/mod.rs into a function.

chore: small code fixes for pyproject code

---

docs/cli.md

Fixed error in auth example (CLI docs)

cli docs: --user is actually --username

---

README.md

The installation modified my ` ~/.zshrc` and added the path to `pixi`, i.e. `export PATH=$PATH:~/.pixi/bin`.
Rational: I had problems with the default installation script because my bash was broken. It installed a osx-64 instead of osx-arm64 executable on my M1 MacBook. Going with default shell seems to be sensible.

docs: `zsh` may be used for installation on macOS

---

src/cli/add.rs
src/cli/info.rs
src/cli/init.rs
src/cli/install.rs
src/cli/list.rs
src/cli/project/channel/mod.rs
src/cli/project/description/mod.rs
src/cli/project/mod.rs
src/cli/project/platform/mod.rs
src/cli/project/version/mod.rs
src/cli/remove.rs
src/cli/run.rs
src/cli/search.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/cli/task.rs
src/project/manifest/document.rs
src/project/manifest/mod.rs
src/project/manifest/python.rs
src/project/manifest/validation.rs
src/project/mod.rs
src/utils/conda_environment_file.rs
src/utils/snapshots/pixi__utils__conda_environment_file__tests__test_import_from_env_yaml.cockpit.yml.snap
src/utils/snapshots/pixi__utils__conda_environment_file__tests__test_import_from_env_yaml.conda.yml.snap
src/utils/snapshots/pixi__utils__conda_environment_file__tests__test_import_from_env_yaml.crnnft.yml.snap
src/utils/snapshots/pixi__utils__conda_environment_file__tests__test_import_from_env_yaml.let-plot.yml.snap
src/utils/snapshots/pixi__utils__conda_environment_file__tests__test_import_from_env_yaml.test_env.yml.snap

For "separation of concerns" reasons, I moved all conda environment import related code to a single file (the existing one in utils). The logic is untouched; I just turned the function `conda_env_to_manifest` into a the method `to_manifest`, which felt more idiomatic. 
I also removed bits and pieces related to `PyPiRequirement::Version` index field, which was unused.
Finally, I altered code in places to account for having now two possible names for the manifest file (pixi.toml an pyproject.toml). The only remaining place referring to pixi.toml is in [PixiControl](https://github.com/olivier-lacroix/pixi/blob/faf98db1e47232bcb4617551961428571c0cd2f8/tests/common/mod.rs#L186). Does this have any impact?

chore: Some cleanups

---

examples/pypi-source-deps/pixi.toml
src/cli/list.rs

fix: pixi list shows path and editable

---

src/cli/add.rs
src/cli/run.rs
src/environment.rs

Fixes #1081 
This adds a better message for when an environment is moved and displays an interactive prompt to let users delete the environment directory:
If the users enters `yes` or `y`, the environment directory is deleted (and automatically recreated), anything else returns an error message:

fix: interactively delete environment when it was relocated

---

src/lock_file/mod.rs
src/lock_file/outdated.rs
src/lock_file/satisfiability.rs

Fixes #1098 
When a package was moved from conda dependencies to pypi dependencies and the version is changed  the satisfiability reported that a requirement was satisfiable. However, if a pep508 requirement isn't satisfiable, only the pypi packages are updated, but in this case the conda packages should also be updated.
To fix this I added a separate error for a requirement mismatch on a conda package. This will trigger updating the conda packages as well.

fix: unsolvable when moving dependency from conda to pypi

---

src/project/manifest/python.rs

Fixes #1065 
Rejects unknown keys in Pypi requirements. The error message is still quite terrible but at least you get an error.

fix: dont allow extra keys in pypi requirements

---

src/environment.rs

https://github.com/prefix-dev/pixi/pull/995 introduced a Pixi-generated `conda-meta/history`. Sadly, `#` is a special character in the `history` file, which ends up breaking the `conda.history.History.parse()` function:
```
$ python -c "from conda.history import History as H; print(H('.pixi/envs/default').parse())"                  
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/jrodriguez/devel/conda-pip/.pixi/envs/default/lib/python3.10/site-packages/conda/history.py", line 138, in parse
res[-1][2].append(line)
IndexError: list index out of range
```
`//` does work without issues.

fix: Amend syntax in `conda-meta/history` to prevent `conda.history.History.parse()` error

---

docs/index.md
install/install.sh

On Apple Silicon, one might want to force installing the x86_64 version of pixi. Using the `PIXI_ARCH` variable, this can now be done using:
```
export PIXI_ARCH=x86_64 && curl -fsSL https://pixi.sh/install.sh | bash
```
My use case is to run pixi on GitLab CI saas-macos-medium-m1 runners.
This would make it easier to install pixi for aarch64 or x86_64.

feat: Enable to force PIXI_ARCH for installation

---

src/cli/add.rs
src/cli/init.rs
src/project/manifest/document.rs
src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/pyproject.rs
src/project/manifest/snapshots/pixi__project__manifest__pyproject__tests__add_pypi_dependency.snap

fixes #1133 
Now you can also run:
```shell
pixi add --feature test --pypi elsie
```
This results in a `pixi.toml`  to:
```toml
[feature.test.pypi-dependencies]
elsie = "*"
```
and in a `pyproject.toml` to:
```toml
[tool.pixi.feature.test.pypi-dependencies]
elsie = "*"
```
Note, it doesn't add it to the `optional dependencies` not sure if we should do that. @olivier-lacroix what do you think?

feat: add to pypi in feature

---

CONTRIBUTING.md
src/cli/list.rs

Changed to be able to sort on `kind` instead of `type`. It was called `kind` in list :)

fix: small typo in list cli

---

docs/reference/cli.md
src/cli/mod.rs

Fixes #1165 
Could you take a look? @Hofer-Julian

docs: fix frozen install help

---

src/project/manifest/feature.rs
src/project/manifest/mod.rs
src/project/manifest/pyproject.rs

When features were added with the introduction of the optional dependencies https://github.com/prefix-dev/pixi/pull/1077 they did not include the proper name. This caused solve-groups to not function at all.

fix: issue with invalid solve group

---

docs/advanced/github_actions.md

Depends on https://github.com/prefix-dev/setup-pixi/pull/98

docs: setup_pixi for local pixi installation

---

docs/advanced/pyproject_toml.md
docs/reference/cli.md
src/cli/init.rs
tests/common/mod.rs

feat: Add option to init with a pyproject.toml

---

src/project/manifest/pyproject.rs

I had a `pyproject.toml` that was using optional deps like:
```toml
[project.optional-dependencies]
test = ["pytest"]
conda_build = ["bla"]
```
Upon conversion, pixi complained because 
```
× failed to parse project manifest
╭─[pyproject.toml:26:1]
25 │ default = { solve-group = "default" }
26 │ conda_build = { features = ["conda_build"], solve-group = "default" }
· ─────┬─────
·      ╰── Failed to parse environment name 'conda_build', please use only lowercase letters, numbers and dashes
27 │ test = { features = ["test"], solve-group = "default" }
╰────
```
This fixes that issue.

fix: replace `_` with `-` when creating environments from features

---

src/cli/tree.rs

This should keep `pixi tree` from displaying duplicate top level dependencies by filtering on Conda/PyPI sources. This doesn't handle mapping between Conda/PyPI names.
fixes: #1158

fix: Prevent duplicate direct dependencies in tree

---

src/cli/run.rs
src/task/task_hash.rs

Should improve https://github.com/prefix-dev/pixi/issues/1139
I still want to implement a warning when glob does not match anything at all.

fix: use project root directory instead of task.working_directory for base dir when hashing

---

src/cli/global/install.rs

This fixes #1200 
With this change, for cmd.exe / bat scripts we now wrap the script with:
```
@echo off
setlocal
... script contents
endlocal
```

fix: do not leak env vars from bat scripts in cmd.exe

---

src/task/file_hashes.rs

Previously we were just supplying the plain globs. However that also matched files in sub-folders (e.g. `build.txt` would match `lib/build.txt` and so on).
Now we are always prepending a `/` in front, so that these files are matched based on the root folder (and a plain `build.txt` would only match `/build.txt`, _not_ `lib/build.txt`).

fix: make file globbing behave more as expected

---

src/lock_file/resolve.rs
src/project/manifest/python.rs

Should fix: https://github.com/prefix-dev/pixi/issues/1186
This adds some special case logic for when file:// are found as requirements. As well as has some special logic when uv returns the `file://` as a given. Which is needed because we do not know whether uv builds the local editable or our specified requirement first. In which cases it gives a different `given` than we would expect.

fix: fix for using file::// in pyproject.toml dependencies

---

docs/tutorials/python.md
mkdocs.yml

Adds a simple tutorial about managing a python project to the documentation.

docs: add python tutorial to documentation

---

docs/reference/configuration.md

- pypi dependencies are stable now
- small change in compatibility limitation sentence

docs: Update pypi docs

---

docs/ide_integration/jupyterlab.md
docs/stylesheets/extra.css
mkdocs.yml

What do you guys think about the Binder link? My idea was to help people who want to do a quick test of using Pixi + JupyterLab before adopting it.

docs: add JupyterLab integration docs

---

src/project/manifest/error.rs
src/project/manifest/pyproject.rs

This improves the logic a little bit.
Python versions like `==3.11.*` now get parsed to `3.11.*` which works better for conda requirements.
We warn the user if there is both a `requires-python` and a `python` dependency in the `tool.pixi.dependencies` section.
We prefer the `requires-python` over a value in the pixi deps.
cc @olivier-lacroix 
fixes #1193

fix: make requires-python take precedence, improve version conversion

---

docs/advanced/github_actions.md

The current documentation will trigger the following error:
```shell
ERROR: --no-deps is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
In editable mode, `--no-deps` is just required to be before the `-e`.

docs: fix order of --no-deps when pip installing in editable mode

---

Cargo.lock
Cargo.toml
src/cli/global/install.rs
src/cli/search.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/config.rs
src/install.rs
src/project/manifest/channel.rs
src/project/manifest/document.rs
src/project/manifest/mod.rs
src/snapshots/pixi__config__tests__config_merge.snap
src/util.rs
tests/init_tests.rs
tests/project_tests.rs

This fixes a few issues:
- #1189 
- Entrypoints for prefix with a space in the path should work better on Windows (e.g. when installing noarch python packages such as flask, it wasn't working before). For example if you create a pixi env in `C:\path\to\spacey project\`, then `pixi run flask` should work without issues now
- #1229 
- I tried to fix #1159 but haven't wired it up yet (basically the previous behavior is still there). I need to take another look at how we deserialize the channels, because we cannot inject any configuration into the deserializer (at least not without going through some global static variables).

fix: update to the latest rattler

---

docs/advanced/channel_priority.md
docs/features/multi_environment.md

Document this logic:
```toml
[project]
name = "test_channel_priority"
platforms = ["linux-64"]
[feature.a]
channels = ["nvidia"]
[feature.b]
channels = [ "pytorch", {channel = "nvidia", priority = 1}]
[feature.c]
channels = [ "pytorch", {channel = "nvidia", priority = -1}]
[environments]
a = ["a"]
b = ["b"]
c = ["c"]
```

docs: add channel priority definition documentation

---

src/lock_file/satisfiability.rs
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@expected-editable-multiple__pixi.toml.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@expected-editable__pixi.toml.snap
tests/non-satisfiability/expected-editable-multiple/bar/pyproject.toml
tests/non-satisfiability/expected-editable-multiple/baz/pyproject.toml
tests/non-satisfiability/expected-editable-multiple/foo/pyproject.toml
tests/non-satisfiability/expected-editable-multiple/pixi.lock
tests/non-satisfiability/expected-editable-multiple/pixi.toml
tests/non-satisfiability/expected-editable/foo/pyproject.toml
tests/non-satisfiability/expected-editable/pixi.lock
tests/non-satisfiability/expected-editable/pixi.toml
tests/satisfiability/editable-non-editable/bar/pyproject.toml
tests/satisfiability/editable-non-editable/foo/pyproject.toml
tests/satisfiability/editable-non-editable/pixi.lock
tests/satisfiability/editable-non-editable/pixi.toml

Fixes an issue where multiple requirements of editable/non-editable would conflict and cause the lock-file to be non satisfiable. However, the logic should be that if just one requirement specifies an editable install then it should be editable regardless of what other requirements specify.
You also get a nice error message:
```
expected bar, and foo to be editable but in the lock-file they are not, whereas baz is NOT expected to be editable which in the lock-file it is
```
Note that I also included several tests that test several cases.

fix: editable non-satisfiable

---

src/project/manifest/document.rs
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_bar.snap
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_baz.snap
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_fooz.snap
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_pypi_feature_dep.snap
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_pypi_feature_target_dep.snap
src/project/manifest/snapshots/pixi__project__manifest__tests__test_remove_pypi_requests.snap

Currently, pixi can create, or leave behind, empty tables in the TOML manifest.
This PR avoids that

fix: Avoid creating Empty TOML tables

---

install/install.sh

.bash_profile is edited, so it needs to exist and be writable

fix: Modify test before attempting to write to .bash_profile in install.sh

---

src/cli/install.rs
src/cli/list.rs
src/cli/shell.rs
src/cli/task.rs
src/cli/tree.rs
src/project/manifest/environment.rs
src/project/mod.rs

fix: Parse properly 'default' as environment Cli argument

---

src/cli/run.rs
src/task/executable_task.rs

Fixes #1256 
Note this does error now on `pixi run -e docs` as we had a requirement to set any option but we meant to say that you need to set a task. This is in theory breaking but it was wrong in my opinion.

fix: improve parse deno error and make task a required field in the cli

---

pixi.lock
pixi.toml

I couldn't run `pixi run install` or `pixi run build` anymore. This fixes that. The PR which broke it for me was: #1273. Probably because of the `cc` bump.

fix: build on linux in pixi env

---

docs/advanced/global_configuration.md
src/config.rs

In some scenarios, you might want to pre-configure pixi but not touch the `$HOME` directory because it belongs to the user using it and not the system administrator.
In these cases, it might be beneficial to have a global system configuration file.

feat: Add /etc/pixi/config.toml to global configuration search paths

---

docs/advanced/global_configuration.md
src/config.rs

This PR adds the option to use kebab-case in the global config. Which will be the preferred option, for older options we've kept the old way of `snake_case` configuration.
Also, the documentation was updated to reflect this. There was as error in the `repodata-config` in the documentation this was incorrectly named `repodata-options` this has *never* worked. This has also been rectified.

feat: change global config to kebab-case

---

src/cli/global/mod.rs
src/cli/mod.rs
src/cli/project/channel/mod.rs
src/cli/project/platform/mod.rs
src/cli/task.rs

This aligns aliases, e.g.:
- Remove should have `rm`  as an alias
- List should have `ls` as an alias
- Install should have `i` as an alias.
I found that we aliased `global install` to `g a` which I hate. So I made the correct aliases visible in the help command and we can hopefully later remove them when we break.

fix: align aliases and add missing

---

docs/examples/cpp-sdl.md
docs/features/advanced_tasks.md
docs/reference/cli.md
docs/reference/configuration.md
docs/tutorials/ros2.md
docs/tutorials/rust.md
examples/cpp-sdl/pixi.toml
examples/ctypes-factorial/README.md
examples/ctypes-factorial/pixi.toml
examples/multi-machine/pixi.toml
examples/qgis/pixi.toml
pixi.toml
schema/examples/valid/full.toml
schema/model.py
schema/schema.json
src/cli/task.rs
src/project/manifest/pyproject.rs
src/task/mod.rs
src/task/task_graph.rs

Inspired by #1308
Note that the schema is updated to also understand both but with deprecation documentation. And the ability to removed this after future releases to force users that lint their toml to be using the correct version.

fix: alias depends_on to depends-on

---

docs/tutorials/python.md

I was searching the documentation for a way to install optional dependencies from PyPI using pixi and got helped on the Discord.
I figured the Python tutorial is the most straightforward place to add this, while the functionality is still being developed.
I have taken this chance to slightly adjust the flow of the tutorial and used Grammarly Premium to work through the grammar and sprinkle in some commas.

docs: Python Tutorial: Dependencies, PyPI, Order, Grammar

---

src/lock_file/satisfiability.rs
src/project/dependencies.rs
src/project/environment.rs
src/project/has_features.rs
src/project/mod.rs

@tdejager , this aligns the way Pypi and Conda dependencies are being merged in the `HasFeatures` trait

refactor: Use generics over PyPiDependencies and CondaDependencies

---

src/cli/global/common.rs
src/cli/global/install.rs
src/cli/global/list.rs
src/cli/global/remove.rs
src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs

This PR refactors most of `upgrade.rs` and `upgrade_all.rs` into a common `upgrade_packages` function, which upgrades several global packages at once.
Now, several global packages can be upgraded at once.

feat: Allow to upgrade several global packages at once

---

pixi.lock
pixi.toml

Fix that will hopefully continue to work for the `pixi-feedstock`

fix: remove dependency on sysroot for linux

---

Cargo.lock
Cargo.toml

Bumps the version of rattler to the latest. 
I also added the required features to reqwest to enable HTTP/2. We were only using HTTP/1 thus far!
Fixes: https://github.com/prefix-dev/pixi/issues/1309

chore: bump rattler

---

src/utils/reqwest.rs

This should fix users with slower internet connection. Currently, a package can download only for 5 minutes - which is definitely not appropriate for some larger ones.
With the `read_timeout` this value is reset at every read so only really stalled connections will time out.

fix: use read timeout, not global timeout

---

src/project/environment.rs
src/project/has_features.rs

The issue described in #1331 can be simplified into the added test:
```
[project]
name = "holoviews"
channels = ["a", "b"]
platforms = ["linux-64"]
[environments]
foo = ["foo"]
[feature.foo]
channels = ["a", "c", "b"]
```
The channels for env `foo` should be `["a", "c", "b"]` but the current logic in `v0.21.0` changes it to have the default feature channels always at the end resulting in `["c", "a', "b"]`. 
We changed this back to keep the order of the features, and only add the missing channels from `default` last in the list. 
So this fixes #1331

fix: channel priority logic

---

docs/reference/cli.md

`environment` flag was missing from documentation. Also updated documentation as mentioned in https://github.com/prefix-dev/pixi/issues/1333#issuecomment-2097579544

docs: Update `install` cli doc

---

src/lock_file/records_by_name.rs

More generics over Conda & Pypi related records

refactor: Use generic for RepoDataRecordsByName and PypiRecordsByName

---

docs/features/multi_environment.md

I think `no-default-feature` was introduced exactly for this use case. Having to keep the default env empty or undefined shouldn't be needed anymore.

docs: Replace empty default example with no-default-feature

---

.github/workflows/docs.yml
install/docs_hooks.py
pixi.toml

The `install.sh` and `install.ps1` where significantly outdated because the update mechanism was faulty
Ps. this is not in a rush as I manually updated the upstream. That's why I know this changes works.

fix: automated update of install script in pixi.sh

---

src/cli/project/platform/mod.rs
src/cli/project/version/mod.rs

`channel` main docstring and `platform` main docstring are the same, same thing with `description` and `version`. Doubt it's intentional, easy change.
Before:
```
Commands:
channel      Commands to manage project channels
description  Commands to manage project description
platform     Commands to manage project channels
version      Commands to manage project description
help         Print this message or the help of the given subcommand(s)
```
After:
```
Commands:
channel      Commands to manage project channels
description  Commands to manage project description
platform     Commands to manage project platforms
version      Commands to manage project version
help         Print this message or the help of the given subcommand(s)
```

fix: wrong description on `pixi project help`

---

src/environment.rs
src/install_pypi.rs
src/lock_file/update.rs
tests/install_tests.rs

Fixes #1232 
Now we do two things if there is no `pypi-dependencies`:
- Check if we need to remove some `site-packages`.
- Skip everything that requires to call the python interpreter.
To not make the test abonormally slow we "abuse" one of the tests to try to install `python` `2.7` which will not work if we by accident try to run any `uv` related work.

fix: don't need a python interpreter when not having `pypi` dependencies.

---

src/cli/shell_hook.rs

fixes #1360 
The problem was that we missed the persistent shell feature in `shell-hook` so it wasn't keeping the correct environment in the restart of the shell after `install, add, remove`

fix: align shell-hook cli with shell

---

docs/reference/cli.md
src/cli/add.rs
src/cli/remove.rs

This documents the behaviour introduced by a number of PRs, including: https://github.com/prefix-dev/pixi/pull/999, https://github.com/prefix-dev/pixi/pull/1246, https://github.com/prefix-dev/pixi/pull/1246

docs: Document the add & remove cli behaviour with pyproject.toml manifest

---

src/cli/completion.rs
src/cli/run.rs
src/cli/snapshots/pixi__cli__completion__tests__zsh_completion.snap

I didn't realize `pixi run` could also execute arbitrary commands in an environment and thought only pre-defined tasks, based on the CLI help text. This small patch makes this a little clearer for folks not reading the online manual.

docs: clarify in CLI that run can also take commands

---

docs/reference/cli.md
src/cli/list.rs

implements #1372 
feature: add cli flag for `pixi list` so users can filter only for explicit packages using `--explicit` , additionally with `-x` 
```
-x, --explicit                       Only list packages that are explicitly defined in the project
```
```
List project's packages. Highlighted packages are explicit dependencies
Usage: pixi list [OPTIONS] [REGEX]
Arguments:
[REGEX]  List only packages matching a regular expression
Options:
--platform <PLATFORM>            The platform to list packages for. Defaults to the current platform
--json                           Whether to output in json format
--json-pretty                    Whether to output in pretty json format
--sort-by <SORT_BY>              Sorting strategy [default: name] [possible values: size, name, kind] …
```

feat: add explicit flag to CLI list command

---

src/cli/global/common.rs
src/cli/global/install.rs
src/cli/global/upgrade.rs

Fixes https://github.com/prefix-dev/pixi/issues/1318

fix: Use the right channels when upgrading global packages

---

src/cli/add.rs
src/cli/global/common.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/upgrade.rs
src/cli/has_specs.rs
src/cli/init.rs
src/cli/mod.rs
src/cli/remove.rs
src/project/manifest/mod.rs
src/project/manifest/pyproject.rs
tests/add_tests.rs
tests/common/builders.rs
tests/common/mod.rs
tests/install_tests.rs
tests/solve_group_tests.rs

Refactors Args of `pixi add` and `pixi remove` into a common struct and aligns arguments:
- Like `add`, `remove` now accepts a Vec of platforms
- Like `add`, `remove` now accepts a `no_lockfile_update` argument
- Use same console messages for `remove` as for `add`
In addition,
- iteration over platforms is pushed down the stack, as it was always wrapping calls to the dependency add / remove methods
- package & package name extraction is refactored to use the HasSpecs trait

feat: Align `remove` arguments with `add`

---

src/cli/install.rs
tests/common/mod.rs

Allow installation of multiple envs at the same time. Eg:
```bash
pixi install -e default -e other
```

feat: allow installing multiple envs at once

---

src/prompt.rs

fixes [prefix-dev/pixi#1407](https://github.com/prefix-dev/pixi/issues/1407)
I adapted the prompt logic from conda and made some small changes for pixi.
The environment name is displayed on the right side per default, but can be moved to the left like this:
```
set -gx CONDA_LEFT_PROMPT 1
```
I have tested it with a vanilla fish theme and my tide prompt. It looks good now.
I noticed that there's a source /tmp/pixi_env_....fish line printed twice which is not ideal, but out of scope for this PR, as it is not a fish specific issue.

fix: fish prompt display looks wrong in tide

---

src/cli/run.rs

Use the recently-added logic for figuring out the env name from an activated shell. Should fix: https://github.com/prefix-dev/pixi/issues/1435

fix: should now use the activated environment when running a task

---

src/install_pypi.rs

Because of caching, the credentials were not available when a solve was
skipped. This makes sure the username and potentially password are
available for pulling from the registry.
More details are in this issue: https://github.com/prefix-dev/pixi/issues/1374#issuecomment-2138874996

fix: For installing from a lock file without doing a solve beforehand

---

src/cli/info.rs

```toml
channels = ["https://fast.prefix.dev/conda-forge"]
```
Before:
```
> pixi info
...
Channels: conda-forge
...
```
After:
```
> pixi info
...
Channels: https://fast.prefix.dev/conda-forge
...
```

fix: channel display channels

---

src/pypi_mapping/prefix_pypi_name_mapping.rs
tests/solve_group_tests.rs

While trying to reproduce #1230 , I've observed that we record purl for packages even that are not conda-forge but from pytorch.
so by having this example:
```
[dependencies]
captum = {version="*", channel="pytorch"}
boltons = {version = "*"}
captum = { version = "*"}
```
we need to have purl only for boltons, and empty purls for captum with a warning that pypi will overwrite it.

fix: don't record purl for non conda-forge channels

---

Cargo.toml

Could it be correct that this is related to this issue: https://github.com/conda-forge/pixi-feedstock/issues/46?

fix: remove debug true in release

---

src/cli/run.rs
src/project/environment.rs
src/task/task_environment.rs

I believe this allows `osx-64` only environments' tasks to run on osx-arm64. @wolfv Could you verify. I only checked with faking the current platform on my machine.
e.g. this should work on `osx-arm64`:
```toml
[project]
name = "foo"
channels = ["foo"]
platforms = ["linux-64", "win-64", "osx-64"]
[tasks]
test = "echo test"
```
```
pixi run test
```
Fixes #1404

fix: use best_platform to verify the run platform

---

src/cli/install.rs

The installed environments are now listed inline similar to the other commands. The formatting of the message has been updated from tab delimited to comma seperated. 
resolves #1486

fix: `pixi install --all` output missing newline 

---

.gitattributes
.gitignore
src/cli/init.rs

~With `.pixi/config.toml` being a valid configuration place, what do you think about excluding it from .gitignore?~
Also, with pixi.lock file diffs getting very large, especially with multi-envs, I think it makes sense to add `linguist-generated=true` (in some cases, github refused to render the markdown anyway). https://github.com/pavelzw/pixi-diff-to-markdown can generate a bit prettier diffs anyway.
Maybe it makes sense to have a diff mode `pixi diff pixi.lock.old pixi.lock.new` as well that generates the same json output as `pixi update --json` and allow people to configure their git diff to use pixi similar to how [bun does it](https://bun.sh/guides/install/git-diff-bun-lockfile).

chore: Update default pixi gitignore and gitattributes

---

docs/features/multi_environment.md

Improve documentation on task logic in multi env. Related to #https://github.com/prefix-dev/pixi/issues/1491

docs: improve multi env tasks documentation

---

docs/reference/cli.md
schema/examples/valid/full.toml
schema/model.py
schema/schema.json
src/cli/run.rs
src/cli/task.rs
src/task/mod.rs
tests/common/mod.rs

first PR for the work for #1113 and part of #1434 
I believe next missing work would be some tests and I'm not entirely certain on how to update the `schema`. 
note: I realized that the output for `task list` is now in a single line, so the description only prints after the `run` command if a description exists.

feat: add `description` field to `task`

---

docs/reference/project_configuration.md

Fix typo in documentation, replace `:` with `=`

docs: fix typo in  project_configuration.md

---

pixi.toml
src/activation.rs
src/cli/run.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/lib.rs
src/lock_file/update.rs
src/project/environment.rs
src/project/mod.rs
src/task/executable_task.rs
tests/common/mod.rs
tests/test_activation.rs

Fixes #1503
Fixes #1505
The issue was that the work on the clean-env introduced a situation where all env vars of the current environment are added to the shell activation. This is not what we want, so this pr reverts that behavior.
This pr adds
- Cleanup of the activation code
- Storage of both the clean and normal environment variables when used in the tasks.
- Introduces Environment variable behavior to tell the activator what to do with the current environment
- Removes windows non-sense, I added the possible code to the related issue : #289 for future reference.

fix: too much shell variables in activation of `pixi shell`

---

docs/basic_usage.md

To quit python in terminal use exit() instead of exit

fix: tiny error in basic_usage.md

---

src/project/mod.rs

Fixes #1499 
The config from the CLI was set *after* the reqwest client was initialized. I modified the initialization to create the client lazily. This ensures that the config is properly set on the project before the client is initialized.

fix: lazy initialize client

---

docs/reference/cli.md

docs: describe the --change-ps1 option for pixi shell

---

.pre-commit-config.yaml
src/lock_file/satisfiability.rs

Short sha hashes failed satisfiability checks, this has been fixed and the test has been updated.

fix: fix satisfiability for short sha hashes

---

src/install_pypi.rs

Wrong path was passed to the dynamic check. This made the editable be re-installed each time.
Fixes: https://github.com/prefix-dev/pixi/issues/1526

fix(install_pypi): wrong path passed to dynamic check

---

src/cli/task.rs

Fixes https://github.com/prefix-dev/pixi/issues/1547
I have tried some different approaches, and this one was less intrusive. I'm open to suggestions.

fix: Don't error if no tasks is available on platform

---

src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-64.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-aarch64.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.linux-ppc64le.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.osx-64.snap
src/project/snapshots/pixi__project__virtual_packages__tests__test_get_minimal_virtual_packages.osx-arm64.snap
src/project/virtual_packages.rs

This PR bumps the system requirements to be more in line with current `manylinux2_28` and minimum macOS versions. 
While conda-forge is very conservative with the default system requirements, we can be a bit more bold. We based our first set of defaults on `conda-forge` defaults, but the aims are somewhat different: conda-forge tries to build packages for maximum compatibility while we are developing a software that is modern and probably mostly used on recent machines. 
There is some pain with wheels that are only available for macOS 13.0+ which have become somewhat common on PyPI. Users would then receive `sdists` with all of their problems. Therefore I think it would be good to bump the minimum here. Users that want to support older systems or RedHat style Linux versions can always set …

feat: bump system requirements

---

src/activation.rs
src/project/mod.rs

I think this will fix: #1480 
@baszalmstra any idea how I could make a test for it? The problem is that the test should happen relative to the cwd, because of the relative loading of the toml. But setting cwd is a pretty bad idea in tests I think..

fix: remove double manifest warning

---

tests/task_tests.rs

Fix for flaky task test, not using `remove_var` because of: https://doc.rust-lang.org/std/env/fn.remove_var.html
> Even though this function is currently not marked as unsafe, it needs to be because invoking it can cause undefined behaviour. The function will be marked unsafe in a future version of Rust. This is tracked in [rust#27970](https://github.com/rust-lang/rust/issues/27970).
> This function is safe to call in a single-threaded program.
> In multi-threaded programs, you must ensure that are no other threads concurrently writing or reading(!) from the environment through functions other than the ones in this module. You are responsible for figuring out how to achieve this, but we strongly suggest not using set_var or remove_var in multi-threaded programs at all.

fix: flaky task test

---

CHANGELOG.md
cliff.toml
docs/docs_hooks.py
mkdocs.yml

Add a hook to copy the changelog to the docs build so that it's available via the site too. I was frequently swapping between github and the website to see the changes in the new versions.
Also updated is the exitsting changelog itself so that the TOC is rendered properly in the built site. See preview below
In addition, the template used to generate the documentation has also been modified slightly so that the future docs are rendered  with the updated heading sections.

docs: Add changelog to docs

---

docs/reference/project_configuration.md

In #1553, the system requirements were bumped, updated the docs to reflect this.

docs: updated the values of the system requirements

---

src/cli/run.rs
src/task/executable_task.rs
src/task/mod.rs
src/task/task_graph.rs

Fixes #1492
Passes additional command line arguments verbatim via `pixi run` to deno task shell. 
```
> pixi run python -c 'import sys; print(sys.argv)' '*foo*'
['-c', '*foo*']
```
But only if there is more than one argument, so if a user quotes the entire command it is still interpreted in its entirety by deno task shell:
```
> pixi run "python -c 'import sys; print(sys.argv)' '*foo*'"
glob: no matches found '.../*foo*'
```

fix: pass command line arguments verbatim

---

docs/reference/cli.md
src/cli/config.rs

result of try this issue: https://github.com/prefix-dev/pixi/issues/1557
now you can run 
```
pixi config xxx -g
pixi config xxx -s
pixi config xxx -l
```
for `global` `system` and `local`

feat: add short options to config location flags

---

README.md
docs/index.md

fixes #1578 
I can't seem to find other work arounds, if anyone knows a better one please let me know!

docs: tell cargo install which bin to install

---

docs/reference/cli.md

Adds missing reference documentation for the `exec` command.

docs: add reference documentation for the exec command

---

Cargo.lock
Cargo.toml
README.md
docs/index.md
src/cli/completion.rs

- Add nushell completion
- Stop guessing shell, and make `--shell` required
- Adapt instructions
I have a version local that still tries to guess the shell from the `$SHELL` env var. But it made the code much more verbose, and I am not a fan of that behavior. On my system, `$SHELL` gives `/bin/bash` even though I use nushell.
I also adapted the instructions to stop suggesting that your choice of shell is platform dependent. Every listed shell can be used on Windows and vice versa.

feat: Add nushell completion

---

Cargo.toml

Adding `clap_complete_nushell` failed after merging since it wasn't in sync with Bas' PR adding workspace dependencies

fix: Add `clap_complete_nushell` to dependencies

---

docs/switching_from/conda.md
docs/switching_from/poetry.md
mkdocs.yml
pixi.toml

This is a starting point to start adding more beginner friendly documentation. 
Disclaimer, I've not used `conda` `mamba` `poetry` more then just for examples. The deeper details are not known to me. So any improvements are welcome, that said this should merge fast and incrementally improve overtime.

docs: add transitioning docs for `poetry` and `conda`

---

docs/tutorials/python.md

I noticed the package name in the python tutorial was using '_' instead of '-' for the root folder (and therefore package name).
Using '_' is however correct for the module name.

docs: Use '-' instead of '_' for package name

---

src/cli/global/install.rs

I've had helped to many people with `pixi global install pip`
This feels like a helpful temp fix.

feat: interactive warning for packages in `pixi global install`

---

src/cli/completion.rs
src/cli/snapshots/pixi__cli__completion__tests__nushell_completion.snap

- Add completion for `pixi run --environment` for nushell
- Also fixes a small doc bug with the former version
- Simplify `pixi run` completion script

feat: Add completion for `pixi run --environment` for nushell

---

Cargo.lock
Cargo.toml
docs/reference/project_configuration.md
examples/multi-machine/pixi.lock
examples/multi-machine/pixi.toml
pixi.lock
schema/examples/valid/full.toml
schema/model.py
schema/schema.json
src/lock_file/resolve/conda.rs
src/lock_file/update.rs
src/project/has_features.rs
src/project/manifest/feature.rs
src/project/manifest/metadata.rs
src/project/manifest/mod.rs

Allows the user to turn off strict priority:
```toml
[project]
channel-priority = "disabled"
[feature.no-default]
channel-priority = "strict"
[environments]
no-default = { no-default-feature = true, features = ["no-default"] }
error = ["strict"] # mixing strict and disabled errors
```
Closes #1254 #1532 #1029

feat: add channel-priority to the manifest and solve

---

.github/workflows/rust.yml

On the release `v0.26.0` build we missed the build for the MSI installer as it was set to `continue-on-error`.

fix: Make sure we also build the msi installer

---

docs/features/multi_environment.md

Fix a typo in the markdown documentation

fix: Fix a typo

---

docs/index.md

Output to the `completions` directory, this seems more of the fishy way, AFAIK.

docs: improve the fish completions location

---

src/cli/global/mod.rs
src/cli/list.rs
src/cli/task.rs

⚠️Breaking change ⚠️
Now that we touch the CLI, let's also remove the deprecated aliases

chore!: Remove deprecated CLI aliases

---

crates/pixi_manifest/src/pypi/pypi_options.rs
src/environment.rs
src/install_pypi.rs
src/lock_file/update.rs
src/utils/uv/conversions.rs

When thinking about how install should work off the lock file mostly, I found out that we are using the manifests pypi-options in the installation. I think this can be replaced by the locked indexes, especially as we have the actual url's at hand when making the `Dist`'s.
This implements that refactor, the only assumption I've made is that the first url in the list is the equivalent of the `IndexLocation` `index_url`, this mainly being the main pypi index in most cases.

feat: use locked pypi indexes during installation

---

src/pypi_mapping/custom_pypi_mapping.rs
src/pypi_mapping/mod.rs
src/pypi_mapping/prefix_pypi_name_mapping.rs
tests/solve_group_tests.rs

While debugging the `opencv-headless` issue from #771 I noticed that the most accurate mapping (the hash based mapping) wasn't actually used! This PR fixes the logic.

fix: hash pypi mapping wasnt used

---

Cargo.lock
crates/pixi_manifest/Cargo.toml
crates/pixi_manifest/src/manifest.rs
src/lock_file/satisfiability.rs
src/project/mod.rs
tests/project_tests.rs

I have extracted drive-by refactors from https://github.com/prefix-dev/pixi/pull/1485
- Defer much of `Project::load` to `Project::from_manifest` for consistency, and to avoid repetition.
- Rename `Project::load` to `Project::from_path`, to be consistent with `Manifest::from_path`
- Remove unused method `Manifest::solve_group`, as well as unnecessary collection

refactor: Make project manifest loading DRY and consistent

---

src/cli/project/channel/add.rs
src/cli/project/channel/mod.rs
src/cli/project/channel/remove.rs
tests/common/builders.rs
tests/common/mod.rs

Refactor channel add and remove CLI command into a common `AddRemoveArgs` struct with helper methods

refactor: Refactor channel add and remove CLI commands

---

src/cli/completion.rs

Add one more line to the fish script for code completion to support listing tasks in `pixi run`.
I didn't know how to add description information but as far as I saw for the other shells, it's not yet used there either.
Closes https://github.com/prefix-dev/pixi/issues/1191

feat: add pixi run completion for fish shell

---

Cargo.toml
crates/pixi_manifest/src/document.rs
crates/pixi_manifest/src/pypi/pypi_requirement_types.rs

This PR makes `pixi_manifest` crate compatible with the `pep440_rs` and `pep508_rs` available from crates.io.

fix: depend on pep440_rs from crates and use replace

---

crates/pixi_manifest/src/dependencies.rs
crates/pixi_manifest/src/lib.rs
src/project/environment.rs
src/project/has_features.rs
src/project/mod.rs

Move `Dependencies` to `pixi_manifest`. This is useful to have in `pixi-build`.
**Next**, split `Project` from `HasFeatures` and move `HasFeatures` to `pixi_manifest`.

refactor: move dependencies to pixi_manifest

---

crates/pixi_manifest/src/metadata.rs
crates/pixi_manifest/src/parsed_manifest.rs
crates/pixi_manifest/src/pyproject.rs

Copies the `version`, `description`, and `authors` from the pyproject if they are not explicitly defined in the `[tool.pixi.project]` section.

feat: copy version, description and authors from pyproject

---

Cargo.lock
Cargo.toml
crates/pixi_config/Cargo.toml
crates/pixi_config/src/gateway.rs
crates/pixi_config/src/lib.rs
src/cli/exec.rs
src/project/repodata.rs
src/utils/mod.rs

This continue to make the `project` module entirely independent of anything in the main pixi crate.
This makes moving a lot simpler, which allows us to use it in pixi build
I've put the repodata conversion behind a feature, because not everything might need it :)

refactor: move config to repodata functions

---

docs/advanced/github_actions.md
docs/advanced/updates_github_actions.md
docs/reference/cli.md

https://github.com/pavelzw/pixi-diff-to-markdown/pull/22
https://github.com/prefix-dev/setup-pixi/pull/131

docs: Mention pixi exec in GHA docs

---

crates/pixi_manifest/Cargo.toml
src/utils/reqwest.rs
src/utils/uv/requirements.rs

Small changes looking at TODO comments:
* Error on asking a PyPi package that is not a dir to be editable
* remove unused default_retry_policy()
* Use console workspace dep as opposed to specifying version

fix: To do clean up

---

crates/pixi_manifest/src/error.rs
crates/pixi_manifest/src/manifest.rs
crates/pixi_manifest/src/pyproject.rs
src/cli/init.rs
src/install_pypi.rs
src/project/mod.rs

This Fixes https://github.com/prefix-dev/pixi/issues/1687 and https://github.com/prefix-dev/pixi/issues/1207 by keeping the `[project]` table optional in `pyproject.toml`.
The `[project]` table had been made mandatory to make sure a name was defined. Now, the project name is read from, in order of priority
- the `[tool.pixi.project]` table
- the `[project]` table
- the `[tool.poetry]` table
The same is done for project description, version and authors.
During init, if the name cannot be read from the `[project]` table or the `[tool.poetry]` table, a default name (inferred from the directory name) is added to the `[tool.pixi.project]`
This PR also refactors handling of `pyproject.toml`: both pixi and non-pixi `pyproject.toml` are now read into the same `PyProjectManifest` struct, with …

feat: Make project table optional for `pyproject.toml` manifests

---

.github/workflows/rust.yml

Made it 13 instead of 12 as that was the default setting for pixi's default virtual packages.

fix: test on macos-13 e.g. x86

---

docs/features/multi_environment.md
examples/multi-machine/pixi.lock
examples/multi-machine/pixi.toml

The example as it was would not solve, it ends with a fairly obscure error:
```
× failed to solve the conda requirements of 'mlx' 'osx-arm64'
╰─▶ Cannot solve the request because of: mlx >=0.5.0,<0.6.0 cannot be installed because there are no viable options:
└─ mlx 0.5.0 | 0.5.0 | 0.5.0 | 0.5.0 | 0.5.0 | 0.5.1 | 0.5.1 | 0.5.1 | 0.5.1 | 0.5.1 would require
└─ __osx >=13.3, for which no candidates were found.
```
This was already found previously in https://github.com/prefix-dev/pixi/issues/562#issuecomment-1855847020, and the fix is to add a minimum macOS version. Note that the conda-forge package metadata (saying >=13.3) is also incorrect, the 13.5 minimum added to the example comes from the MLX docs: https://ml-explore.github.io/mlx/build/html/install.html#
While we're at it, also update …

docs: fix mlx feature in "multiple machines" example

---

Cargo.lock
Cargo.toml
src/cli/add.rs
src/cli/global/install.rs
src/environment.rs
src/lib.rs
src/lock_file/update.rs
src/lock_file/utils.rs
src/rlimit.rs

This is an attempt to fix #1551
This PR does two things:
* Concurrent prefix installations share the same io concurrency limit to ensure we dont open too many files when running multiple installations concurrently.
* Pixi attempts to increase the soft rlimit to a "more sensible" value of 1024.
@wolfv, @ruben-arts  Would you be able to test this PR locally. I added a bunch of tracing to the rlimit setting. I wonder what happens on your machine.

fix: try to increase rlimit

---

docs/advanced/updates_github_actions.md

Fixes #1773
We could add a note, that projects without `pypi-dependencies` could add `--no-install`. I am not sure if it's worth it.

docs: Fix instructions for update github actions

---

docs/design_proposals/pixi_global_manifest.md
docs/features/pixi_global_manifest.md
mkdocs.yml

[Rendered version](https://github.com/Hofer-Julian/pixi/blob/docs/pixi-global-proposal/docs/features/pixi_global_manifest.md)

docs(rfc): pixi global proposal

---

docs/reference/project_configuration.md

This adds another example to the reference showing how to use existing environment variables in the env definition section.

docs: Expands the environment variable examples in the reference section

---

.github/workflows/rust.yml

It sometimes gets stuck in an infinite loop.
By timing out after an hour, we improve the situation somewhat.

ci: Add timeout to job "Rust / Cargo Test"

---

src/task/task_graph.rs

Only compile `TaskNode::full_command` for tests and make it `pub(crate)`
Saw this trick in a different part of the code base and thought it fit nicely here as well

refactor: Only compile `TaskNode::full_command` for tests

---

crates/pixi_manifest/src/environment.rs

derive `Default` for more `Environment` and `EnvironmentName`

refactor: derive `Default` for more structs

---

docs/design_proposals/pixi_global_manifest.md

The environment can only contain lowercase latin characters, numbers and dashes

docs: stop using invalid environment name in pixi global proposal

---

docs/reference/pixi_configuration.md
src/cli/info.rs

fix: show global config in info command

---

docs/features/environment.md
docs/reference/project_configuration.md
src/activation.rs
src/cli/run.rs
src/project/mod.rs
src/task/executable_task.rs
src/task/mod.rs
tests/common/mod.rs

Implement the same behavior as `deno_task_shell`
https://docs.deno.com/runtime/manual/tools/task_runner/#specifying-the-current-working-directory

feat: add `INIT_CWD` to activation env

---

docs/features/environment.md

Hopefully fixes docs formatting here: https://pixi.sh/latest/features/environment/#caching

fix: format in docs/features/environment.md

---

crates/pypi_mapping/src/custom_pypi_mapping.rs
crates/pypi_mapping/src/lib.rs
src/lock_file/update.rs
src/project/mod.rs
tests/solve_group_tests.rs

Partly fixes #1764 
Fixes #1791 
We didn't read the channel name in the mapping correctly anymore. This fixes that.
This now forces the user to have the channel in the mapping defined as an actual channel. Giving the user this error:
```
❯ pixi install
× Defined conda-pypi-map channel: bla is missing from the channels, which are: conda-forge, robostack, https://fast.prefix.dev/conda-forge/, bioconda
````
Added a test to verify

fix: make proper use of NamedChannelOrUrl

---

src/cli/search.rs

Fixes #1827 
I made the search less wild by increasing the required similarity score.
```
> pixi search gcc* -p osx-arm64
Using channels: conda-forge
x Could not find gcc
```
```
> pixi.exe search rttler* -p osx-arm64
Using channels: conda-forge
Package                                  Version             Channel            
py-rattler                               0.6.3               conda-forge/osx-arm64
py_rattler                               0.6.3               conda-forge/noarch
```

fix: tame search

---

src/cli/tree.rs

Fixes #1839 
Previously visited packages are marked with a `*` in the tree similar to when you do not use `-i`.
This is the output of the issue reported after applying this PR:
```sh
> pixi tree -i python
python_abi 3.12
├── pydantic-core 2.20.1
│   └── pydantic 2.8.2
│       └── fastapi 0.112.1
│           └── fastapi-cli 0.0.5
│               └── fastapi 0.112.1 (*)
├── uvicorn 0.30.6
│   ├── fastapi 0.112.1 (*)
│   └── fastapi-cli 0.0.5 (*)
└── markupsafe 2.1.5
└── jinja2 3.1.4
└── fastapi 0.112.1 (*)
python 3.12.5
├── annotated-types 0.7.0
│   └── pydantic 2.8.2 (*)
├── typing_extensions 4.12.2
│   ├── typing-extensions 4.12.2
│   │   ├── annotated-types 0.7.0 (*)
│   │   ├── pydantic-core 2.20.1 (*)
│   │   ├── fastapi 0.112.1 (*)
│   │   └── pydantic 2.8.2 (*)
│   ├── starlette …
```

fix: issue 1839

---

src/cli/has_specs.rs

Parse match specs on the command line in lenient mode.
Fixes #1792

fix: issue 1792

---

src/prefix.rs

This adds context to the error that can occur when files in the conda-meta directory failed to parse.
Fixes https://github.com/prefix-dev/pixi/issues/1744

fix: add context to error when parsing conda-meta files

---

src/task/task_environment.rs
src/task/task_graph.rs

This PR removes the system requirements check for some of the tests. Checking the system requirements is not required for these tests.
Fixes https://github.com/prefix-dev/pixi/issues/1738

fix: dont enfore system requirements for task tests

---

docs/design_proposals/pixi_global_manifest.md

- Add channels
- Add platform
- Override global manifest path via config key rather than env var

docs: extend `pixi global` proposal

---

docs/reference/project_configuration.md

fix(docs): ssh url should not contain colon

---

crates/pixi_uv_conversions/Cargo.toml
crates/pixi_uv_conversions/src/conversions.rs
examples/pypi-find-links/pixi.lock
examples/pypi-find-links/pixi.toml
src/cli/list.rs
src/install_pypi.rs
src/lock_file/resolve/pypi.rs

Fixes #1672 
Uv has fixed that the index location given urls are passed along with the distributions. This allowed us to remove a bunch of code to reconstruct the relative path of packages from flat-indexes.

fix: find links with manifest-path

---

.cargo/config.toml

Fixes #1414 
When running `pixi` in debug mode on windows you would occasionally encounter a `thread 'main' has overflowed its stack`. This PR increases the stack size on windows in debug mode to fix this issue.
As taken from:
https://users.rust-lang.org/t/stack-overflow-when-compiling-on-windows-10/50818/8

fix: increase stack size in debug mode on windows

---

src/project/mod.rs

Fixes #1525 
When solving solve groups with pypi dependencies we create a temporary environment. This directory should be created in `.pixi/solve-group-envs/<name>` however they were accidentally stored in `.pixi/envs/solve-group-envs/<name>`. This might cause a conflict with a environment named `solve-group-envs`.
I also checked that this directory is properly cleaned when running `pixi clean`.
This was also already correctly done when using detached envs.

fix: solve-group-envs should reside in .pixi folder

---

Cargo.toml
crates/pixi_manifest/src/pypi/pypi_requirement.rs
crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_failing.snap
crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_succeeding.snap

Further improves https://github.com/prefix-dev/pixi/issues/1858
Not sure why the formatting is weird but at least it tells you the actual problem:
Custom error:

feat: improve parsing errors of `pypi-dependencies`

---

crates/pixi_config/src/lib.rs
crates/pixi_config/src/snapshots/pixi_config__tests__version_constraints.snap

There was a pinning bug that was caused by versions that did not have 3 segments.
This PR fixes that.
Fixes #1878

fix: pinning logic for minor and major

---

docs/reference/project_configuration.md

After https://github.com/prefix-dev/pixi/pull/1887 . @ruben-arts

docs: Fix linux minimum version in project_configuration docs

---

docs/Community.md

This PR add my project [jslorrma/keyrings.artifacts](https://github.com/jslorrma/keyrings.artifacts) to `Community.md`.
See https://github.com/prefix-dev/pixi/issues/1857#issuecomment-2307470213

docs: add `keyrings.artifacts` to the list of project built with `pixi`

---

src/install_pypi.rs
src/lib.rs
tests/install_tests.rs
tests/satisfiability/old_lock_file/pixi.lock
tests/satisfiability/old_lock_file/pyproject.toml

Fixes:
```
/home/runner/.pixi/bin/pixi install --locked --manifest-path pyproject.toml --color always
thread 'main' panicked at /home/runner/work/pixi/pixi/src/install_pypi.rs:611:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: The process '/home/runner/.pixi/bin/pixi' failed with exit code 101
```

fix: use default indexes if non where given by the lockfile

---

docs/design_proposals/pixi_global_manifest.md

The required `channels` key was missing

docs: Fix global manifest

---

crates/pixi_utils/src/conda_environment_file.rs

Fixes: #1901 
Now gives errors like:
```
× Failed to parse 'env.yml' as a conda environment file
╰─▶ channels: invalid type: string "nodefaults", expected a sequence at line 2 column 11
╭─[env.yml:2:11]
1 │ name: envname
2 │ channels: nodefaults
·           ┬
·           ╰── error occurred here
3 │ dependencies:
╰────
```
```
× Can't parse 'pandas[performance]' as conda dependency
╰─▶ invalid bracket
```

feat: improve the conda env.yml parsing errors

---

src/cli/init.rs

This avoids pixi from adding the deps to the target tables. E.g.:
```toml
#before:
[target.linux-64.dependencies]
x = "*"
[dependencies]
x = "*"
```
And this disables the `install` on import. No idea why we did that but 99% of the time it annoyed me.

fix: `init` don't make the dependencies target specific and don't install

---

crates/pypi_modifiers/src/pypi_tags.rs
tests/install_tests.rs

This boolean was filtering out the creation of manylinux wheel tags.

fix: enable use of manylinux wheeltags once again

---

docs/advanced/authentication.md

Added some short documentation regarding Azure authentication. Could @jslorrma, verify its correctness if you have the chance? Also pulling in @PanTheDev, because I know you wanted to add documentation surrounding this. We can modify/edit as you guys see fit!

docs: document azure keyring usage

---

docs/index.md

fix installation docs:
1. the env var that controls the installed version is `PIXI_VERSION`
2. running
```
PIXI_VERSION=v0.18.0 curl -fsSL https://pixi.sh/install.sh | bash
```
will install the latest version.
the env var needs to on the `bash` that runs the install script

fix(docs): update env variables in installation docs

---

src/cli/add.rs
tests/install_tests.rs

Before:
```
pixi add numpy
pixi add pandas==2.0.1
pixi add numpy panda==2.0.1
```
After this PR
```
pixi add numpy
pixi add pandas==2.0.1
pixi add numpy panda==2.0.1
```

fix: always overwrite when pixi adding the dependency

---

.github/workflows/test_downstream.yml
pixi.lock
pixi.toml
tests/integration/test_main_cli.py

- Use explicit enum for exit codes
- Use modern subprocess usage
- Extend type hints
- Check type hints

refactor: improve integration tests

---

.github/workflows/test_downstream.yml
pixi.toml
tests/integration/test_main_cli.py

- Test locally build pixi, instead of installed one
- Add task `test-integration-dev` with dependency on task `build`
- Use list instead of strings for commands, so that it also works if the paths contain spaces

feat: Improve integration tests

---

src/cli/init.rs
tests/integration/test_main_cli.py

By creating the directory structure hatchling requires
Fixes #1903
Fixes #1941

fix: `pixi init` for `pyproject.toml`

---

scripts/release.py

Make sure that we use the released pixi, not a development version

feat: Improve release script

---

tests/integration/test_main_cli.py

As soon as we implement it, this marker should throw an error

fix: integration tests for pixi global

---

Cargo.lock
Cargo.toml

Bump zip crate from 0.6.6 to current 2.2.0

chore: upgrade zip dependency from alpha to current stable

---

examples/docker/.dockerignore
examples/docker/.gitignore
examples/docker/Dockerfile
examples/docker/README.md
examples/docker/docker-compose.yml
examples/docker/pixi.lock
examples/docker/pyproject.toml

Closes https://github.com/prefix-dev/pixi/issues/1938
I optimized the usage of Docker in various ways:
- update base image pixi version to 0.28.2
- replace `COPY . /app` with more granular `COPY` instructions, which optimizes build cache. Re-running image builds should be much faster.
- add dedicated `RUN --mount=type=cache,... pixi install` instruction, so that conda package downloads are cached.
- add `docker-compose.yml` for building and running the example flask development server
- replace `flit_core` build system with `hatch`

feat: improve examples/docker

---

tests/common/mod.rs

Disables the progress bars for the tests. Because it was overwritting the output a lot, especially when using `cargo t`.

feat: disable progress bars in the tests

---

src/cli/clean.rs

This makes it more consistent with `apt`.

feat: add flag to `pixi search`

---

pixi.lock
pixi.toml

Uses `pytest-xdist` to run tests in parallel.
Saved about 2 seconds for integration tests on my machine.

feat: run pytests in parallel

---

tests/add_tests.rs

Pins the python version in this specific test, so that it keeps working when the platform is added later.

fix: pins python version in add_pypi_functionality

---

.github/workflows/rust.yml

Add back older caching method, at it seems to work much better for uv.
I think github caching got a lot faster again, caching downloding for uv takes about a minute but the runs speed up considerably. So why this seems so much faster I don't really know, when its in I'll add lines to only save the cache in `main` builds from another PR.
We could also start using buildjet: https://github.com/Swatinem/rust-cache/blob/master/.github/workflows/buildjet.yml that gives us a 20G limit instead of 10G.

feat: add back older caching method

---

src/cli/project/export/conda_explicit_spec.rs

This fixes a reference to a flag that was removed from `pixi project export conda-explicit-spec` during the review of PR #1873.

fix: Fix error message for export conda explicit spec

---

docs/reference/cli.md

Hi pixi dev team!
I've tried to install a package in editable mode using the pixi CLI, and by looking at the documentation I've seen:
```bash
pixi add --pypi "project @ file:///absolute/path/to/project" --editable 
```
Executing that I got an error saying:
```
× Expected package name starting with an alphanumeric character, found '@'
│ @
│ ^
```
Trying without spaces around @:
```bash
pixi add --pypi "project@file:///absolute/path/to/project" --editable 
```
it worked.

docs: Update cli.md

---

schema/examples/invalid/bad_feature_platform.toml
schema/model.py
schema/schema.json
schema/test_manifest.py

At present, the following does not raise an error when editing/validating:
```toml
[feature.foo_bar]
platforms = ["garbage"]
```
But does raise an issue when parsed:
```
× failed to parse project manifest
╭─[pixi.toml:10:13]
9 │ [feature.foo_bar]
10 │ platforms = ["garbage"]
·             ─────┬─────
·                  ╰── 'garbage' is not a known platform. Valid platforms are 'noarch', 'unknown', 'linux-32', 'linux-64', 'linux-aarch64', 'linux-armv6l', 'linux-armv7l', 'linux-ppc64le', 'linux-ppc64', 'linux-s390x', 'linux-riscv32', 'linux-riscv64', 'osx-64', 'osx-arm64', 'win-32', 'win-64', 'win-arm64', 'emscripten-wasm32', 'wasi-wasm32', 'zos-z'
╰────
```
This PR: 
Future work (not on this PR):
- the "true" list of platforms is, of course, whatever the rust code (probably `rattler`?) …

fix: constrain feature platforms in schema

---

pixi.lock
pixi.toml
tests/wheel_tests/generate_summaries.py
tests/wheel_tests/helpers.py
tests/wheel_tests/record_results.py

- Move from `toml` to `tomllib` and `toml-w` as recommended by the Python docs: https://docs.python.org/3/library/tomllib.html
- Add an explicit dependency on pytest

refactor: follow-up wheels tests

---

src/cli/tree.rs

Fixes #2043 
Also does some general cleaning up. 
You can test the issue with `cargo run -- tree | head -n 10` Which now doesn't fail anymore

fix: tree print to pipe

---

crates/pixi_manifest/src/pypi/pypi_requirement.rs
crates/pixi_manifest/src/target.rs
schema/examples/valid/full.toml
schema/model.py
schema/schema.json

Fixes the issue in the comment of @evetion in #771: https://github.com/prefix-dev/pixi/issues/771#issuecomment-2346462475
Now you are able to run:
```
pixi add --pypi "ribasim@git+https://github.com/Deltares/Ribasim.git#subdirectory=python/ribasim" 
```

fix: `subdirectory` in pypi url

---

examples/cpp-sdl/CMakeLists.txt

This prevents an empty console to be opened when we launch this program from Windows Explorer.
Note that this change makes `std::cout` not work anymore (if launched from a console). This is fixed in a separate PR: https://github.com/prefix-dev/pixi/pull/2070.

fix: create a GUI application on Windows, not Console

---

src/cli/init.rs

fixes: #2066 
```bash
$ pixi init --format pyproject test-project
$ tree test-project
test-project/
├── pyproject.toml
└── src
└── test_project # <<<< This is now an underscore
└── __init__.py
```

fix: make dashes underscores in python package names

---

docs/reference/cli.md
src/cli/upload.rs

From what understand eventually the pixi upload UX will be improved (see https://github.com/prefix-dev/pixi/issues/248), in the meanwhile I think it is useful to fix the existing documentation to simplify its use. 
Following the docs, I obtained some enigmatic errors, until I found https://github.com/prefix-dev/pixi/issues/248 that contained the right endpoint to call.

fix: Change documentation of pixi upload to refer to correct API endpoint

---

crates/pixi_manifest/src/error.rs
src/cli/config.rs
src/cli/shell.rs
src/project/mod.rs

You'll now get:
```
$ pixi install
× failed to parse project manifest
╭─[pyproject.toml:18:12]
17 │ 
18 │ [tool.pixi.pypi-depenencies]
·            ────────┬───────
·                    ╰── unknown field `pypi-depenencies`, expected one of `project`, `system-requirements`, `target`, `dependencies`, `host-dependencies`, `build-dependencies`, `pypi-dependencies`, `activation`, `tasks`, `feature`, `environments`, `pypi-options`, `tool`, `$schema`
19 │ test_init = { path = ".", editable = true }
╰────
```
instead of:
```
❯ ~/.pixi/bin/pixi i
× could not find pixi.toml or pyproject.toml which is configured to use pixi
```

fix: give better errors on broken `pyproject.toml`

---

pixi.toml
tests/integration/common.py
tests/integration/test_main_cli.py

- Move helper functions to own file
- Use physical rather than logical CPU cores for parallel runs
- Add verbose flag when running on CI, which makes it much easier to debug failures

refactor: integration test suite

---

.github/workflows/rust.yml
.github/workflows/test_downstream.yml

- Typecheck takes 22 s on linux and 3 minutes on Windows. One platform is enough, so let's only run it on linux
- Adapt the naming of the workflow

ci: downstream test improvement

---

docs/design_proposals/pixi_global_manifest.md

- binaries -> executables
- PACKAGE_NAME -> PACKAGE

docs: adapt wording in pixi global proposal

---

src/cli/project/export/conda_environment.rs
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_pyproject_panic.snap
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_with_defaults.snap
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_with_pip_custom_registry.snap
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_with_pip_extras.snap
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_with_pip_find_links.snap
src/cli/project/export/snapshots/pixi__cli__project__export__conda_environment__tests__test_export_conda_env_yaml_with_source_editable.snap

Adding `nodefaults` as a channel to the conda environment yaml's after `pixi project export conda-environment`. 
Idea tipped in https://github.com/prefix-dev/pixi/issues/2089

feat: add nodefaults to conda envs

---

.github/workflows/rust.yml
scripts/release.py

This will fix the issue that we don't build `msi` installers.

fix: always fetch the release version

---

docs/design_proposals/pixi_global_manifest.md

This describes this recently added [functionality](https://github.com/prefix-dev/pixi/pull/1980) and how it could be added to the new `pixi global`
@183amir

docs: `pixi global` mention `no-activation`

---

crates/pixi_build_types/src/procedures/conda_build.rs
src/build/mod.rs
src/cli/build.rs
src/cli/mod.rs

Adds a very initial version of the `pixi build` cli command. 
This is far from perfect but serves as the basis for adding more features.

feat: `pixi build` cli

---

.pre-commit-config.yaml
pixi.toml

Changed it so that `pixi run lint` will run the cargo parts to. And so that you also format before committing.

fix: run cargo clippy on push and on pixi lint task

---

Cargo.lock
Cargo.toml
src/global/common.rs
src/global/install.rs
src/global/project/manifest.rs
src/global/project/mod.rs

This just refactors the code to use `fs_err` instead of `std::fs` or `tokio::fs` resulting in the removal of the `.wrap_err`s.
I also changed the `sync` function to have more situation where the env is updated

feat: `fs_err` in `pixi global`

---

Cargo.lock
Cargo.toml
crates/pixi_build_frontend/src/protocols/conda_build/mod.rs
crates/pixi_build_frontend/src/protocols/conda_build/protocol.rs
crates/pixi_build_types/src/conda_package_metadata.rs
crates/pixi_glob/src/glob_hash_cache.rs
crates/pixi_record/Cargo.toml
crates/pixi_record/src/source_record.rs
pixi.lock
pixi.toml
src/build/mod.rs
src/build/source_metadata_cache.rs
src/lock_file/update.rs

This PR adds a source metadata cache that caches the response from `conda/getMetadata`.

feat: add a source metadata cache

---

docs/design_proposals/pixi_global_manifest.md

`pixi global install --environment ENV` should also work if `ENV` already exists

docs: Update global manifest `install`

---

src/task/file_hashes.rs

I am using `pixi` with detached environments. I have a `postinstall` task that runs `pip install --no-build-isolation --no-deps --disable-pip-version-check -e .`. I want to specify an output for this task that checks if the package is installed in `.pixi/envs/defaults/...` so that I can cache this task. This currently fails because the Walker used does not follow symlinks, and `.pixi` just points to my detached environments via a symlink. This PR enables resolving symlinks and adds a test for that.

feat: Follow symlinks while walking files

---

pixi.toml
scripts/install.py

Add a script which installs pixi to `~/.pixi/bin`. Now, people only need pixi, not Rust to install a developer version of pixi. Also the script allows to give pixi a different name, per default `pixid`

feat: add `pixi run install-as`

---

Cargo.lock
Cargo.toml
src/cli/self_update.rs

`self-update` checks if the Pixi binary matches the default filepath. Instead of checking if paths are equal, we should check if files are same in `self-update`.
This should resolve this issue:
```
× pixi is not installed in the default location:
│ 
│ - Default pixi location: /users/apoorvkh/.pixi/bin/pixi
│ - Pixi location detected: /nfs/home/apoorvkh/.pixi/bin/pixi
```
which could be caused by using symlinks or case-insensitivity in Windows, etc.
Fixes #1171 and maybe #2059

fix: check if files are same in `self-update`

---

Cargo.lock
Cargo.toml

This PR bumps `rattler_solve` which bumps `resolvo` which includes two important [performance](https://github.com/mamba-org/resolvo/pull/67) [improvements](https://github.com/mamba-org/resolvo/pull/66). This should significantly reduce the number of cases where the solver takes a very long time to solve (minutes plus).
This benchmark image taken [from resolvo](https://github.com/mamba-org/resolvo/pull/67#issuecomment-2382370118) shows that the number of cases that take more than 60 seconds is significantly decreased.

perf: significantly speed up conda resolution

---

crates/pixi_manifest/src/manifests/mod.rs

I've noticed that we have no tests for manifests, so I added one for now.

test: add manifest test

---

src/global/common.rs
src/global/project/mod.rs

The fix is that the pruning function now takes care of both the environment and the binaries at the same time.

fix: also remove binaries of pruned environments

---

src/cli/global/install.rs
src/global/project/manifest.rs
src/global/project/snapshots/pixi__global__project__manifest__tests__add_dependency.snap

Now `pixi global install python=3.11.0=h10a6764_1_cpython` results in:
```toml
[envs.python.dependencies]
python = { version = "==3.11.0", build = "h10a6764_1_cpython" }
````

fix: going from matchspec to pixispec and into toml value

---

install/install.sh

- Exported paths for Bash and ZSH are now surrounded by double quotes, which is necessary to avoid breaking user systems where the existing `PATH` contains spaces.
- The `PIXI_HOME` environment variable now resolves incoming `~/` prefixes to the actual user's `$HOME` value. Otherwise we would generate invalid paths, since `~/` is not a valid prefix in `PATH`. It also fixes the fact that the old code installed into a literal sub-directory of the current working dir, named `~/.pixi` (a literal `~`), instead of into the user's home directory, whenever users tried to provide a custom `env PIXI_HOME=~/.pixi` variable themselves.
- We now use double quotes around all variables. This is required for two reasons. It ensures that arguments with spaces are supported. And it prevents Bash from …

fix: improve install.sh PATH handling and general robustness

---

src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/global/install.rs
src/global/project/mod.rs
tests/integration/test_global.py

- Use long form CLI commands. They are preferable in scripts and docs.
- Require parameter `packages`
- Use `HasSpecs` trait
- Fail if environment doesn't exist
- Use `environment_prefix` in more places
- Take ownership of `env_name` in `environment_prefix`
- Use stderr for messages as described in https://clig.dev/#the-basics
- Adapt mapping docs
- Dropped `global` namespace in integration test naming for consistency
- Extended integration tests

refactor: `pixi global add` follow up

---

src/task/file_hashes.rs

Unfortunately the `.follow_links(true)` created some issues. The idea is to completely redo the file search logic but for now we turn of the breaking option. 
Closes #2196 #2205

fix: turn off symlink follow for task cache

---

crates/pixi_consts/src/consts.rs
src/cli/global/expose.rs
src/cli/global/list.rs
src/cli/global/uninstall.rs
src/cli/global/update.rs
src/global/common.rs
src/global/install.rs
src/global/project/environment.rs
src/global/project/manifest.rs
src/global/project/mod.rs
src/global/project/parsed_manifest.rs
src/global/project/snapshots/pixi__global__project__parsed_manifest__tests__duplicate_exposed.snap
tests/integration/test_global.py

- `pixi global expose remove` doesn't need `--environment` flag anymore
- Move to fancy display for exposed name

feat: improve expose

---

src/cli/global/uninstall.rs
src/global/project/mod.rs
tests/integration/test_global.py

This fixes the situation where we removed environments that were removed from the manifest on `pixi global uninstall` but it should only uninstall the requested environments.

fix: only uninstall single specified environments, only cleanup on sync

---

docs/tutorials/python.md

File tree characters, typo, and (subjectively) clearer wording in one section

docs: small fixes in tutorials/python.md

---

src/cli/global/list.rs
src/cli/info.rs
src/global/project/mod.rs

Adds the following to `pixi info`:
Adds manifest path to `pixi global list`:
Ps. who uses light theme :vampire:

feat: improve debugablity global

---

src/cli/global/mod.rs
src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs

Users will get an error message when they attempt to use `pixi global upgrade` or `pixi global upgrade-all`

feat: Re-add `pixi global upgrade`

---

crates/pixi_manifest/src/feature.rs
crates/pixi_manifest/src/features_ext.rs
crates/pixi_manifest/src/has_environment_dependencies.rs
crates/pixi_manifest/src/lib.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/target.rs
src/cli/info.rs
src/cli/list.rs
src/cli/project/export/conda_environment.rs
src/cli/tree.rs
src/cli/update.rs
src/lock_file/satisfiability.rs
src/lock_file/update.rs
src/project/environment.rs
src/project/grouped_environment.rs
src/project/mod.rs
src/project/snapshots/pixi__project__tests__dependency_set_with_build_section.snap
src/project/solve_group.rs
tests/add_tests.rs
tests/project_tests.rs

This PR removes the default behavior that `host-dependencies`, `build-dependencies`, and `dependencies` are combined. This only happens when the project contains a `[build]` section.
Builds on #2251

feat: don't combine build, host, and run when there is a build section

---

docs/reference/cli.md
src/cli/config.rs
src/cli/global/edit.rs

Fixes on windows:
```
pixi global edit code
```
Aligns `edit` cli:
```
pixi config edit -g code
```

fix: edit cli on windows and for both config and global

---

pixi.toml
src/cli/global/list.rs
tests/integration/test_global.py

Add optional `regex` argument for both` pixi global list` and `pixi global list --environment env-name`.
If passed regex string is not a regex syntax, but a simple string - it will act as a contains filter.
Some examples:
Having `nushell`, `python`, `python3-10` as enviroments
`pixi global list py`
`pixi global list --environment python lib`

feat: add pixi global list filter

---

src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/sync.rs
src/cli/global/uninstall.rs
src/cli/global/update.rs
src/global/common.rs

https://github.com/clap-rs/clap/issues/4507#issuecomment-1372250231
`num_args = 1.. ` don't make packages a mandatory argument.
This PR aims to fix this, and some other stylistic usage of report instead of computing println message

fix: pixi global required args

---

src/cli/project/environment/add.rs
tests/common/mod.rs

fixes: https://github.com/prefix-dev/pixi/issues/2245
Now parses the environment name

fix: parse env name on adding

---

tests/integration/test_global.py

fix: skip `test_pixi_install_cleanup`

---

Cargo.toml
crates/pixi_utils/src/reqwest.rs

Adding gcs auth middleware to pixi
Would need to test it, but currently blocked by : https://github.com/prefix-dev/pixi/issues/1922

feat: Add support for `gcs://` conda registries

---

src/cli/global/upgrade.rs
src/cli/global/upgrade_all.rs

fix: `pixi global upgrade-all` error message

---

src/cli/run.rs
tests/integration/test_main_cli.py
tests/integration/test_run_cli.py

Fixes: #2299 
Also adds a pytest for this, decided to move it into a pytest as it took me 5 minutes which is much faster. Feel a bit burned by our rust integration test setup, mostly because of the slow compile times for changing text.

fix: select correct run environment

---

docs/features/global_tools.md

I also removed the note that the desing of global tools is still in progress

docs: document where `pixi-global.toml` can be found

---

.github/workflows/rust.yml
.github/workflows/test_downstream.yml

Especially macOS runners tend to hang.
As far as I can tell 30 minutes should be enough.

ci: add timeouts

---

.github/workflows/test_common_wheels.yml
.github/workflows/test_downstream.yml
.gitignore
pixi.toml
pytest.ini
scripts/activate.bat
scripts/activate.sh
tests/integration/conftest.py
tests/wheel_tests/test_common_wheels.py

- specify `basetemp` for pytest
- this avoids the problem that `/tmp` is filling up on Linux which can make problems
- it is also more convenient to inspect test artifacts
- move target directory from `.pixi/target` to `pixi-target`
- `setup-pixi` caches the whole `.pixi` which is something we sometimes want to avoid for target

ci: adapt test directories

---

docs/advanced/authentication.md

- Improve the pypi authentication documentation to use pixi global rather than pipx.
- Reformat the documentation to use tabs (one tab per registry), hopefully making the documentation clearer, and easier to extend with other registries.

docs: Improve keyring documentation to use pixi global

---

.github/workflows/test_downstream.yml
.pre-commit-config.yaml
pixi.toml
tests/pypi_proxy.py
tests/run_all_examples.py
tests/wheel_tests/conftest.py
tests/wheel_tests/generate_summaries.py
tests/wheel_tests/helpers.py
tests/wheel_tests/read_wheels.py
tests/wheel_tests/record_results.py
tests/wheel_tests/test_common_wheels.py
tests/wheel_tests/test_read_wheels.py

- typecheck all tests
- fix type hints
- move typecheck to pre-commit

test: typecheck all tests

---

src/repodata.rs

I've observed that we are using two different ways to initialise the package cache for query repodata and installing.
I think it would be nice to do it in the same way, so we can respect PIXI_CACHE_DIR

feat: use the same package cache folder

---

examples/pybind11/pixi.lock
examples/pybind11/pyproject.toml

It is much faster than the `build` Python package; `uv` is written in Rust so it makes sense.

docs: Replace build with uv in pybind11 example

---

crates/pixi_manifest/src/task.rs

For quote escaping strings, use built in contains method to find presence of special characters, and put characters directly into (pre allocated) String, instead of vector of bytes, that is then cast into a string.

refactor: use built in string methods

---

crates/pixi_consts/src/consts.rs
docs/packaging.md
src/cli/mod.rs
tbump.toml

feat: Allow to specify custom version during build

---

crates/barrier_cell/src/lib.rs

As OnceLock is now in std, reimplement BarrierCell with the OnceLock primitive (simplifying the unsafe code to one instance, and making it easier to maintain)

refactor: reimplement barrier cell on OnceLock

---

src/environment.rs
tests/install_tests.rs

Closes #2115
**Implementation note**: I wasn't so sure where's the best location in the code to create `.pixi/.gitignore`, and I ended up adding it to the `sanity_check_project` part of `update_prefix`. This means that `.pixi/` will be created slightly more eagerly than before (e.g. if there aren't yet any environments defined). Please let me know in case there's a better way.
**Brief why?**: Adding a `.gitignore` under `.pixi/` has the advantage that `.pixi/` will be ignored in a self-contained way without requiring modification of the project-level `.gitignore`. This ignore is mostly redundant with the rule defined in `GITIGNORE_TEMPLATE`, but retaining them both for the moment ensures that edge cases are better handled. See the discussion in …

feat: Create `.pixi/.gitignore` containing `*`

---

pixi.toml
src/lock_file/satisfiability.rs
tests/install_tests.rs
tests/integration/conftest.py
tests/integration/test_global.py
tests/integration/test_main_cli.py
tests/solve_group_tests.rs

- Mark more tests as slow
- Use debug-build for integration tests
- Add `test-integration-fast` and `test-all-fast` for running a great subset of tests without waiting too long

ci: speed up test workflow

---

src/cli/global/install.rs

Stop reporting state changes for `pixi global install`.
We already have the list view for that.

feat: improve global install reporting

---

src/cli/task.rs

Description
**Issue**:
- explicitly requesting tasks for a specific environment with the `--environment` flag, along with the `--summary (-s)` flag, would also display tasks available in other environments. 
<details>
<summary> before fix: </summary>
current `pixi task ls --summary` 
</details>
**Fix**:
- A new `env_task_map` was introduced, which either maps the explicitly requested environment (if specified) or iterates over all environments, filtering based on platform compatibility.
- Removed the `get_tasks_per_env` function, but could extract the new logic back out into it
- Tried to prevent iterating over `projects.environments()` again 
<details>
<summary> after fix: </summary>
regular `task ls --summary` still works:
`pixi task ls` with no args unaffected:
</details>

fix: --environment with --summary displaying unrequested environments

---

install/install.sh

`--no-progress-meter` was "only" added in 7.67, but centOS 7 only ships til 7.29. Prevents errors in conda-forge's Docker infra.

fix: use `--silent` instead of `--no-progress-meter` for old `curl`

---

src/project/environment.rs

Implement https://discord.com/channels/1082332781146800168/1082338253925003385/1303730191054671913
```
LAPTOP in conda-recipes on  main [?] via 🐍 v3.13.0
❯ ..\pixi\target\debug\pixi.exe i
WARN win-arm64 is not supported by the pixi.toml, falling back to win-64 (emulation)
✔ The default environment has been installed.
```
Thanks @wolfv for the insight!

feat: add platform fallback win-64 for win-arm64

---

src/cli/task.rs

`task list` was not displaying when targets were specified
**manifest-path**
```toml
[project]
channels = ["https://fast.prefix.dev/conda-forge"]
name = "pixi"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
[tasks]
make.cmd = "command_1"
generate_keymap.cmd = "command_2"
svg.cmd = "command_3"
[target.osx.tasks]
flash.cmd = "command_4"
port.cmd = "command_5"
port_right.cmd = "command_6"
```
**before**
```console
> pixi task --manifest-path target/pixi.toml ls -s
Tasks per environment:
----------------------
default: generate_keymap, make, svg
```
**after**
```console
> pixi task --manifest-path target/pixi.toml ls -s
Tasks per environment:
----------------------
default: flash, generate_keymap, make, port, port_right, svg
```

fix: ensure tasks are fetched for the best platform

---

README.md

It shows failing builds even if they are only skipped

docs: remove badge

---

docs/tutorials/python.md

Update Python tutorial to accommodate change where `init` already adds the python project.
See https://github.com/prefix-dev/pixi/issues/2451

docs: update Python tutorial

---

src/environment.rs

Fix #2450
This PR tolerate error when creating pixi file. This allow to run `shell` and `shell-hook` on read-only filesystem

feat: tolerate pixi file error

---

src/global/trampoline.rs

fix: attempt copying trampoline when hard-linking fails

---

docs/tutorials/ros2.md

Great quick start - here a couple small suggestions from a fresh set of eyes!
Also, the turtlesim image link is broken. I can add this image 
to fix it - where in the repo should such an asset be stored?

docs: Update ros2.md turtlesim section

---

examples/python-library-gcp-keyring/pixi.lock
examples/python-library-gcp-keyring/pyproject.toml

This adds a dependencies that can only be taken from the remote to test if that works correctly. 
Found issues:
- This only works if the user sets up a keyring provider and then tells pixi to use that. The error could be more helpful by improve the error msgs.
- Satifiablity works for both path versions and actual versions which should not satisfy in my opinion, it should redownload from the index if the user replaces `package = {path = "."}` to `package = "*"`

fix: add use of gcp pypi package in example

---

src/cli/upgrade.rs

Description was duplicate from `update`, it now reflects what it's supposed to do (unless I misunderstood what it does)

fix: wrong description on pixi upgrade

---

Cargo.lock
Cargo.toml
crates/pixi_config/Cargo.toml
crates/pixi_config/src/lib.rs
crates/pixi_config/src/snapshots/pixi_config__tests__config_merge.snap
crates/pixi_spec/src/lib.rs
crates/pixi_utils/src/snapshots/pixi_utils__conda_environment_file__tests__test_import_from_env_yaml.cockpit.yml.snap
docs/reference/pixi_configuration.md
src/cli/exec.rs
src/lock_file/satisfiability.rs

Enables sharded repodata for specific channels.
Add:
```toml
[repodata-config."https://prefix.dev"]
disable-sharded = false
```
To your global config to not disable sharded repodata for all prefix channels. The double negation is there because in the future we might want to enable sharded repodata by default.
This PR is in draft because https://github.com/conda/rattler/pull/910 needs to be merged first.
@ruben-arts is there a good place to add this to the documentation?

feat: allow using sharded repodata

---

tests/data/pixi_tomls/python_mismatch.toml
tests/integration_python/test_edge_cases.py
tests/integration_python/test_run_cli.py

This adds a test for #2481.
cc @nichmor @hameerabbasi
Also moved previous regression to  the same file.

test: extra test for mismatch in python versions

---

crates/pixi_manifest/src/build.rs
src/project/mod.rs

This PR aims to make easier to integrate isolated build tools https://github.com/prefix-dev/pixi/pull/2479 .
After merging we can also refer to `feature/pixi-build` from pixi-build-backend tools, so it will not fail on deser when reading manifest with `channels` field

feat: add channels for build section

---

docs/tutorials/python.md

When running through the tutorial I saw a different output message. Looks like it changed here https://github.com/prefix-dev/pixi/pull/1413

docs: update pixi install output

---

crates/pixi_config/src/lib.rs
tests/integration_python/test_main_cli.py

If one of the configs is broken, that's the warning I get with this branch

fix: always print a warning when config is invalid

---

src/global/project/manifest.rs
tests/integration_rust/init_tests.rs

When I changed the defaults-channel in my config some tests stopped working.
I've adapted `test_add_dependency` accordingly.
I didn't manage to adapt `default_channel` so that it would stop parsing the local config

test: make pixi tests work with local config

---

crates/pixi_utils/src/executable_utils.rs

For comparison purposes we were always lower-casing the executable name. However, we also returned the lowercase version and exposed executables as lowercase which doesn't match user expectations.
With this PR we are instead returning the original case. 
I cannot judge if this affects current exposed binaries. However, I assume we would just keep the lower-case exposed binary as written in the global manifest and only change newly installed tools.
fixes https://github.com/prefix-dev/pixi/issues/2478

fix: keep the case when getting the executable

---

pixi.lock
pixi.toml

This should help us identify which test is to blame for the macOS failures

test: timeout when integration tests take too long

---

docs/switching_from/conda.md

Hi all,
Just a minor fix regarding the example of exporting a Pixi environment to Conda.

docs: Fix typo in pixi export conda-enviroment

---

crates/pixi_build_frontend/src/protocols/pixi/mod.rs
crates/pixi_build_frontend/src/tool/cache.rs
crates/pixi_build_frontend/src/tool/spec.rs
crates/pixi_build_frontend/tests/snapshots/diagnostics__missing_backend.snap
examples/cpp-sdl/pixi.lock
src/build/mod.rs
tests/integration_python/conftest.py

Fix failing CI after *happily* merging isolated tools in `feature/pixi-build`.
This introduced 2 regression:
* unupdated `cpp_sdl/pixi.lock`.
* a missing correct error when user defined only build command without dependencies.

fix: CI for feature/pixi-build

---

pixi.toml

The hope is that either we don't see tests timing out anymore, at least see them consistently timing out

ci: stop running integration tests in parallel

---

crates/pixi_build_frontend/src/protocols/pixi/mod.rs
crates/pixi_build_frontend/src/protocols/pixi/protocol.rs
crates/pixi_build_frontend/src/tool/spec.rs
crates/pixi_build_frontend/tests/basic/pixi.toml
crates/pixi_build_frontend/tests/diagnostics.rs
crates/pixi_manifest/src/build_system.rs
crates/pixi_manifest/src/has_environment_dependencies.rs
crates/pixi_manifest/src/lib.rs
crates/pixi_manifest/src/manifests/manifest.rs
crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__invalid_key.snap
crates/pixi_manifest/src/manifests/workspace.rs
crates/pixi_manifest/src/validation.rs
examples/cpp-sdl/pixi.lock
examples/cpp-sdl/pixi.toml
examples/flask-hello-world-pyproject/pyproject.toml
examples/flask-hello-world/pixi.toml
schema/examples/valid/full.toml
schema/model.py
schema/schema.json
src/project/mod.rs

We decided to rename `[build]` to `[build-system]`. This change takes care of that.
I also took the liberty to remove most `alias`es from `model.py` and use an `alias_generator` instead. Less code is better!

refactor: rename `[build]` to `[build-system]`

---

install/install.ps1

This PR changes the powershell installation script to read the current architecture from the system and download the best matching pixi build.
I tested it by running the script locally and I have a working `win-arm64` pixi running now. 👍

fix: install on win-arm64

---

docs/reference/cli.md

Not sure if I am missing something obvious, but the `conda-environment` and `conda-explicit-spec` are without underscores.

docs: Fix wrong use of underscores in pixi project export

---

README.md
docs/index.md

We currently give people a one-liner to setup completions.
That is convenient, but also fragile.
If people's startup script doesn't end in a newline, it [breaks](https://github.com/panel-extensions/copier-template-panel-extension/issues/4#issuecomment-2495774437).
If people run it multiple times it will be duplicated.
Let's follow https://starship.rs and give users instructions to add it themselves

docs: adapt completion instructions

---

crates/pixi_build_frontend/src/build_frontend.rs

Removing some debug epritln output.
Other output should be removed only after we upgrade rattler-build here https://github.com/prefix-dev/pixi-build-backends/blob/main/Cargo.toml#L34 to rattler-build/main, which I currently cannot do due to some compiler errors when doing upgrade.

fix: remove debug output

---

src/global/list.rs
tests/integration_python/global/test_global.py

fix: `pixi global list` failing for empty environments

---

crates/pixi_build_frontend/src/protocol.rs
crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs

This adds some "fallback" behavior if a recipe.yaml is found but no `pixi.toml` next to it. 
We just default to the `pixi-build-rattler-build` backend. 
I am currently testing with:
```toml
[project]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "Add a short description here"
name = "build-recipe"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]
[package]
[build-system]
dependencies = []
build-backend = "bla"
channels = [
"https://prefix.dev/pixi-build-backends",
"https://prefix.dev/conda-forge"
]
[tasks]
[dependencies]
bzip-two = { path = "./recipes/bzip-two" }
```
and a `recipe.yaml` that looks like:
```yaml
package:
name: bzip-two
version: 1.0.8
```

feat: build recipe yaml directly

---

src/lock_file/satisfiability.rs
src/project/mod.rs
tests/integration_rust/add_tests.rs

Fixes #2574.
I added a test as well, but I'm not sure if it follows the project's standards.

fix: ensure pinning strategy is not affected by non-semver packages

---

src/cli/global/sync.rs
src/global/project/mod.rs
tests/integration_python/global/test_global.py

feat: let `pixi global sync` collect errors rather than returning early

---

src/install_pypi.rs

So @ruben-arts found out that we were installing the prefix too often, this came in with the uv upgrade that we re-introduced in a previous PR.
So I think some bugginess was introduced to fix some lifetime issues, basically from what I was reading it was just installing even though the distributions were already installed.
I've did a long-standing refactor that I wanted to do, that you actually get a reason why a reinstall is happening, which is often tricky to debug. 
I've also fixed the bug, cleaned up a lot of the debug statements so they make actual sense and report a lot more in general. Also, because of the new structure we can more directly tell why a reinstall happened because of keeping track of this as a a cause.
I've tested the following manual steps on rerun.io pixi toml:
I …

fix: pypi installs happening every time

---

crates/pixi_build_frontend/src/tool/cache.rs
crates/pixi_config/src/lib.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/snapshots/pixi_manifest__pyproject__tests__add_pypi_dependency.snap
crates/pixi_manifest/src/snapshots/pixi_manifest__pyproject__tests__remove_pypi_dependency.snap
crates/pixi_utils/src/cache.rs
crates/pixi_utils/src/conda_environment_file.rs
src/activation.rs
src/build/mod.rs
src/cli/exec.rs
src/environment.rs
src/global/project/parsed_manifest.rs
src/lock_file/update.rs
tests/integration_rust/common/builders.rs
tests/integration_rust/common/mod.rs
tests/integration_rust/install_tests.rs
tests/integration_rust/pypi_tests.rs
tests/integration_rust/solve_group_tests.rs

I couldnt run some tests on my local arm64 windows machine because some packages are not available for arm64 (yet). 
I added a platform to the toolcache to allow installing tools for other platforms than the current one. 
I also found that the toolcache was instantiated on each build invocation which effectively removes all caching. 
Finally I sped up the toolcache tests by using sharded repodata and changing the tool that was installed to something more lightweight.
@nichmor This touches some of your code, please review.

fix: improve test speed and support win-arm64

---

CONTRIBUTING.md
scripts/install.py

Found this script useful while working on features for other tooling, i use PIXI_HOME for my binaries so this feature helps write it to the same location. 
+ also wanted to describe how to use it for other devs looking to contribute
- Refactor the installation script to support specifying a custom destination for executables and add logging for better visibility. 
- Update CONTRIBUTING.md to include instructions for the new installation method.

refactor: Enhance installation script with custom destination and update documentation

---

docs/Community.md

My project no longer uses `pixi`. Therefore, I'd like to remove it from the community page.

docs: remove `tclf` from community.md📑

---

crates/pixi_build_frontend/src/build_frontend.rs
crates/pixi_build_frontend/src/lib.rs
src/build/mod.rs
src/cli/build.rs

This allows us to set a `PIXI_BUILD_BACKEND_OVERRIDE=/foo/bar/...` so that we can test more easily.

feat: (simple) build tool override

---

pixi.toml

Adds `--all-targets`.
Adding `--all` isn't necessary since it is a deprecated alias for `--workspace`

fix: pixi test tasks

---

src/cli/mod.rs

Text printed to stdout by pixi has colors even when stdout is redirected to a pipe or file. For example:
> $ pixi list | xxd -l 64
> 00000000: 1b5b 316d 5061 636b 6167 651b 5b30 6d20  .[1mPackage.[0m
It is a common feature for command-line tools to automatically detect if stdout is a pipe or file and disable colors. And in fact pixi uses the crate `console` for color formatting which has built-in support for detecting if stdout and stderr are terminals and automatically disabling color output, so this should work.
However pixi does its own color management which overrides how `console` manages color styling. Pixi checks if _only_ stderr is a terminal, and based on that overrides `console` handling of stdout and stderr. Thus causing stdout to be color formatted when stdout is redirected to …

fix: color formatting detection on stdout

---

.github/workflows/release.yml
Cargo.toml

This PR removes the generation of release artifacts on every PR.

chore: skip building release artifacts on pr

---

crates/pixi_build_frontend/src/build_frontend.rs
crates/pixi_build_types/src/procedures/conda_build.rs
crates/pixi_build_types/src/procedures/conda_metadata.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/toml/workspace.rs
crates/pixi_manifest/src/workspace.rs
schema/model.py
schema/schema.json
src/build/mod.rs
src/cli/build.rs
src/lock_file/update.rs

This adds a new field: `[workspace.build-variants]`.

feat: add variant config to workspace

---

crates/pixi_manifest/src/manifests/source.rs

I need to expose these public methods so I could access manifest table from pixi-build-backend.
necessary for this PR: https://github.com/prefix-dev/pixi-build-backends/compare/main...nichmor:pixi-build-backends:fix/add-entry-points-in-recipe?expand=1

feat: expose some public API

---

tests/integration_python/pixi_global/test_global.py

I am not exactly sure what is going on here, but `xz` is now read as `xz-tools` when migrating

fix: `test_sync_migrate`

---

pytest.ini
src/build/mod.rs
src/lock_file/update.rs
tests/data/pixi_build/simple-pyproject/.gitignore
tests/data/pixi_build/simple-pyproject/pixi.lock
tests/data/pixi_build/simple-pyproject/pyproject.toml
tests/data/pixi_build/simple-pyproject/src/simple_pyproject/__init__.py
tests/integration_python/pixi_build/test_build.py

This way the environment cache is only used if there are no source dependencies in the lock file.

fix: pixi build trigger rebuild

---

install/install.sh

And suggest a known work-around for Windows.

docs: add broken curl version check in install.sh

---

crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__build_variants-2.snap
crates/pixi_manifest/src/manifests/snapshots/pixi_manifest__manifests__workspace__tests__build_variants.snap
crates/pixi_manifest/src/manifests/workspace.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/toml/workspace.rs
crates/pixi_manifest/src/workspace.rs
src/build/mod.rs

Adds support for the "`.target`" on the workspace object. 
We then merge the variants (more specific one should win). E.g.:
```
[workspace.build-variants]
foo = ["1.0"]
[workspace.win-64.build-variants]
foo = ["2.0.* *_win"]  # wins on Windows
```

feat: add target to workspace `[workspace.target.win-64.build-variants]`

---

tests/scripts/test-examples.sh

It fails on CI, but @tdejager and I cannot reproduce the error locally

test: stop testing rich example

---

pixi.toml

We hoped that this would avoid osx freezing, but it didn't

test: run tests in parallel again on CI

---

crates/pixi_utils/src/reqwest.rs

We expect that `native-tls` is still used for `reqwest` and that this is the reason we see this error message on CI on Windows
```
Failed to resolve dependencies: error sending request for url (https://prefix.dev/conda-forge/noarch/repodata_shards.msgpack.zst)
Diagnostic severity: error
Caused by: An existing connection was forcibly closed by the remote host. (os error 10054)
Caused by: client error (Connect)
Caused by: error sending request for url (https://prefix.dev/conda-forge/noarch/repodata_shards.msgpack.zst)
```

fix: enforce rust-tls for reqwest

---

Cargo.lock
Cargo.toml
crates/pixi_build_frontend/Cargo.toml
crates/pixi_build_frontend/src/tool/cache.rs
src/cli/mod.rs
src/cli/run.rs
src/global/install.rs
src/global/project/environment.rs
src/global/project/mod.rs
src/install_pypi/mod.rs
src/lock_file/update.rs
src/lock_file/utils.rs
src/prefix.rs
src/task/executable_task.rs

This PR tries to implement a better IO concurrency using https://github.com/conda/rattler/pull/980 . We have to test whether this improves performance before merging.

fix: reduce io concurrency

---

Cargo.lock
crates/pixi_config/Cargo.toml
crates/pixi_config/src/lib.rs

Fixes # 2720
We used to log on debug level when we couldn't parse a config file

fix: log config parsing errors as errors

---

docs/reference/cli.md
src/cli/run.rs
src/task/task_graph.rs
tests/integration_rust/common/mod.rs

I built this because I agree with #2740 
Fixes #2740 
Allows the user to skip the `depends-on` of a task by running:
```
pixi run --skip-deps task-name
```

feat: skip dependencies of a task

---

crates/pixi_manifest/src/snapshots/pixi_manifest__system_requirements__tests__serialization.snap
crates/pixi_manifest/src/snapshots/pixi_manifest__system_requirements__tests__serialization_other_family.snap
crates/pixi_manifest/src/system_requirements.rs
src/cli/info.rs

This allows us to add it to `pixi info` which I did:
```
Environment: img2txt
Features: img2txt, img2txt_base
Solve group: img2txt
Channels: pytorch, conda-forge, bioconda, anaconda
Dependency count: 1
Dependencies: python
PyPI Dependencies: paddlepaddle, layoutparser, easyocr
Target platforms: win-64, linux-aarch64, osx-arm64, osx-64, linux-64
System requirements: cuda = "12"
libc = "2.27"
```            
Printing only if it is defined by the user

feat: serialize system requirements

---

Cargo.lock
Cargo.toml

After running:
```
pixi add rust scipy
```
This is the result, `pixi` is this branch vs the latest release. On `osx-arm64`
```
hyperfine -p "pixi clean" "pixi install" "pixi39_3 install" -r 5
Benchmark 1: pixi install
Time (mean ± σ):      2.558 s ±  0.116 s    [User: 0.432 s, System: 1.895 s]
Range (min … max):    2.400 s …  2.651 s    5 runs
Benchmark 2: pixi39_3 install
Time (mean ± σ):     12.199 s ±  0.700 s    [User: 4.337 s, System: 44.407 s]
Range (min … max):   11.053 s … 12.887 s    5 runs
Summary
pixi install ran
4.77 ± 0.35 times faster than pixi39_3 install
```

chore: update rattler for macOS speedup

---

README.md
docs/index.md

Now that autoload and simplified config is a thing, we can also simplify our nushell instructions

docs: simplify nushell completion script

---

pixi.toml
pytest.ini

When we pass `-m` to `pytest` multiple times, only the last one is used.
This results in the fast tests to run also the extra slow tests.
This times out with a debug build

fix: `pixi run test`

---

src/build/cache/mod.rs
tests/integration_python/pixi_build/test_build.py

There was an issue were the packages in the build-cache were reused for unrelated source checkouts. This is because we bucket the caches based on the pinned source spec but for a lot of examples the pinned path source spec was simply `.`. This caused a lot of examples to reuse the cache entry of another source checkout causing strange behavior.
I fixed this issue by using the pinned source spec as the cache key if the source is immutable (e.g. for git checkouts) and otherwise (e.g. for path source dependencies) use the absolute path on disk as the cache key. I think this makes sense as it creates separate cache entries for packages in different locations on disk (like temporary directories).
Fixes #2792

fix: use correct directory for build artifact cache

---

Cargo.lock

This includes the `resolvo` improvements resulting in potentially slicing the memory usage and solve time in half. 
A quick test shows that solving https://github.com/holoviz/holoviews/blob/main/pixi.toml from 10 seconds to 5.6 seconds and taking only half of the RAM.

chore: cargo deps

---

tests/integration_python/common.py
tests/integration_python/test_main_cli.py

I noticed we use `ALL_PLATFORMS` for the `platforms = [..]` section in a few generated projects. I think this is unnecessary and we should use `CURRENT_PLATFORM` by default. The tests are run on a number of platforms anyway. There was also a tests that wasnt using the prefix.dev conda-forge channel yet which had some failures.

chore: use current platform by default

---

Cargo.lock
crates/pixi_config/src/lib.rs
crates/pixi_git/src/resolver.rs
crates/pixi_git/src/sha.rs
crates/pixi_git/src/source.rs
crates/pixi_git/src/url.rs
crates/pixi_glob/src/glob_mtime.rs
crates/pixi_progress/Cargo.toml
crates/pixi_progress/src/lib.rs
crates/pixi_pty/src/unix/pty_process.rs
crates/pixi_record/src/lib.rs
crates/pixi_record/src/pinned_source.rs
crates/pixi_uv_conversions/src/types.rs
src/build/mod.rs
src/project/mod.rs

This should be merged **before** https://github.com/prefix-dev/pixi/pull/2778
Turns out, we have quite a few unused functions. I used my own discretion, how to deal with them. I mostly followed the following rule:
- has something to do with `pixi build`? -> `allow(unused)`
- is used in a test? -> `cfg(test)`
- other reason? -> delete it
Please review carefully and check if we need some of these functions after all.
(Or if they actually should be `pub`, because we will use them soon in other crates)

fix: remove or explicitly allow unused functions

---

Cargo.lock
Cargo.toml

Fixes: #2839 
To make sure we don't build version-ranges twice

chore: make sure we only build one version of `version-ranges`

---

docs/build/backends.md
docs/reference/pixi_manifest.md
docs/source_files/pixi_tomls/simple_pixi_build.toml
mkdocs.yml

Add some information regarding build backends, not meant to be complete just yet. Mainly serving as a vehicle to document the behaviors and environment variables added in #2843.

docs: build backend docs

---

crates/pixi_consts/src/consts.rs
crates/pixi_spec/src/toml.rs
src/cli/global/edit.rs
src/cli/info.rs
src/global/project/manifest.rs
src/global/project/mod.rs
src/global/project/parsed_manifest.rs

When using pixi global edit, if the manifest folder didn't exist it would throw an error when trying to save. Some EDITORs also will error when trying to open the file. This creates the folder. 
This also cleans up some consts around manifest file and folders and fixes the exposed name error not matching the executable name in the global manifest.

fix: create missing global manifest folder with pixi global edit

---

crates/pixi_manifest/src/manifests/source.rs
crates/pixi_manifest/src/toml/document.rs
tests/integration_rust/add_tests.rs
tests/integration_rust/snapshots/integration_rust__add_tests__add_dependency_dont_create_project.snap

previously if `pixi.toml` contained a `[workspace]` and you runned `pixi add` it would create a `[project]` table because we always verify if we need to add platforms, and do it with a hardcoded `project` key. 
Now we will have a small logic to find the table name.

fix: pixi add creates a project

---

Cargo.lock
crates/pixi_build_frontend/Cargo.toml
crates/pixi_build_frontend/src/into_build_types.rs
crates/pixi_build_frontend/src/lib.rs
crates/pixi_build_frontend/src/protocols/builders/pixi.rs
crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs
crates/pixi_build_frontend/src/protocols/mod.rs
crates/pixi_build_frontend/src/snapshots/pixi_build_frontend__into_build_types__tests__conversions_v1_docs@pixi_build_cpp.snap
crates/pixi_build_frontend/src/snapshots/pixi_build_frontend__into_build_types__tests__conversions_v1_docs@pixi_build_python.snap
crates/pixi_build_frontend/src/snapshots/pixi_build_frontend__into_build_types__tests__conversions_v1_docs@pixi_build_workspace.snap
crates/pixi_build_frontend/src/snapshots/pixi_build_frontend__into_build_types__tests__conversions_v1_examples@boltons.snap
crates/pixi_build_frontend/src/snapshots/pixi_build_frontend__into_build_types__tests__conversions_v1_examples@cpp-sdl.snap
crates/pixi_build_types/Cargo.toml
crates/pixi_build_types/src/capabilities.rs
crates/pixi_build_types/src/lib.rs
crates/pixi_build_types/src/procedures/initialize.rs
crates/pixi_build_types/src/project_model.rs
crates/pixi_manifest/src/lib.rs
crates/pixi_manifest/src/target.rs

This extracts the required manifest fields into the `initialize` of the build protocol, this has the benefit of allowing the backends to not rely on the `pixi.toml` itself, this is nice because it decouples whatever we do in the `pixi.toml` (like adding extra fields) to whatever the backends need to know.

feat: extract pixi manifest info into protocol

---

docs/index.md

Fixes an error in the Pixi installation documentation for unix systems.
Pixi adds itself to PATH in ~/.bashrc, NOT ~/.bash_profile.
Not sure if that has always been the case or if it's because that was changed at some point.

docs: Fix installation docs mistake in index.md

---

tests/integration_python/pixi_build/test_build.py
tests/integration_python/pixi_build/test_git.py

- `>30s` I marked as extra slow
- `>4s,<30s` I marked as slow

test: mark tests as slow

---

Cargo.toml
tests/integration_rust/add_tests.rs
tests/integration_rust/solve_group_tests.rs

Add an `online_tests` feature that specifically covers tests accessing the Internet.  It is enabled by default to preserve the existing behavior, but can be explicitly disabled when running the test suite entirely offline.
I have not added the respective feature checks to
`slow_integration_tests`, as they all seem to require Internet, so that seems redundant.
Fixes #2880

test: add `online_tests` feature to control Internet use

---

src/global/project/mod.rs
src/project/repodata.rs
src/repodata.rs

A follow-up on https://github.com/prefix-dev/pixi/pull/1767

refactor: simplify repodata_gateway function

---

crates/pixi_manifest/src/toml/pyproject.rs

fix: pyproject `entry-points`

---

schema/model.py
schema/schema.json
src/cli/search.rs
src/project/mod.rs
tests/integration_rust/common/mod.rs

fix: Print warning when pixi manifest is not parsed in pixi search

---

crates/pixi_build_frontend/tests/diagnostics.rs
crates/pixi_manifest/src/manifests/manifest.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/toml/deprecation.rs
crates/pixi_manifest/src/toml/feature.rs
crates/pixi_manifest/src/toml/manifest.rs
crates/pixi_manifest/src/toml/mod.rs
crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__task__test__depends_on_deprecation.snap
crates/pixi_manifest/src/toml/target.rs
crates/pixi_manifest/src/toml/task.rs
crates/pixi_manifest/src/toml/warning.rs
crates/pixi_manifest/src/utils/test_utils.rs
src/main.rs

This PR reverts the deprecation error on `depends_on` in favor of a deprecation warning. 
We did not really have a way to signal warnings like deprecations in the manifest. This PR adds a simple mechanism to collect warnings during parsing. These warnings are emitted after the project is parsed. Im a little unsure whether it makes sense to just emit them or if we should add a method to emit them. 
An example when running `pixi list --no-install` on the holoviews repository.
```
WARN Encountered 2 warnings while parsing the manifest:
⚠ The `depends_on` field is deprecated. Use `depends-on` instead.
╭─[pixi.toml:136:1]
135 │ cmd = 'pytest holoviews/tests/ui --ui --browser chromium'
136 │ depends_on = ["_install-ui"]
· ─────┬────
·      ╰── replace this with 'depends-on'
137 │
╰────
⚠ The …
```

feat: add deprecation notice for `depends_on`

---

src/main.rs

When running a debug build on windows you often get "stackoverflow" errors when starting pixi. This is because the default stacksize on windows is smaller than on other operating systems. This PR works around this issue by boxing the main entrypoint future instead which effectively moves it to the heap.

refactor: spawn main entrypoint in box

---

.github/workflows/ci.yml

We noticed that 15 minutes is sometimes not enough for this architecture

ci: bump timeout for macOS x86_64

---

mkdocs.yml

Changes the documentation slightly to move some less interesting top-level sections down in the sidebar.

docs: move top-level sections

---

docs/features/environment.md
docs/source_files/pixi_tomls/activation.toml

Triggered by https://github.com/prefix-dev/pixi/issues/2859
Thought this might be missing from the activation story in that file

docs: add more activation documentation

---

src/main.rs

I'm still running into stack overflow issues when running pixi in debug mode on windows. This is mostly caused by the fact that windows has a 1MB stack size for the main thread. Which is relatively small to the 8MB on macOS and Linux.
Apparently, there is a not very well-documented environment variable to set the stack size of threads called `RUST_MIN_STACK`. But this only sets the stack-size for newly spawned threads while the issues happens on the main thread. I noticed uv very recently worked around this issue to spawn an additional main thread from which the entire application is ran. Pretty clever, so I implemented the same behavior for pixi. 
Now I can finally run pixi again in debug mode. 🥳

fix: stackoverflow when running pixi in debug mode on windows

---

src/cli/run.rs
tests/integration_python/test_run_cli.py

`pixi run --help` and `pixi run -h` already worked. However `pixi run python --help` returned the help of `pixi run` instead of the one from python

fix: `pixi run --help`

---

pixi.toml

This was an oversight from an earlier PR.
The behavior stays the same

test: simplify extra_slow task

---

Cargo.lock
crates/pixi_progress/Cargo.toml
crates/pixi_progress/src/lib.rs
src/install_pypi/mod.rs
src/uv_reporter.rs

We found some strange behavior in sending items over an async channel from a sync rayon thread that caused messages to never arrive. Ive banged my head against the problem and couldnt figure out what was happening. So in the end I just simplified the code drastically and removed all the async code all together. Turns out it wasnt really needed anyway.
Fixes #2851

fix: shell hang on progress bar

---

pixi.lock
pixi.toml
src/global/project/mod.rs
tests/integration_rust/common/builders.rs

I use this when I start a docker on my Mac, and I've used it previously on a Raspberry Pi, but never committed it.

chore: add linux aarch64 support

---

src/build/cache/source_metadata_cache.rs
src/build/mod.rs

Fixes an issue where the build variants where not included in the source meta cache which caused invalid cache issues.

fix: take into account the variants for the source cache

---

src/cli/init.rs
tests/integration_python/common.py
tests/integration_python/test_main_cli.py

On my system, `pixi init some_folder` didn't work anymore if `some_folder` didn't exist.
I can confirm that `test_pixi_init_non_existing_dir` fails on my machine without the Rust code changes, and works with them.

fix: pixi init

---

Cargo.lock
crates/pixi_build_frontend/src/protocols/builders/pixi.rs
crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs
crates/pixi_build_frontend/src/protocols/mod.rs
crates/pixi_build_type_conversions/Cargo.toml
crates/pixi_build_type_conversions/src/project_model.rs
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_cpp.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_python.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_workspace.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_docs@pixi_build_workspace_variants.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@boltons.snap
crates/pixi_build_type_conversions/src/snapshots/pixi_build_type_conversions__project_model__tests__conversions_v1_examples@cpp-sdl.snap
crates/pixi_build_types/src/procedures/initialize.rs
crates/pixi_build_types/src/project_model.rs

Some last minute changes to make the build protocol even more forward compatible.

refactor: make more forward compatible

---

src/cli/completion.rs

closes https://github.com/prefix-dev/pixi/issues/2934
there might be other aliases we could add down the line, but at least to me `pixi r` is the one I'm using the most.

feat: add nushell autocompletion for pixi r

---

examples/pixi-build/boltons/pixi.lock
examples/pixi-build/boltons/pixi.toml
examples/pixi-build/boltons/pyproject.toml

The pixi-build Boltons example seemed to do nothing, and it was also incorrect, with regards to the naming.
This should fix this.

fix: boltons example seemed broken

---

.github/workflows/release.yml

fixes #2936 
I've made this branch on the org to test the release scripts
Tested by running the artifacts from: https://github.com/prefix-dev/pixi/actions/runs/12832606818

fix: add jemalloc env var page setting to release build

---

crates/pixi_build_frontend/src/protocols/builders/pixi.rs
crates/pixi_build_frontend/tests/snapshots/diagnostics__invalid_manifest.snap

I spend too much time on finding the file from the error. This will avoid that lost time, next time.
From:
```
× failed to setup a build backend, the pyproject.toml could not be parsed
```
To:
```
× failed to setup a build backend, the /Users/rubenarts/examples/ros_workspace/src/talker/pyproject.toml could not be parsed
```

chore: pixi build manifest error print full path

---

.github/workflows/ci.yml

I've noticed that newly opened PRs don't trigger a CI workflow. This change ~~hopefully~~ fixes that

ci: run workflow on opened PR

---

crates/pixi_manifest/src/manifests/workspace.rs
docs/reference/pixi_manifest.md

As discussed in https://github.com/prefix-dev/pixi/issues/2964#issuecomment-2604253502

docs: fix ambiguous version specifiers

---

crates/pixi_build_type_conversions/src/project_model.rs

Removes clones in the pixi build type conversions that were unneeded as the code already had ownership of the values and so were unnecessary

refactor: use destructuring to remove clones in conversion

---

tbump.toml

We don't actually use the git functionality, so let's go back to the default config

ci: simplify tbump config

---

src/cli/list.rs

While reviewing #2960 I found that `pixi list` doesn't print the correct information
Before:
```
> pixi list -x
Package      Version  Build               Size      Kind   Source
python       3.12.8   hc22306f_1_cpython  12.4 MiB  conda  python
sphinx_tags  0.4                          19.2 KiB  pypi   sphinx_tags-0.4-py2.py3-none-any.whl
```
After:
```
> pixi list -x
Package      Version  Build               Size      Kind   Source
python       3.12.8   hc22306f_1_cpython  12.4 MiB  conda  python
sphinx_tags  0.4                                    pypi   git+https://github.com/beenje/sphinx-tags.git@490f40f0042792ca410c249e195f29c96e33b25b
```

fix: `pixi list` should print the git location instead of the wheel

---

src/cli/shell.rs
src/cli/shell_hook.rs
src/prompt.rs

- Closes https://github.com/prefix-dev/pixi/issues/1275
Made some choices that can be discussed:
- Had to copy things form `shell.rs`, not sure if a refactor is expected here.
- Detect if we are already in a pixi shell so we don't duplicate the PS1 recursively
- Do not add the shell function for reactivation
- The shell syntax used for `$PS1` makes it vulnerable to `set -u` errors if not set, I added a fix here too. Is that ok?
Not particularly proud of that `shell.clone()` either. Maybe there's a better way?

feat: Set PS1 in shell-hook too

---

docs/index.md

This fixes https://github.com/prefix-dev/pixi/issues/1248
If the user does not have Oh My Zsh they need to add this line for autocomplete to work with Zsh.

docs: enable autocomplete on Zsh

---

.github/workflows/ci.yml
pixi.toml

Clippy and fmt is currently run twice, since the skip on pre-commit didn't work, since the IDs changed. I don't see how running them separately improves things, so I put it all on pre-commit

ci: fix clippy and fmt check

---

src/cli/init.rs

I always wondered why "description" is generated with `pixi init`. Looking at the code, it doesn't seem like we really do anything with this key. I therefore propose to remove `description` from the template.

fix: remove `description` from `pixi init` template

---

docs/advanced/authentication.md

In the documentation, there isn't a tab for authenticating to AWS codeartifact, but I stumbled upon the relevant issue https://github.com/prefix-dev/pixi/issues/1783 and the linked blog post.
I managed to set up keyring authentication using the newer `pixi global install` method (as opposed to the `pipx` workaround in the older blog post). In my case, I have left `keyringrc.cfg` empty (there are good defaults as [mentioned in the docs](https://github.com/jmkeyes/keyrings.codeartifact)) so it wasn't a necessary step.
I hope this will help others who are using codeartifact too.

docs: add section on aws codeartifact

---

.gitattributes
src/cli/init.rs

Attempting a three-way file merge doesn't really make sense on pixi.lock, so we could treat it as a binary file (choose either ours or theirs, but don't attempt to manually resolve conflicts into an intermediate. Ultimately in case of lock-file conflicts the user probably almost always wants to resolve conflicts from three-way merging pixi.toml and then regenerate the lock-file.

feat: prevent line-based 3-way merge on pixi.lock

---

crates/pixi_manifest/src/pypi/pypi_requirement.rs
src/lock_file/update.rs

Attempt to implement: https://github.com/prefix-dev/pixi/issues/1881#issuecomment-2621283703
This will also update the prefix on run when there are pypi path dependencies that are directories, this will typically be source files that we are working with. I think this is in spirit with the wanted behavior, even though the conda filter works a bit differently, as I expect git dependencies to be updated with a `pixi update` instead. And path dependencies which are not directories are either wheels or sdists, and do not change often (if at all)
```bash
pixi init --format=pyproject
#should do a full install
pixi r python
touch pyproject.toml
pixi r python
````

fix: will also update prefix if there are pypi path dependencies

---

install/install.ps1
install/install.sh

Trying to install `v0.40.2` using `curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=0.40.2 bash` results in 
```
This script will automatically download and install Pixi (0.40.2) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/download/0.40.2/pixi-x86_64-unknown-linux-musl.tar.gz
error: 'https://github.com/prefix-dev/pixi/releases/download/0.40.2/pixi-x86_64-unknown-linux-musl.tar.gz' is not available
```
which confused me for a second. I hope this auto-prepending the missing `v` makes it smoother. Let me know what you think.

feat: Auto-prepend 'v' to version numbers during pixi installation

---

src/main.rs

Switches back to the multithreaded runtime for all of pixi.

fix: change back to multithreaded runtime

---

install/install.sh

If the ${HOME}/.bashrc file does not exist, create it with the `touch` command.
File was touched only if it already existed.

fix: logic was backward for creating missing .bashrc

---

src/cli/add.rs
src/cli/run.rs

Attempt to fix #3050 
This is not a total fix as there is no guarentee we hit all cases where we write to the .pixi folder. But multiple functions can make this directory. @baszalmstra Do you have a good idea on how to guarentee this `.gitignore` file is written when the `.pixi` folder is made?

fix: do proper sanity check on add and run

---

src/cli/remove.rs

fix: add check error message to remove uv dependencies

---

crates/pixi_build_frontend/src/protocol.rs
crates/pixi_build_frontend/src/protocols/builders/conda_build/protocol.rs
crates/pixi_build_frontend/src/protocols/mod.rs
crates/pixi_build_frontend/src/reporters.rs
src/build/mod.rs

That way they fit with the RPC method names `conda/getMetadata` and `conda/build`

fix: protocol method names

---

docs/reference/cli.md
src/cli/run.rs
tests/integration_python/test_run_cli.py

Solves https://github.com/prefix-dev/pixi/issues/3106
**Full disclosure:** I'm not a rust programmer, but I have some experience in other languages. I stuck with the existing code for my implementation. Feel free to comment/fix/change as needed.
* I chose the flag to be `--dry-run` with the short flag `-n`, to keep in line with a similar flag that exists for the `upgrade` and `update` commands
* for the code itself - I print the dry-run log first, and then allow to each task (and dependent tasks) to print its commands, as done by default - after that part I just continued with the for loop
* I updated the docs as well and checked locally that we can see them
* I wrote a simple test - in the tested task we print an environment variable. When running in dry run mode we only expect to see …

feat: Added dry-run flag to pixi run + docs + test

---

.gitignore
Cargo.lock
crates/pixi_build_frontend/Cargo.toml
crates/pixi_build_frontend/tests/diagnostics.rs
crates/pixi_build_frontend/tests/snapshots/diagnostics__invalid_manifest.snap
crates/pixi_manifest/src/discovery.rs
crates/pixi_manifest/src/manifests/document.rs
crates/pixi_manifest/src/manifests/provenance.rs
crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_failing.snap
crates/pixi_manifest/src/snapshots/pixi_manifest__discovery__test__workspace_discoverer@non-existing.snap
crates/pixi_manifest/src/snapshots/pixi_manifest__discovery__test__workspace_discoverer@non-pixi-build_project.snap
crates/pixi_manifest/src/utils/test_utils.rs
src/workspace/discovery.rs
src/workspace/mod.rs

There was a failure when running the list command with a `--manifest-path pixi.toml` instead of using `./pixi.toml`. What happened is that the discovery found `pyproject.toml` but when creating the workspace path it tried to use the parent of a file which was basically empty, and making the `workspace.root` be an empty path.
Resulting in failures if this was being passed around. As can be seen:
- `× base path is not absolute:` https://github.com/prefix-dev/setup-pixi/actions/runs/13088235283/job/37021990108
- `× lock-file not up-to-date with the project`: https://github.com/Hofer-Julian/Ribasim/actions/runs/13266269616/job/37034421343#step:6:18
This should resolve that.

fix: fixing passing a file as `--manifest-path`

---

src/cli/lock.rs
src/cli/update.rs
src/lib.rs
src/lock_file/mod.rs
src/lock_file/outdated.rs
src/lock_file/update.rs
src/workspace/workspace_mut.rs
tests/integration_rust/common/mod.rs

Follow up to the big workspace refactor.
- Methods were unnecessarily nested
- Updated docstrings
- Fix variable names

refactor: clean up workspace methods

---

tests/integration_python/test_docs_examples.py

That was to workaround a pixi build bug that seems to be fixed by now

fix: remove cache dir in pixi build tests

---

.github/workflows/ci.yml

This tries to test more on the downstream tests mainly:
- Run the installations with `--locked` to make sure we test satisfiability
- Actually start an environment for `polarify` 
- Getting more info with `pixi info` and `pixi list`

test: cover more with downstream tests

---

tests/integration_rust/install_tests.rs

https://github.com/prefix-dev/pixi/actions/runs/13311434771/job/37174767230
the tests only running on `main` are failing

fix: S3 tests

---

tests/integration_python/pixi_build/test_build.py

Fixes #3120
Depends on https://github.com/prefix-dev/pixi-build-backends/pull/75

fix: `BUILD_EDITABLE_PYTHON` env flag

---

docs/features/system_requirements.md

docs: fix list

---

src/lock_file/update.rs

Changes the message of the progress bar when it is mapping PyPI packages. @wolfv and @ruben-arts were discussing this and this sounded like it should be modified :)

fix: change the progress message during mapping of packages

---

crates/pixi_git/src/url.rs
crates/pixi_uv_conversions/src/requirements.rs
src/lock_file/update.rs
src/uv_reporter.rs
tests/integration_rust/add_tests.rs

The second time parsing the git URL would remove the `git@` from `ssh://git@github..` which is not right in this case.
TODO:

fix: skip unneeded url parse and only add git+ when needed

---

src/install_pypi/mod.rs
src/install_pypi/plan/mod.rs
src/install_pypi/plan/test/mod.rs

When you switch from a registry package to a local source package, pixi should re-install it. This was previously not checked in the installation planner. This PR adds that check. **But** it doesn't fix the complete problem as we still get it from the cache afterward, so this PR is the first in a series to fix the problem of reinstallation completely. 
Reproducer:
First `pixi install` this:
```toml
[project]
name = "pixi_test"
platforms = ["osx-arm64"]
[tasks]
check = "python -c 'import yaml; print(yaml.__file__)'"
[dependencies]
python = ">=3.9,<3.14"
pyyaml = "==6.0.2,<7"
```
Then clone the `pyyaml` package: `git clone --branch 6.0.2 git@github.com:yaml/pyyaml.git`
And modify the pixi.toml to:
```toml
[project] …
```

fix: reinstall if required is source and installed is from registry.

---

src/environment/conda_prefix.rs
src/prefix.rs
tests/integration_python/test_edge_cases.py

Instead of:
```
❯ pixi i
Error: 
╰─▶ EOF while parsing a value at line 1 column 0
```
You'll now get errors like:
```
❯ pixi i
Error: 
× failed to collect prefix records from '/Users/rubenarts/dev/pixi/examples/conda_mapping/.pixi/envs/default'
╰─▶ EOF while parsing a value at line 1 column 0
help: try `pixi clean` to reset the environment and run the command again
```
This doesn't solve the issue but might help the users who walk into similar issues. The actual issue is described in: https://github.com/conda/rattler/issues/1062

chore: improve error messages on prefix issues

---

Cargo.lock
crates/pixi_git/Cargo.toml
crates/pixi_git/src/git.rs
crates/pixi_git/src/lib.rs
crates/pixi_git/src/resolver.rs
crates/pixi_git/src/source.rs
src/build/mod.rs

fixes: https://github.com/prefix-dev/pixi/issues/2981
remove `miette` and replace it with actual errors
```
pixi add exchangelib --git git+https://github.com/ecederstrand/exchangelib --branch main
Error: 
× failed to extract metadata for 'exchangelib'
╰─▶ Git operation failed
```

feat: replace miette diagnostic with actual errors

---

docs/advanced/production_deployment.md

In https://github.com/Quantco/pixi-pack/pull/104 I am proposing to add a `--use-cache CACHE_DIR` flag to optionally allow the user to avoid re-downloading packages.
Syncing the docs to reflect so. Only merge when/if that PR merges :) 
Also: thanks for your great work!

docs: Sync pixi-pack docs with PR #104 (add --use-cache)

---

crates/pixi_consts/src/consts.rs
src/cli/list.rs

Now it also prints the source and uses the colors to print the kind.

fix: improve `pixi list` output for conda source packages

---

src/cli/global/add.rs
src/cli/global/expose.rs
src/cli/global/install.rs
src/cli/global/remove.rs
src/cli/global/uninstall.rs

There was no way to get the original error if reverting failed. Now we always print the original error and the reverting error when given verbose flags

fix: pixi global revert error message

---

docs/advanced/s3.md

depends on (the release of) https://github.com/conda/rattler/pull/1076

docs: Add rattler-index s3 documentation

---

Cargo.lock
Cargo.toml
crates/pixi_manifest/Cargo.toml
crates/pixi_manifest/src/pypi/snapshots/pixi_manifest__pypi__pypi_requirement__tests__deserialize_failing.snap
crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__feature__test__mismatching_excluded_target_selector.snap
crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__feature__test__mismatching_target_selector.snap
crates/pixi_manifest/src/toml/snapshots/pixi_manifest__toml__manifest__test__unused_features.snap
src/lock_file/snapshots/pixi__lock_file__virtual_packages__test__virtual_package_not_found_error.snap

chore: upgrade Cargo dependencies

---

src/build/mod.rs
src/cli/build.rs

This PR enables the `pixi build` command to also actually use incremental building, i.e re-using the work dir if possible.

feat: add caching of regular build

---

.github/dependabot.yml
.github/workflows/ci.yml

I've expected that the latest GitHub actions update now does the right thing automatically, but it doesn't

ci: revert machete update

---

tests/integration_python/pixi_build/test_git.py

Our attempts to fix it were not fruitful

test: skip `test_build_git_source_deps_from_tag` on Windows

---

pixi.lock
pixi.toml

Force `git` to an older version.

chore: downgrade git

---

src/lock_file/virtual_packages.rs
tests/data/lockfiles/archspec.lock
tests/data/lockfiles/ignored_virtual_packages.lock

Fixes #3280 
As we've introduced virtual package validation, but we don't match archspecs yet, we should ignore them. And for that same reason any virtual packages we don't understand.

fix: ignore package we can't match with in the virtual packages.

---

crates/pixi_build_frontend/tests/diagnostics.rs
crates/pixi_consts/src/consts.rs
crates/pixi_manifest/src/discovery.rs
crates/pixi_manifest/src/manifests/document.rs
crates/pixi_manifest/src/manifests/provenance.rs
src/cli/init.rs
src/install_pypi/mod.rs
src/lock_file/resolve/pypi.rs
src/workspace/discovery.rs
tests/integration_python/test_main_cli.py
tests/integration_rust/common/mod.rs

`[workspace]` should be preferred over `[project]`.
At the moment they are simple aliases, but we should warn on `project` in the future.

feat: default to "workspace" with `pixi init`

---

tests/integration_python/pixi_build/test_git.py

The actual cause was the git update: https://github.com/prefix-dev/pixi/pull/3272

test: run test_build_git_source_deps_from_tag again for Windows

---

crates/pixi_config/src/lib.rs

Improves: #3271
Since we've been testing it for a long time already I think we can confidently make this the default.
The second question is, are we going to make `https://prefix.dev/conda-forge` the default channel as well to give users the best possible experience? 🤔

feat: make sharded repodata enabled by default

---

src/cli/info.rs
src/workspace/environment.rs
tests/integration_python/test_main_cli.py

fix: print all tasks for the current platform in `pixi info`

---

docs/advanced/s3.md

otherwise you will get the following error:
```
❯ pixi list
Error:
× dispatch failure
├─▶ other
├─▶ the credentials provider was not properly configured
╰─▶ ProfileFile provider could not be built: profile `conda` was not defined: `sso_region` was missing
```

docs: Set sso_region in s3 config example

---

README.md

Noticed this with a recent install on Linux.

docs: Update README.md to note PATH changes go in `~/.bashrc`, not `~/.bash_profile`

---

src/lock_file/satisfiability.rs
tests/integration_rust/add_tests.rs
tests/integration_rust/install_tests.rs
tests/integration_rust/solve_group_tests.rs

I've marked every test that takes >1s as slow

test: mark more tests as "slow"

---

.github/workflows/ci.yml
pixi.toml

Fixes the issue where the cli docs generation update the lockfile, creating a diff

fix: use --locked to run the generation of cli docs

---

src/lock_file/update.rs

now 2 places to request conda-mapping, one for solving conda enviornemts with the `workspace::authenticated_client()`, another one for solving pypi environments with `workspace::client()`.
This pr let the latter case also use `authenticated_client()`.

fix: let amend_pypi_purls() always use reqwest client with the mirror middle ware

---

.github/actionlint.yml
.github/workflows/ci.yml
.github/workflows/setup-dev-drive.ps1

Updated the windows runners to the latest Windows 2025 preview version of Windows Server.
Changed the script to match with how `uv` setups up their runners.

fix: use new windows runners with the dev drive feature

---

.github/workflows/post_release.yml

I've updated the token but we didn't update the releaser after the cargo-dist upgrade.

chore: fix winget releaser job

---

.github/workflows/ci.yml

I found that we're not using the run any more for the releases, so making it the paid runner makes little sense as we don't need main to be fast.
Edit the CI job this PR fixes: https://github.com/prefix-dev/pixi/actions/runs/13925247542/job/38967978468?pr=3378

fix: use windows latest as arm build runner

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/enforce-sha.yaml
.github/workflows/lint-pr.yml
.github/workflows/post_release.yml
.github/workflows/release.yml
.github/workflows/schema.yml
.github/workflows/test_common_wheels.yml
.github/workflows/trampoline.yaml
.github/workflows/update-lockfiles.yml

- pin external actions
- for setup-pixi, always use main
- enforce sha also in the future
For motivation see https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://michaelheap.com/pin-your-github-actions/

ci: pin github actions

---

Cargo.lock
Cargo.toml
pixi_docs/Cargo.lock

1. bump zip to 2.4.2
2. limit priority-queue to 2.2.0, avoid introduce `edition = 2024` from priority-queue 2.2.1
3. run cargo update on Cargo.toml and pixi_doc/Cargo.toml, resolve ci fail in #3374

fix: Upgrade zip to 2.4.2, update Cargo.lock

---

src/global/install.rs

fix: stop requiring `PATH` for `pixi global` activation

---

tests/integration_python/common.py

These strings can get quite long. A line break helps a lot to compare them

test: improve error message for python integration tests

---

crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs
crates/pixi_manifest/src/features_ext.rs
src/build/mod.rs
src/lock_file/update.rs

Fixes #3158
This PR ensures that diagnostics from backend errors are now properly propagated.
`main`:
```
Error:   × failed to extract metadata for 'subproject'
╰─▶ failed to initialize a build backend for subproject
```
This PR:
```
Error:   × failed to extract metadata for package 'subproject'
├─▶   × the initialization of the build backend for 'subproject' failed
│
╰─▶   × missing field 'build' in table
╭─[F:\projects\issues\issue-3158\subproject\pixi.toml:7:1]
6 │
7 │ ╭─▶ [package.run-dependencies]
8 │ ╰─▶ python = "*"
╰────
```

fix: propagate error diagnostics from backends

---

src/cli/search.rs
tests/integration_rust/snapshots/integration_rust__search_tests__search_multiple_versions.snap

Add `run_export` information to the output of `pixi search`. If the data is not available from the repodata the output will be:
```
Run exports: not available in repodata
```

feat: add run export information to search

---

docs/deployment/pixi_pack.md

added section about self-extracting binaries (copy-pasted from the pixi-pack README) and a reference to it in the "unpacking without pixi-pack" section

docs: mention self-extracting binaries in pixi_pack

---

.pre-commit-config.yaml
docs/deployment/pixi_pack.md
pixi.toml

I tried "cargo-clippy" in my pre-commit now for a while, but the overhead is just to much.
I want my minimal version back again :)

chore: add pre-commit-minimal back

---

pixi.toml

The pytorch examples are often timing out.
Let's hope that this solves that.

ci: bump timeout extra slow tests

---

README.md
docs/advanced/installation.md
docs/index.md
install/install.sh

make install.sh posix compliant, then we can install without bash on Unix-like os.

feat: make install.sh posix compliant

---

docs/workspace/advanced_tasks.md

In relation to #3468, this PR adds to the documentation that tasks are run by default in the workspace root.

docs: added task cwd default behaviour

---

src/cli/global/sync.rs
src/cli/global/update.rs
src/global/common.rs
src/global/completions.rs
src/global/mod.rs
src/global/project/mod.rs

Fixes #3476
On Windows we never install completions, so let's also avoid the completion checks then
Also skip completions check for `environment_in_sync`.
This check is pretty expensive and unless users manually remove things in that directory, that check also isn't necessary.

perf: only call `pixi global` completion functions when necessary

---

docs/source_files/pixi_tomls/activation.toml
docs/source_files/pixi_tomls/lots_of_channels.toml
docs/source_files/pixi_tomls/main_pixi.toml
docs/source_files/pixi_tomls/multi-environment-py-envs.toml
docs/source_files/pixi_tomls/multi-environment-simple.toml
docs/source_files/pixi_tomls/pytorch-conda-forge-envs.toml
docs/source_files/pixi_tomls/pytorch-conda-forge.toml
docs/source_files/pixi_tomls/pytorch-from-pytorch-channel.toml
docs/source_files/pixi_tomls/pytorch-pypi-envs.toml
docs/source_files/pixi_tomls/pytorch-pypi.toml
docs/source_files/pixi_tomls/simple_pixi.toml

This PR changes the `[project]` headers in the toml files in `docs/source_files/pixi_tomls` to `[workspace]`.

refactor: change section header from [project] to [workspace] in the docs source files

---

docs/reference/environment_variables.md
docs/workspace/environment.md

They are better suited in the reference

docs: move environment var section

---

src/shell_snippets/pixi-bash.sh
src/shell_snippets/pixi-zsh.sh

close #3490 
close #3308 
1. use `$PIXI_EXE "$@"` to run the main command.
2. respect the exit code of the main commmand

fix: shell-hook, avoid run unexpected commands

---

docs/deployment/pixi_pack.md

xref https://github.com/Quantco/pixi-pack/pull/116

docs: Mention pypi support in pixi-pack

---

docs/reference/pixi_manifest.md

In the last two weeks it happen two times that I interacted with users that were confused by how `scripts` listed under the activation table were used by pixi (see for example https://github.com/RoboStack/ros-humble/issues/271). I also do not have a full understanding of this, but I tried to document that I understood.

docs: Document that activation scripts are not simply sourced 

---

crates/pixi_manifest/src/discovery.rs
crates/pixi_manifest/src/manifests/workspace.rs
crates/pixi_manifest/src/pyproject.rs
crates/pixi_manifest/src/toml/manifest.rs
crates/pixi_manifest/src/toml/workspace.rs
crates/pixi_manifest/src/workspace.rs
docs/reference/pixi_manifest.md
src/activation.rs
src/cli/build.rs
src/cli/info.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/cli/workspace/name/get.rs
src/cli/workspace/name/set.rs
src/global/project/mod.rs
src/workspace/environment.rs
src/workspace/mod.rs
tests/integration_rust/init_tests.rs

This PR makes the workspace name optional and instead allows deriving the name from the location of were the workspace is stored. E.g. if the workspace is stored under `/foo/bar/pixi.toml` the name of the workspace will default to `bar`. If the workspace is stored under `/pixi.toml` the workspace will have the fallback name "workspace". 
The workspace name is used only to provide context to the user so I think this behavior is appropriate. This is different from the package name, which is also stored in the lock-file. 
I added 3 tests to verify the behavior.
Fixes https://github.com/prefix-dev/pixi/issues/3431
Closes #3514

feat: make workspace name optional

---

docs/deployment/pixi_pack.md

We slightly changed the CLI args of `pixi-pack` in https://github.com/Quantco/pixi-pack/pull/129.

docs: Update pixi-pack docs for ignoring non-wheel pypi packages

---

Cargo.lock
Cargo.toml
pixi_docs/Cargo.lock
tests/integration_rust/common/package_database.rs

Fixes https://github.com/prefix-dev/pixi/issues/3438 by updating the rattler dependency to include https://github.com/conda/rattler/pull/1195
* Ran 'pixi run update-rattler' to update rattler packages in the project.
* Needed to update a string in tests/integration_rust/common/package_database.rs to optional string for tests to pass.

feat: Update rattler dependencies to latest

---

src/cli/task.rs
tests/integration_python/test_main_cli.py

fix: fix panic for `pixi task list` for platform specific tasks

---

crates/pixi_build_frontend/src/protocols/mod.rs
crates/pixi_build_frontend/src/protocols/stderr.rs

This PR improves the error message when a build backend crashes during the `getMetadata` call. Instead of showing a cryptic error the output of the build backend is displayed:
`main`:
```
Error:   × failed to extract metadata for package 'root'
╰─▶   × pipe of stderr stopped earlier than expected
```
This PR:
```
Error:   × failed to extract metadata for package 'root'
╰─▶   × the build backend (pixi-build-python) exited prematurely.
│ Build backend output:
│
│
│  ╭─ Resolving environments
│  │
...
│ thread 'main' panicked at F:\projects\rattler-build\src\metadata.rs:466:14:
│ Build string is not resolved
│ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
│  │
│  ╰─────────────────── (took 0 seconds)
```

fix: improve error message if build backend crashes

---

docs/advanced/installation.md

docs: mention installation with wget instead of curl

---

src/cli/init.rs

Fixed this line:
```
🤔 Nothing to do here: 'pyproject.toml' already contains a '[tool.pixi.workspace3]' section.
```
(removed the redundant 3)

fix: fixed a typo in init.rs

---

src/lock_file/outdated.rs
src/lock_file/satisfiability.rs
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@binary-spec-source-record.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@expected-editable-multiple.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@expected-editable.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@explicit-pypi-dependency.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@mismatched-spec.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@missing-dependency.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@missing-pypi-extra.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@solve-groups-pypi.snap
src/lock_file/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@source-dependency.snap
src/workspace/environment.rs
tests/data/non-satisfiability/explicit-pypi-dependency/pixi.lock
tests/data/non-satisfiability/explicit-pypi-dependency/pixi.toml

Fixes #2238
This PR adds support to detect if a package that is locked as a conda package is only referenced by pypi dependencies in which case the lock-file is invalidated.

test: invalidate lock-file if a pypi dependency is requested

---

docs/advanced/installation.md

The windows installation script `pixi/install/install.ps1` is currently installing pixi at `%UserProfile%\.pixi\bin`, while the documentation `pixi/docs/advanced/installation.md` says that pixi gets installed in `LocalAppData/pixi/bin`. 
This fix is to change the documentation.

docs: Updating windows installation.md to correspond to installation.ps1

---

pixi.toml
renovate.json

This should help with renovate not being able to deal with newer pixi syntax: https://github.com/prefix-dev/pixi/pull/3604#issuecomment-2805008407

ci: renovate add pixi constraints

---

docs/reference/pixi_manifest.md

Replace some words `project` with `workspace`

docs: Replace `project` with `workspace` in more places

---

renovate.json

We run multiple macOS runner versions on purpose since 13 runs on x86_64 See https://github.com/prefix-dev/pixi/pull/3605

ci: renovate don't update macOS runner

---

docs/reference/pixi_manifest.md

I replaced the word "project" with "workspace" for consistency in terminology.

docs: replace "project" with "workspace"

---

src/install_pypi/plan/test/harness.rs
src/install_pypi/plan/test/mod.rs
src/install_pypi/plan/validation.rs
src/install_pypi/utils.rs

When using a pypi local archive things keep reinstalling.
```toml
[workspace]
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["https://prefix.dev/conda-forge"]
name = "installation-order"
platforms = ["osx-arm64"]
version = "0.1.0"
[tasks]
[dependencies]
python = "3.13.*"
minimal = { path = "./minimal-0.1.0-py2.py3-none-any.whl" }
```
```
...
INFO pixi::install_pypi: 4 of 5 required packages are considered are installed and up-to-date
INFO pixi::install_pypi: *re-installing* following packages: minimal
INFO pixi::install_pypi: re-installing 'minimal' because: 'Git archive is a path'
INFO pixi::install_pypi: Prepared 1 package in 0ms
INFO pixi::install_pypi: Installed 1 package in 1ms
✔ The default environment has been installed.
```
The above kept happening. …

fix: don't keep reinstalling local pypi archives

---

src/lock_file/update.rs

Fixes #3568
When a platform was removed it was detected as a platform that needed resolving. This PR fixes that issue by cross-referencing if the platform should also be resolved in the first place.

fix: dont resolve for previously locked platforms

---

crates/pixi_manifest/src/task.rs
src/cli/task.rs
src/task/task_graph.rs
tests/integration_python/__snapshots__/test_main_cli.ambr
tests/integration_python/test_main_cli.py

The tasks with commands including arguments were not printing properly. 
The previous behaviour: 
After the changes:

fix: json prints of the tasks

---

Cargo.lock
Cargo.toml
pixi_docs/Cargo.lock
src/lock_file/resolve/pypi.rs

This PR makes use of the `install_path` to create a relative path to lock instead of the url handling that was done before. The previous code existed before the time of uv workspaces, and this code should hopefully make this handling more correct. I ran into this while working on: https://github.com/prefix-dev/pixi/pull/3636
I've added some specific tests for the handling of paths, including one windows specific case. We are using path dependencies in CI so I assume this should tackle some of the cases.
I've also checked if the `examples/pypi-source-deps` lock stays the same.

feat: change the way paths are handled

---

renovate.json

The original script didn't work as can be seen here: https://github.com/prefix-dev/pixi/pull/3648
Let's hope that this does the trick.

ci: fix separate PR for rattler

---

Cargo.lock
Cargo.toml
pixi_docs/Cargo.lock

since we bump the rust edition to 2024, we do not need limit priority-queue version.

fix: remove priority-queue spec limit due to rust edition

---

src/cli/info.rs
tests/integration_python/__snapshots__/test_main_cli.ambr
tests/integration_python/test_main_cli.py

Fixes https://github.com/prefix-dev/pixi/issues/3667 and also exposes size for each environment. Not sure if I should add any tests for this or not!

feat: add environment size and prefix to pixi info

---

docs/python/pyproject_toml.md

Clarify the `pyproject.toml` for the `main_project` to ease reading in the last section.

docs: clarify which pyproject_toml is used

---

crates/pixi_uv_conversions/src/requirements.rs
crates/pixi_uv_conversions/src/types.rs
src/lock_file/package_identifier.rs
src/lock_file/satisfiability/mod.rs

Related issue: https://github.com/prefix-dev/pixi/issues/3687

fix: pypi panic with path dependencies in lock file

---

docs/reference/pixi_manifest.md

Not sure where exactly you wanna link here but the url is broken.
Old: https://docs.rs/pixi/latest/pixi/workspace/manifest/struct.ProjectManifest.html
New: https://docs.rs/pixi/latest/pixi/struct.Project.html

docs: fix broken project manifest link

---

crates/pixi_build_types/src/project_model.rs

fixes: https://github.com/prefix-dev/pixi-build-backends/issues/134
Tested it locally by building the backends with a path dependency and it now properly communicates that `target.linux-64` dependencies.

fix: package target selector platform serialization

---

crates/pixi_config/src/lib.rs
src/cli/global/install.rs
src/cli/global/list.rs
src/global/list.rs

Go from:
To:
This is a personal improvement, not sure if everyone agrees, but I don't think the path helps in this case as most users don't care about the manifest. 
`pixi global list` still contains the "header" as I think there it makes more sense, because it's a tool that requests more information.

chore: slightly cleanup cli output

---

docs/reference/cli/pixi/self-update_extender

Looks like the wrong example commands made their way into the docs for `self-update`.

fix: examples in self-update_extender

---

docs/reference/cli/pixi.md
src/cli/mod.rs

There are enough commands to make an unordered list awkward to parse:

style: Alphabetise command list in cli help

---

crates/pixi_build_types/src/procedures/conda_build.rs
src/build/mod.rs

This makes it easier to compare CondaOutputIdentifier's in Rust.
I also changed the type of the selected outputs to use a `BTreeSet`. This is a bit more efficient to check whether an identifier is contained within the selected outputs and should serialize the same way as a `Vec`.

feat: improve type of outputs, add Eq, PartialEq, etc.

---

crates/pixi_build_types/src/procedures/conda_build.rs
crates/pixi_build_types/src/procedures/conda_metadata.rs
crates/pixi_command_dispatcher/src/source_metadata/mod.rs
crates/pixi_glob/src/glob_hash_cache.rs
crates/pixi_glob/src/glob_mtime.rs
crates/pixi_record/src/source_record.rs
src/build/cache/build_cache.rs
src/build/mod.rs
src/lock_file/satisfiability/mod.rs

There are two changes:
- if the source is a file, we use the parent directory as globbing "base". This fixes the issue where `foobar = { path = "./recipe/recipe.yaml" }` always produced a `0000...` hash. I think this is not surprising behavior.
- We also got an input glob of `recipe.yaml` twice in the glob section in the `pixi.lock`. Making globs a `BTreeSet` fixes this. I don't think duplicate globs would ever make sense.

fix: source globs and make them unique

---

renovate.json
renovate.json5

We are on Rust 1.86.0, so we don't need those rules anymore

ci: update renovate rules

---

pixi.lock
pixi.toml

Also add `cargo-edit` since that is nowadays on conda-forge

chore: move `update-rattler` task to `dev`

---

Cargo.lock
Cargo.toml
crates/pixi_uv_conversions/src/conversions.rs
crates/pixi_uv_conversions/src/requirements.rs
src/install_pypi/mod.rs
src/install_pypi/plan/test/harness.rs
src/install_pypi/plan/validation.rs
src/lock_file/package_identifier.rs
src/lock_file/resolve/build_dispatch.rs
src/lock_file/resolve/pypi.rs
src/lock_file/resolve/resolver_provider.rs
src/lock_file/satisfiability/mod.rs

i had to adjust our index populating to fit our existing tests with the breaking changes from uv's side, there are also few name and function changes they made.

feat: migrate to `uv_distribution_types` for package requirements and update uv

---

crates/pixi_consts/src/consts.rs
docs/reference/cli/pixi/self-update.md
src/cli/self_update.rs

Add two cli options for `pixi self-update`:
- `--force`
- `--no-release-note`
when add `--force` option,
- `pixi self-update --version X --force` :   does not print the "upgrade"/"downgrade" message
- `pixi self-update --force`  :  skips the github api version resolving step, just download the latest binary directly.

feat: add cli options for self-update: --force and --no-release-note

---

pixi.toml

Without quoting here, you have to double quote in your terminal which is annoying

test: fix `test-specific-test`

---

.github/workflows/ci.yml
.github/workflows/setup-dev-drive.ps1

We ran out of space, so we only used cargo there.
But that conflicts with us setting cargo target dir in the pixi.toml. At this point it's not worth it IMO.
Let's just not use the dev drive for this job

ci: stop using dev drive for cargo test windows

---

src/cli/init.rs

`.egg-info` doesn't have anything to do with pixi and thus, I don't think we should add it to `.gitignore`. If we added `.egg-info`, we should add `*.pyc`, `__pycache__`, etc. as well which is out of scope IMO.

feat: Remove egg-info from gitignore and fix whitespace in beginning

---

Cargo.lock
Cargo.toml
crates/pixi_build_type_conversions/Cargo.toml
crates/pixi_build_type_conversions/src/project_model.rs
crates/pixi_build_types/Cargo.toml
crates/pixi_build_types/src/project_model.rs

Use `ordermap` instead of `indexmap` so we can `Hash` structs. This change does not affect the API at all.
@Hofer-Julian We both need this change so I pulled it into a seperate PR.

feat: use ordermap instead of indexmap

---

docs/first_project.md
docs/getting_started.md
docs/installation.md
docs/python/tutorial.md
docs/stylesheets/extra.css
mkdocs.yml

Taking a look at `uv` and `deno` I noticed that we're missing a little bit of a sum-up of a bunch of things pixi can do. In a form of "feature" list. This is why I removed the getting started, in the hope users reach this page first and will be redirected to the actual documentation. 
What I would like to do in another PR, is bringing back a real getting started but more mixed with how our current tutorials are. e.g.
- Getting stared with:
- Python in Pixi
- C++ in Pixi
- Lua in Pixi
- Pytorch in Pixi
- ROS in Pixi
Where specific users can get a getting started experience relevant to their use case. 
- Update of the python tutorial to make all commands work with the latest results
- Redo of the `getting_started.md` as basic usage
- Addition of `first_project.md` to get the absolute basic …

docs: refactor getting started and python tutorial

---

src/workspace/mod.rs

Fixes #3030 
We incorrectly checked the environments' folder, so a warning was triggered every time on Windows. 
Also tested it on my windows machine.

fix: check for the environments not the environments dir

---

.github/workflows/test_common_wheels.yml

This job ran >2h today. Let's avoid that.

ci: add timeout to `test_common_wheels`

---

.gitignore
crates/pixi_build_types/src/project_model.rs
crates/pixi_command_dispatcher/src/source_build/mod.rs
crates/pixi_glob/src/snapshots/pixi_glob__glob_hash__test__glob_hash_case_1_satisfiability.snap
src/lock_file/satisfiability/snapshots/pixi__lock_file__satisfiability__tests__failing_satisiability@source-dependency-changed-project-model.snap
tests/data/non-satisfiability/source-dependency-changed-project-model/pixi.lock
tests/data/satisfiability/source-dependency/pixi.lock

Implements custom Hash traits for ProjectModelV1 and all nested types that skip default/empty values in hash calculation for better stability. This allows adding new optional fields without breaking existing hashes, improving cache consistency and reducing unnecessary rebuilds.
- Removed `#[derive(Hash)]` from all ProjectModelV1 types
- Implemented manual Hash traits that ignore:
- `None` values in Option fields  
- Empty OrderMap collections
- Default struct values
- Used discriminant values for enum variants to ensure consistency
- Added .gitignore pattern for `*.local.*` files
**Before**: Adding any new field would change the hash, breaking cache invalidation
```rust
// Adding a new optional field would change hash even if None
pub struct ProjectModelV1 {
pub name: String,
pub …
```

feat: implement stable hash for ProjectModelV1 to improve cache consistency

---

docs/integration/third_party/conda_deny.md

@Hofer-Julian
Just noticed that I skipped a (not so unimportant) word - in #4090.
I also did a minor cosmetic adjustment to the output format section.
Sorry for the overhead.

docs: fix conda_deny documenation

---

crates/pixi_manifest/src/pypi/pypi_options.rs
crates/pixi_progress/src/lib.rs
src/global/common.rs
src/global/project/mod.rs

This should fix the global progress bars from cluttering while doing something like an update.
I also seemed like the added macro did not accept a trailing comma, so I capture the entire token-tree instead, and forward that which according to the LLM should be fine.
Its now back to:

fix: global progress

---

crates/pixi_command_dispatcher/src/backend_source_build/mod.rs
crates/pixi_command_dispatcher/src/install_pixi/mod.rs
crates/pixi_command_dispatcher/src/lib.rs
crates/pixi_command_dispatcher/src/source_build/mod.rs
src/cli/build.rs

This adds veeeeryyy preliminary build profiles to source builds. In development mode we build editable packages and in release mode we dont. Release mode is used during pixi build and development mode is used when installing a pixi environment.
This fixes a regression where `pixi build` would build an editable package.
There is also some more tracing code in here which allowed me to debug some issues.

fix: add build profiles to not build in editable mode in `pixi build`

---

docs/integration/ci/github_actions.md

https://github.com/prefix-dev/setup-pixi/pull/217

docs: Update setup-pixi docs

---

crates/pixi_command_dispatcher/src/command_dispatcher_processor/backend_build_source.rs
crates/pixi_command_dispatcher/src/reporter.rs
crates/pixi_command_dispatcher/tests/integration/event_reporter.rs
src/reporters/install_reporter.rs

Fixes #4074
At the moment `--verbose` has to be passed for Pixi to print build output. However, if the build fails we want the build output to be passed even if `--verbose` wasn't set. This PR fixes that.

fix: print build log if build fails

---

Cargo.lock
Cargo.toml
src/cli/init.rs
tests/integration_python/test_main_cli.py

Closes #4166.
@lucascolley I implemented the feature. Can you guide me on how your testing strategy imposes tests for this change?

feat: prevent pixi init to be executed in parent of pixi home directory

---

tests/integration_python/test_edge_cases.py
tests/integration_python/test_reinstall.py

These tests use a `PIXI_CACHE_DIR` making them slower than normal tests. So added the extra_slow tag to them to avoid red CI on them taking longer then 100 sec.

chore: make none cached sharing tests extra slow

---

crates/pixi_build_frontend/src/backend/json_rpc.rs
crates/pixi_build_frontend/src/backend/mod.rs
crates/pixi_build_frontend/src/tool.rs
crates/pixi_build_types/src/lib.rs
crates/pixi_command_dispatcher/src/build_backend_metadata/mod.rs
crates/pixi_command_dispatcher/src/command_dispatcher/instantiate_backend.rs
crates/pixi_command_dispatcher/src/instantiate_tool_env/mod.rs
crates/pixi_command_dispatcher/src/solve_pixi/mod.rs
crates/pixi_command_dispatcher/src/source_build/mod.rs
crates/pixi_command_dispatcher/src/source_metadata/mod.rs
crates/pixi_utils/src/reqwest.rs

Adds more logging to determine which build backend is installed and what the backend is doing. Also removes some logging that I deemed unnecessary.

chore: add better logging for build backends

---

docs/index.md

Text has the quoting backwards which caused an error:
Pre-recorded demo has it correct:

fix: Quick Demo example shell quoting

---

src/workspace/environment.rs
tests/integration_python/test_run_cli.py

This PR is to fix: https://github.com/prefix-dev/pixi/issues/4116
What I changed
As self.features() would put "default" envs in the last item, but the "default" env priority should be the lowest.Here, we use rfold (reverse fold) to ensure later features override earlier features for environment variables. Processing features in reverse order means that features appearing later in the list will have higher precedence.
Example: If features: [override_feature, user_feature, default]
rfold processes as: [default, user_feature, override_feature]
Result: override_feature env vars take precedence over all others.

fix: feature activation environment variable priority

---

crates/pixi_config/src/lib.rs
tests/integration_python/test_main_cli.py

Apparently, we are not allowed to use `"*"` or `">"` in fish completions. This fixes that and adds a test so it doesn't come back.
Fixes #4308

fix: fish completion script

---

docs/integration/ci/github_actions.md

Companion to https://github.com/prefix-dev/setup-pixi/pull/220

docs: Add keyring auth support doc and bump setup-pixi action version

---

src/cli/add.rs
src/cli/cli_config.rs
src/cli/install.rs
src/cli/list.rs
src/cli/mod.rs
src/cli/reinstall.rs
src/cli/remove.rs
src/cli/run.rs
src/cli/shell.rs
src/cli/shell_hook.rs
src/cli/tree.rs
src/cli/upgrade.rs
src/cli/workspace/export/conda_explicit_spec.rs
tests/integration_rust/common/mod.rs
tests/integration_rust/upgrade_tests.rs

There was some very custom machinery to check `--frozen` and `--locked` conflicts. While just using clap will do, this removes all of that and adds clap conflict. Also removes related tests.
Ran the commands manually with `--locked` etc. and through env variables and conflicts seem to work.

refactor: remove manual conflicts check for `--frozen` & `--locked`

---

crates/pixi_reporters/src/download_verify_reporter.rs
crates/pixi_reporters/src/main_progress_bar.rs

This PR fixes #4402 .
Thanks to the excellent debugging skills of @s22chan, a deadlock was discovered. The fix was to release the contested lock earlier, eliminating the race condition.

fix: occassionally hangs on exit

---

crates/pixi_core/src/lock_file/update.rs
crates/pixi_utils/src/reqwest.rs
tests/integration_rust/pypi_tests.rs

We found out that when updating pypi records that require a prefix there might be a race condition when solving for multiple platforms in parallel. This PR eliminates that race condition.

fix: ensure we only create pypi prefix once

---

pixi.toml
scripts/install.py

I use this task all the time, especially with git worktrees as an alias to de target folder does not work. I would like to use the debug version a lot of the time though, because of the faster compilation times. Especially when iterating. I opted *not* to use task arguments cause this autocompletes more nicely.

feat: add install-as-debug task

---

docs/reference/pixi_manifest.md
schema/model.py
schema/schema.json

We forgot to update the schema, this fixes that

fix: adapt schema for `[workspace.target.OS.build-variants]`

---

crates/pixi_cli/src/install.rs
crates/pixi_core/src/environment/mod.rs
crates/pixi_core/src/lock_file/install_subset.rs
crates/pixi_core/src/lock_file/update.rs
docs/reference/cli/pixi/install.md
tests/integration_rust/common/builders.rs
tests/integration_rust/install_filter_tests.rs

This augments the abilities introduced in #4404, with the ability to do multiple `--only`, before only one `--only` flag was accepted. In the end the technical change for this was pretty easy, we just add multiple starting points to the reachability analysis instead of one single root. These will then all be iterated through at some point. 
An additional thing that was added is a test to verify that `pixi install --only a --skip-with-deps a` skips the package. Something I felt was missing from the original test-suite.
1. Added extra unit tests.
2. User tested:
```bash
╰─ pixi-dev i --only click …
```

feat: add the option for multiple `--only` flags.

---

crates/pixi_core/src/environment/mod.rs
crates/pixi_core/src/lock_file/update.rs
tests/integration_rust/install_filter_tests.rs

There was a problem when doing a subset install like:
```bash
pixi init
pixi add python
pixi add --pypi flask
pixi install --only flask --skip-with-deps click
pixi r python -c "import click" # <--- This would error
```
Would not work. Now we invalidate the QuickValidation by writing out an **invalid environment hash**. The end-to-end test has also been updated accordingly.

fix: environment never recovering after subset install

---

crates/pixi_cli/src/cli_config.rs
crates/pixi_cli/src/install.rs
crates/pixi_cli/src/lib.rs
crates/pixi_cli/src/reinstall.rs
crates/pixi_docs/src/main.rs
docs/reference/cli/pixi/add.md
docs/reference/cli/pixi/exec.md
docs/reference/cli/pixi/install.md
docs/reference/cli/pixi/list.md
docs/reference/cli/pixi/reinstall.md
docs/reference/cli/pixi/remove.md
docs/reference/cli/pixi/run.md
docs/reference/cli/pixi/shell-hook.md
docs/reference/cli/pixi/shell.md
docs/reference/cli/pixi/tree.md
docs/reference/cli/pixi/upgrade.md
docs/reference/cli/pixi/workspace/channel/add.md
docs/reference/cli/pixi/workspace/channel/remove.md
docs/reference/cli/pixi/workspace/export/conda-explicit-spec.md

This attempts to fix: https://github.com/prefix-dev/pixi/issues/4466. the issue that I re-introduced inadvertently.
I tried to do most of it through clap, this will change the CLI a bit that `--frozen=true` and `--locked=true` are allowed, and `false` for that matter. The `requires_equal` means you *cannot* use `--locked true`. But the big upside is that we are using mainly clap machinery to parse, which from my point of view is a big advantage. It also uses less code to boot. 
From my tests it seems that the env vars and how they are interpreted work as you would expect, i.e., the CLI options take precedence. But could be that I'm missing something.
I've tested the following:
```bash
PIXI_FROZEN=true PIXI_LOCKED=false pixi-dev i --frozen …
```

feat: attempt to fix --frozen and --locked story

---

crates/pixi_reporters/src/sync_reporter.rs

Instead of always running with `pixi build/install -v` now the build output will always be shown, unless you run with `-q` to silence the output. 
We should still work on an improved experience because it's a bit to much for big builds with multiple packages, but it's better than nothing for now. 
fixes: https://github.com/prefix-dev/pixi/issues/4391

fix: default to outputting build  logs

---

crates/pixi_command_dispatcher/src/command_dispatcher_processor/mod.rs

The problem was that `reporter_context` when solving pixi environments, assumes that `self.solve_pixi_environments[id]` is present. This doesn't seem to be guaranteed if one of the solves fails, in our test case we had an invalid path for a source dependency.
By checking if there's actually an entry for `id` we avoid panicking during indexing

fix: panic on moving source location

---

crates/pixi_command_dispatcher/src/solve_pixi/source_metadata_collector.rs
crates/pixi_command_dispatcher/src/source_metadata/mod.rs

Before:
```
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
╰─▶   × the package 'ros-jazzy-my-python-ros-apkg' is not provided by the project located at 'src/my_python_ros_pkg'
help: No packages are provided by the build-backend
```
After:
```
Error:   × failed to solve requirements of environment 'default' for platform 'osx-arm64'
╰─▶   × the package 'ros-jazzy-my-python-ros-apkg' is not provided by the project located at 'src/my_python_ros_pkg'
help: The build backend does provide other packages, did you mean 'ros-jazzy-my-python-ros-pkg'?
```

fix: improve source metadata error

---

pixi.toml

I think we should do that manually

chore: don't autofix typos

---

Cargo.lock
crates/pixi_build_types/src/project_model.rs
crates/pixi_command_dispatcher/Cargo.toml
crates/pixi_command_dispatcher/src/build/build_cache.rs
crates/pixi_command_dispatcher/src/build/mod.rs
crates/pixi_command_dispatcher/src/source_build/mod.rs
crates/pixi_command_dispatcher/src/source_build_cache_status/mod.rs
crates/pixi_stable_hash/Cargo.toml
crates/pixi_stable_hash/src/json.rs
crates/pixi_stable_hash/src/lib.rs
crates/pixi_stable_hash/src/map.rs

Fixes #4403
Currently, the build cache does not include any information about the project model or the configuration. This caused pixi to relock a package but not rebuild a package if one of the dependencies is changed. This PR adds a hash to the cache that describes the content of the packages project model and backend configuration. 
I left a TODO in place, which could be implemented to improve the performance of checking this hash. This could speed up checking if something changed at all. 
This PR also extends the stable hash crate with the ability to hash json values and generic maps.

fix: rebuild if dependencies changed

---

crates/pixi_manifest/src/pypi/merge.rs
crates/pixi_manifest/src/pypi/mod.rs
crates/pixi_manifest/src/pypi/pypi_options.rs
crates/pixi_manifest/src/utils/mod.rs

I had this refactor in my mind for a long time, but now got around with it with codex. Basically it makes the complex merging of PyPIOptions easier to read, by defining a few standard methods for use with merging. Basically making it more of a declarative read.
Better to read the diff side-by-side to see the benefit.

refactor: PyPI merge logic so that its more easy to extend

---

Cargo.lock
crates/pixi_core/Cargo.toml
crates/pixi_core/src/environment/pypi_prefix.rs

We've parallelized the check if a PyPI distribution was installed using the pixi uv installer or not. When the distribution is not installed by `pixi-uv` (e.g. a conda package) we can early out.
We also optimized reading the INSTALLER file by first checking the length of the file. If the length is not the same as the length of the "uv-pixi" string we can early out. This drastically reduces the IO required to perform the check.
For a large environment with roughly 367 conda installed python packages this provides a very large speedup:
**Before `109ms`:**
**After `3.9ms`:**

perf: early out on installer file not containing the pixi uv installer

---

.gitignore
docs/build/package_source.md
docs/build/ros.md
docs/source_files/pixi_workspaces/pixi_build/ros_ws/.gitattributes
docs/source_files/pixi_workspaces/pixi_build/ros_ws/.gitignore
docs/source_files/pixi_workspaces/pixi_build/ros_ws/pixi.lock
docs/source_files/pixi_workspaces/pixi_build/ros_ws/pixi.toml
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_cmake_ros_pkg/CMakeLists.txt
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_cmake_ros_pkg/package.xml
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_cmake_ros_pkg/pixi.toml
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_cmake_ros_pkg/src/my_cmake_node.cpp
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_python_ros_pkg/my_python_ros_pkg/my_python_node.py
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_python_ros_pkg/package.xml
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_python_ros_pkg/pixi.toml
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_python_ros_pkg/setup.cfg
docs/source_files/pixi_workspaces/pixi_build/ros_ws/src/my_python_ros_pkg/setup.py
mkdocs.yml
tests/integration_python/test_docs_examples.py

This adds a tutorial how to get started with a ROS workspace with `pixi build`.
- It setups a workspace manifest
- Builds two packages, CMake and Python
- Shows how to run the packages
- Shows how to build a conda package

docs: add `pixi-build-ros` tutorial

---

crates/pixi_cli/src/init.rs
mkdocs.yml
tests/integration_python/test_main_cli.py

A before and after:
The link was broken, and the user still didn't know what to do to avoid this warning without reading the documentation.

fix: Documentation link and error in `pixi init`

---

lefthook.yaml

Typecheck takes 10s on my machine
We can reconsider as soon as we move to a fast typechecker like pyrefly or ty

chore: move python typecheck to slow

---

docs/reference/pixi_manifest.md

docs: fix broken hyperlink

---

crates/pixi_utils/src/conda_environment_file.rs
tests/integration_python/common.py
tests/integration_python/test_edge_cases.py
tests/integration_python/test_init.py
tests/integration_python/test_main_cli.py
tests/integration_python/test_shell.py

fix(init): obscure error when importing `environment.yml` with empty `pip:`

---

Cargo.lock
crates/pixi/tests/integration_rust/pypi_tests.rs
crates/pixi_uv_conversions/Cargo.toml
crates/pixi_uv_conversions/src/conversions.rs
crates/pixi_uv_conversions/src/types.rs

Entries like this one, used to break the requirement conversion:
```toml
[tool.uv.sources]
torch = [
{ index = "pytorch-cpu", extra = "cpu" },
{ index = "pytorch-cu121", extra = "gpu" },
]
```
This PR adapts the conversion so it doesn't fail on it
Fixes #4325

fix(pypi): optional dependencies break requirement conversion code

---

.github/workflows/scorecard.yml

The [OpenSSF Scorecard](https://scorecard.dev/) is a common tool to assess the quality of a dependency for "risky practices". While the project itself calculates the score for a lot of projects, we would like to add it directly here to ensure the "shortcomings" are visible to maintainer and also because the workflow gets a bit more visibility into the repository settings, it will also lead to a higher score.
For an example output, see https://scorecard.dev/viewer/?uri=github.com/Quantco/pixi-pack
I'm also happy to help to get a better score ;)

ci: Add GHA workflow to calculate the OpenSSF scorecard.

---

crates/pixi_api/src/context.rs
crates/pixi_api/src/lib.rs
crates/pixi_api/src/workspace/init/mod.rs
crates/pixi_api/src/workspace/mod.rs
crates/pixi_api/src/workspace/reinstall/mod.rs
crates/pixi_api/src/workspace/task/mod.rs
crates/pixi_api/src/workspace/workspace/name.rs
crates/pixi_cli/src/cli_interface.rs
crates/pixi_cli/src/init.rs
crates/pixi_cli/src/reinstall.rs
crates/pixi_cli/src/task.rs
crates/pixi_cli/src/workspace/name.rs
crates/pixi_manifest/src/task.rs

Implements the required logic for `pixi task ...` in `pixi_api`, including
- `pixi task list`
- `pixi task add`
- `pixi task alias`
- `pixi task remove`
In addition to that, some minor refactors inside `pixi_api`.

feat(pixi_api): Implement task support for WorkspaceContext

---

Cargo.lock
Cargo.toml
crates/pixi/tests/integration_rust/solve_group_tests.rs
crates/pixi_cli/src/search.rs
crates/pixi_command_dispatcher/Cargo.toml
crates/pixi_command_dispatcher/src/command_dispatcher/builder.rs
crates/pixi_command_dispatcher/src/command_dispatcher/mod.rs
crates/pixi_command_dispatcher/src/install_pixi/mod.rs
crates/pixi_core/Cargo.toml
crates/pixi_core/src/workspace/mod.rs
crates/pixi_git/Cargo.toml
crates/pixi_git/src/git.rs
crates/pixi_git/src/resolver.rs
crates/pixi_git/src/source.rs
crates/pixi_global/Cargo.toml
crates/pixi_global/src/common.rs
crates/pixi_global/src/project/mod.rs
crates/pixi_python_status/Cargo.toml
crates/pixi_python_status/src/lib.rs
crates/pixi_utils/src/reqwest.rs
crates/pypi_mapping/Cargo.toml
crates/pypi_mapping/src/custom_mapping.rs
crates/pypi_mapping/src/lib.rs
crates/pypi_mapping/src/prefix/compressed_mapping_client.rs
crates/pypi_mapping/src/prefix/hash_mapping_client.rs

This PR updates the code to use the latest rattler release and introduces the use of `LazyClient` to ensure we only initialize a reqwest client when we actually need to. This should then speed things up when this is not the case.
Closes https://github.com/prefix-dev/pixi/pull/4656

perf: initialize the reqwest client lazily

---

crates/pixi_core/src/lock_file/update.rs
crates/pixi_install_pypi/src/lib.rs

This PR improves performance of any command that install an environment by lazily evaluating the activation variables. We only need the activation variables when we will be building an sdist, which is very often not the case. 
Previously, we were _always_ activating the environment when we needed to get an up-to-date environment. 
Testing this locally on my machine, pixi feels much more snappy.

perf: lazily initialize environment variables for sdist environments

---

crates/pixi_cli/src/workspace/export/snapshots/pixi_cli__workspace__export__conda_environment__tests__test_export_conda_env_yaml.snap
tests/data/mock-projects/test-project-export/pixi.toml
tests/scripts/test-export.sh

x-ref: https://github.com/prefix-dev/pixi/pull/4658#issuecomment-3369051070

fix: fix test-exports integration test after PR4658

---

crates/pixi_cli/src/build.rs

When `--manifest-path` is specified for `pixi build` it gets double prefixed and fails with error like this:
```
remi@mi:~/Projects/Mine/pixi/main$ pixi build --manifest-path examples/pixi-build/array-api-extra/pixi.toml
Error:   × failed to discover a valid project manifest, the source path '/home/remi/Projects/Mine/pixi/main/examples/pixi-build/array-api-extra/examples/pixi-build/array-api-
│ extra/pixi.toml' could not be found
```
Which happens because given manifest path is added to the discovered workspace root directory.
Compute relative path from workspace root to the given (canonicalized) manifest path.
Run following command from the root dir of the repository to test that it doesn't work on main:
```sh
pixi build --manifest-path examples/pixi-build/array-api-extra/pixi.toml
``` …

fix(build): double relative manifest path

---

crates/pixi_core/src/lock_file/satisfiability/mod.rs
crates/pixi_uv_conversions/src/requirements.rs
crates/pixi_uv_conversions/src/types.rs

While working on this issue: https://github.com/prefix-dev/pixi/issues/4573
I made the first intial fix to parse directory requirements, correctly. Alas, this does not fix that issue as we need to set the editable boolean directly, this however is a bigger change, so I wanted to get this in first.

feat: correctly parse directory requirements
